### ISSUE TITLE
stop_task_build(state, worker)`: ! Failed to build source package terra.

### ISSUE THREAD

**Issue by 13954380607** [giotto-suite/Giotto#1005]
pak::pkg_install("drieslab/Giotto")
                                                                   
→ Will install 73 packages.
→ All 73 packages (88.32 MB) are cached.
+ beachmat            2.20.0    [bld][cmp]
+ BH                  1.84.0-0  [bld]
+ BiocParallel        1.38.0    [bld][cmp]
+ BiocSingular        1.20.0    [bld][cmp]
+ bslib               0.8.0     [bld]
+ cachem              1.1.0     [bld][cmp]
+ cowplot             1.1.3     [bld]
+ crosstalk           1.2.1     [bld]
+ data.table          1.15.4    [bld][cmp]
+ dbscan              1.2-0     [bld][cmp]
+ DelayedArray        0.30.1    [bld][cmp]
+ dplyr               1.1.4     [bld][cmp]
+ dqrng               0.4.1     [bld][cmp]
+ farver              2.1.2     [bld][cmp]
+ FNN                 1.1.4     [bld][cmp]
+ fontawesome         0.5.2     [bld]
+ fs                  1.6.4     [bld][cmp]
+ ggplot2             3.5.1     [bld]
+ ggrepel             0.9.5     [bld][cmp]
+ Giotto              4.1.0     [bld][cmp] (GitHub: 2b5fd0b)
+ GiottoClass         0.3.4     [bld][cmp] (GitHub: 57cf471)
+ GiottoUtils         0.1.10    [bld][cmp] (GitHub: 0e6b174)
+ GiottoVisuals       0.2.4     [bld][cmp] (GitHub: 1d2d7f5)
+ gtable              0.3.5     [bld]
+ htmltools           0.5.8.1   [bld][cmp]
+ htmlwidgets         1.6.4     [bld]
+ httr                1.4.7     [bld]
+ igraph              2.0.3     [bld][cmp]
+ IRanges             2.38.1    [bld][cmp]
+ irlba               2.3.5.1   [bld][cmp]
+ jquerylib           0.1.4     [bld]
+ later               1.3.2     [bld][cmp]
+ lifecycle           1.0.4     [bld]
+ limma               3.60.4    [bld][cmp]
+ Matrix              1.7-0     [bld][cmp]
+ MatrixGenerics      1.16.0    [bld]
+ matrixStats         1.3.0     [bld][cmp]
+ memoise             2.0.1     [bld]
+ mgcv                1.9-1     [bld][cmp]
+ nlme                3.1-165   [bld][cmp]
+ pillar              1.9.0     [bld]
+ plotly              4.10.4    [bld]
+ promises            1.3.0     [bld][cmp]
+ purrr               1.0.2     [bld][cmp]
+ RcppAnnoy           0.0.22    [bld][cmp]
+ RcppEigen           0.3.4.0.0 [bld][cmp]
+ RcppTOML            0.2.2     [bld][cmp]
+ reshape2            1.4.4     [bld][cmp]
+ reticulate          1.38.0    [bld][cmp]
+ rlang               1.1.4     [bld][cmp]
+ rmarkdown           2.27      [bld]
+ RSpectra            0.16-2    [bld][cmp]
+ rsvd                1.0.5     [bld]
+ Rtsne               0.17      [bld][cmp]
+ S4Arrays            1.4.1     [bld][cmp]
+ S4Vectors           0.42.1    [bld][cmp]
+ sass                0.4.9     [bld][cmp]
+ ScaledMatrix        1.12.0    [bld]
+ scales              1.3.0     [bld][cmp]
+ scattermore         1.2       [bld][cmp]
+ sitmo               2.0.2     [bld][cmp]
+ sp                  2.1-4     [bld][cmp]
+ SparseArray         1.4.8     [bld][cmp]
+ sparseMatrixStats   1.16.0    [bld][cmp]
+ stringi             1.8.4     [bld][cmp]
+ stringr             1.5.1     [bld]
+ terra               1.7-78    [bld][cmp]
+ tibble              3.2.1     [bld][cmp]
+ tidyr               1.3.1     [bld][cmp]
+ tidyselect          1.2.1     [bld][cmp]
+ uwot                0.2.2     [bld][cmp]
+ vctrs               0.6.5     [bld][cmp]
+ XVector             0.44.0    [bld][cmp]
ℹ No downloads are needed, 73 pkgs (88.32 MB) are cached
ℹ Building BH 1.84.0-0
ℹ Building data.table 1.15.4
ℹ Building dbscan 1.2-0
ℹ Building farver 2.1.2
ℹ Building FNN 1.1.4
ℹ Building fs 1.6.4
ℹ Building httr 1.4.7
ℹ Building Matrix 1.7-0
ℹ Building matrixStats 1.3.0
ℹ Building nlme 3.1-165
ℹ Building RcppAnnoy 0.0.22
ℹ Building RcppEigen 0.3.4.0.0
ℹ Building RcppTOML 0.2.2
ℹ Building rlang 1.1.4
ℹ Building Rtsne 0.17
ℹ Building sitmo 2.0.2
ℹ Building stringi 1.8.4
ℹ Building terra 1.7-78
ℹ Building limma 3.60.4
ℹ Building S4Vectors 0.42.1
ℹ Building sp 2.1-4
✔ Built httr 1.4.7 (48.8s)                            
✔ Installed httr 1.4.7  (1.2s)                        
✖ Failed to build terra 1.7-78 (1m 25.1s)             
Error:                                                
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package terra.
Type .Last.error to see the more details.

**Comment by jiajic** [comment]
Hi, could you tell us what system you're installing on?

**Comment by 13954380607** [comment]
On hpc

**Comment by jiajic** [comment]
Can you make sure if you have these requirements already satisfied on the HPC? 
`GDAL (>= 2.2.3), GEOS (>= 3.4.0), PROJ (>= 4.9.3), sqlite3.` More info at terra's [github](https://github.com/rspatial/terra?tab=readme-ov-file#linux)

**Comment by 13954380607** [comment]
Yes, I think I have all of this and when I directly downloaded package terra, it gave me:  ERROR 1: PROJ: proj_create_from_database: Open of /home/dl2373/.conda/envs/r_env/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /home/dl2373/.conda/envs/r_env/share/proj failed
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘terra’
* removing ‘/home/dl2373/.conda/envs/r_env/lib/R/library/.renv/1/terra’
install of package 'terra' failed [error code 1]. I tried many methods and made sure my proj in the right direction, but it still didn't work.
Thank you.

**Comment by JunxiangXu** [comment]
If you are using a shared cluster, you probably need to load these dependencies separately. Trying to build terra using any of the dependencies from a specific conda environment will make it hard to manage in the future. 
If you have sudo access to the HPC, you can probably build terra using the dependencies with

sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install libgdal-dev libgeos-dev libproj-dev 

For more information please refer to: https://github.com/rspatial/terra

**Comment by jiajic** [comment]
Guessing this is resolved now.
