### ISSUE TITLE
File does not exit

### ISSUE THREAD

**Issue by 13954380607** [giotto-suite/Giotto#1007]
> # Provide path to your data folder
> data_path = '/home/dl2373/new/raw_feature_bc_matrix/'
> # Create Giotto Visium Object
> visium_kidney = createGiottoVisiumObject(visium_dir = data_path,
+                                          expr_data = 'raw',
+                                          png_name = 'tissue_lowres_image.png',
+                                          gene_column_index = 2,
+                                          instructions = instrs)
A structured visium directory will be used
Error: [Giotto]
 /home/dl2373/new/raw_feature_bc_matrix/ does not exist!
Description: I have a raw data in this direction, but I don't understand why it always gave me that this file doesn't exit.  Is it because the Giotto package is wrong?
Thank you

**Comment by RubD** [comment]
Try with:
`data_path = '/home/dl2373/new/'`

And also check `dir.exists(data_path)`

**Comment by 13954380607** [comment]
Thank you so much!

**Comment by jiajic** [comment]
Guessing this is resolved. Please reopen if not.
