### ISSUE TITLE
Export and create Giotto Viewers

### ISSUE THREAD

**Issue by 13954380607** [giotto-suite/Giotto#1012]
[combineMetadata](https://drieslab.github.io/GiottoClass/reference/combineMetadata.html)(visium_kidney)

# select annotations, reductions and expression values to view in Giotto Viewer
viewer_folder = [paste0](https://rdrr.io/r/base/paste.html)(results_folder, '/', 'mouse_visium_kidney_viewer')

[exportGiottoViewer](https://drieslab.github.io/Giotto_website/reference/exportGiottoViewer.html)(gobject = visium_kidney,
                   output_directory = viewer_folder,
                   fa[c](https://rdrr.io/r/base/c.html)tor_annotations = c('in_tissue',
                                          'leiden_[c](https://rdrr.io/r/base/c.html)lus'),
                   numeri[c](https://rdrr.io/r/base/c.html)_annotations = c('nr_feats'),
                   dim_redu[c](https://rdrr.io/r/base/c.html)tions = c('tsne', 'umap'),
                   dim_reduction_names = c('tsne', 'umap'),
                   expression_values = 'scaled',
                   expression_rounding = 2,
                   overwrite_dir = T)

Error:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'j' in selecting a method for function '[': could not find function "."

**Comment by josschavezf** [comment]
Hi @13954380607, unfortunately, the Giotto viewer is no longer supported. We are working on creating new visualization tools. In the meantime, you can still generate the dimension reductions and spatial plots using the spatPlot, spatFeatPlot, plotUMAP, and plotPCA functions.

**Comment by josschavezf** [comment]
Hi @13954380607 we recently implemented the interactive visualization with vitessceR. I suggest taking a look at the tutorials: https://drieslab.github.io/Giotto_website/articles/interactive_giotto_vitessceR.html https://drieslab.github.io/Giotto_website/articles/interactive_selection_cosmx.html
