### ISSUE TITLE
Importing Ligand Receptor txt file

### ISSUE THREAD

**Issue by 17nguyenc** [giotto-suite/Giotto#1013]
Hi, 

I am attempting Ligand-Receptor cell-cell communication data analysis. I cannot import the txt file that is from the giotto package:

```
` > LR_data <- data.table::fread(system.file("extdata", "mouse_ligand_receptors.txt", package = "Giotto"))

Error in data.table::fread(system.file("extdata", "mouse_ligand_receptors.txt",  : 
  Input is empty or only contains BOM or terminal control characters

> list.files(system.file("extdata", package = 'Giotto'), recursive = T, full.names = T)

[1] "/home/cn/R/x86_64-redhat-linux-gnu-library/4.3/Giotto/extdata/additional_r_packages.txt"
[2] "/home/cn/R/x86_64-redhat-linux-gnu-library/4.3/Giotto/extdata/giotto_python_modules.txt" `
```

Did I miss a step in getting this file? Is it supposed to be part of the Giotto library? 

Please advise. Thank you!

**Comment by josschavezf** [comment]
@17nguyenc, apologies for the confusion. The mouse_ligand_receptors.txt file is in the GiottoData package instead of Giotto. 

You can use:

LR_data <- data.table::fread(system.file("extdata", "mouse_ligand_receptors.txt", package = "GiottoData"))
