### ISSUE TITLE
loading Cosmx NSCLC FFPE giotto object

### ISSUE THREAD

**Issue by batukav** [giotto-suite/Giotto#1017]
Dear all,

I am trying to load the Giotto object from CosMx website (https://nanostring-public-share.s3.us-west-2.amazonaws.com/SMI-Compressed/SMI-ReadMe.html). I have downloaded the file, which is around 3.5GB, and tried to load it into my R session.

In the website they suggest using the Giotto commit `0c8c2866e881b1c6b35ddc97c24dcb58b555c375` of the suite branch. To install that version, I did the following: 

`devtools::install_github("drieslab/Giotto@0c8c2866e")`

When I load the object, I am getting the following error:

```
> my_data <- load("SMI_Giotto_Object.RData")
> ls(my_data)
Error in as.environment(pos) : no item called "gem" on the search list
```

and my_data object only returns this:

```
> my_data
[1] "gem"

```
This is my first interaction with R and unfortunately I couldn't figure out what might be the issue here. I'd very much appreciate any help.

Thank you,
Batuhan

**Comment by josschavezf** [comment]
Hi @batukav you don't need to redirect the load to a variable, just run load("SMI_Giotto_Object.RData") and the gem object will appear in the environment
