### ISSUE TITLE
Issue with Reproducing Example Results

### ISSUE THREAD

**Issue by Delun-Chen** [giotto-suite/Giotto#1029]
Hello,
I am a graduate student in bioinformatics, and I have been following your tool and tutorial guide. However, when I was working through the SeqFish+ Mouse Cortex Example (https://drieslab.github.io/Giotto_website/articles/seqfish_cortex.html), I was unable to reproduce the exact same results, particularly in the clustering part. This discrepancy seems to affect the subsequent cell type annotation outcome.
Could you please advise on how I can modify my approach to achieve the same results as shown in the tutorial? Alternatively, would it be possible for you to provide the final cell type annotation data?

Thank you for taking the time to read my message. I greatly appreciate your help.

Here is my contact email:
lawrance5216@gmail.com
![5-UMAP](https://github.com/user-attachments/assets/d0ecd2cc-0e74-41d6-8bd6-d0aa224d022c)
![12-spatDimPlot2D](https://github.com/user-attachments/assets/0d22b5bd-f17a-4801-8ca0-5d30831ce9ec)

**Comment by josschavezf** [comment]
Hi @Delun-Chen, these changes happen with new versions of the packages that run the dimension reduction steps. Unfortunately, I couldn't find the version of the packages used to create the tutorial initially. I updated the tutorial and results and provided the Giotto version and the new cell type annotation. I hope it helps reproduce the analysis. I had an issue running the function plotCellProximityFeats (I'm working on fixing it), but the rest of the analysis works fine.
