### ISSUE TITLE
 sparse->dense coercion: allocating vector of size 1.2 GiB

### ISSUE THREAD

**Issue by MustafaElshani** [giotto-suite/Giotto#1032]
**Describe the Error**
I have transcript level data from Visium slides generated using nanopore, the code below generating `addStatistics` gives and error however at gene level analysis the error does not occur. 

...

**Error Message**

<details>

```r
## Add statistics to the Giotto object
SpatialTrans_DMSO_ONTtrans_statistics <- addStatistics(
  gobject = SpatialTrans_DMSO_ONTtrans,
  expression_values = "raw",  # Use raw expression values
  detection_threshold = 0
)
Warning message:
In asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.2 GiB
```
</details>

**To Reproduce**

Steps to reproduce the behavior, i.e.:
1. Following tutorial file '[Visium part I](https://drieslab.github.io/giotto_workshop_2024/visium-part-i.html#quality-control)'
2. Download data 'Own Data'
3. Run function(s) `addStatistics(
  gobject = SpatialTrans_DMSO_ONTtrans,
  expression_values = "raw",  # Use raw expression values
  detection_threshold = 0
)`

**Expected behavior**

Producing nr_feats and total_expr stats

**Screenshots**

N/A

**System Information**

Please replace the following according to your machine:
Ubuntu 22.04
    - R = 4.4.1
    - Giotto 4.1
    - Python  v 3.10.2

**Additional context**

These are nanopore sequencing data . 

`Use objHistory() to see steps and params used
[1] 31410  4982`

**Comment by josschavezf** [comment]
Hi @MustafaElshani, it doesn't seem to be an error but just a warning. The scaling step requires creating a dense matrix, usually bigger than the raw data. Your statistics should still be in the cell metadata table.
