### ISSUE TITLE
Pseudobulk Differential Expression

### ISSUE THREAD

**Issue by MustafaElshani** [giotto-suite/Giotto#1047]
Is there away to analyse multiple spatial sample and find differential expressed genes using Giotto Suite?

I followed the [tutorial in working in multiple samples ](https://drieslab.github.io/giotto_workshop_2024/working-with-multiple-samples.html) however could not find an instructions in doing differential expression between samples, pseudobulk type approach?

**Comment by josschavezf** [comment]
Hi @MustafaElshani you can use the same function findMarkers_one_vs_all, but in the cluster column argument you have to provide the column with the sample ID, usually is "list_ID".

**Comment by MustafaElshani** [comment]
Thank you Joselyn 

I managed to work it out especially from you latest tutorials in https://drieslab.github.io/Giotto_website/articles/visium_prostate_integration.html
