### ISSUE TITLE
Filtered and raw matrices have different counts with createGiottoVisiumObject

### ISSUE THREAD

**Issue by PerrineLacour** [giotto-suite/Giotto#105]
Hello,

I tried to import some dataset from a Visium experiment (processed with spaceranger) to R with Giotto function createGiottoVisiumObject, and tried both filter and raw options.
However, after filtering the raw matrix to keep only spots under tissue (following the tutorial https://rubd.github.io/Giotto_site/articles/mouse_visium_brain_201226.html), I saw that both matrices (the one imported with `raw` option and filtered, and the one imported with `filter` option) don't contain the same information.
First, they don't have the same number of genes (raw: 260 spots and 19057 genes, filtered: 260 spots and 17847 genes).
Second, I don't have the same values in both matrices for some genes and barcodes. Here is some example:
raw:
        CAATTAAGGGTGATGA-1 CAATTTCGTATAAGGG-1 CACAATGAGCTGCTAT-1 CACACGCGCTGTCTTA-1 CACAGCACCCACGGCA-1
Mrpl15                   .                  .                  .                  .                  .
Pcmtd1                   .                  .                  .                  .                  .
Gm26901                  .                  .                  .                  .                  .
Snhg6                    .                  .                  .                  .                  .
Cops5                    .                  .                  .                  .                  .

filtered: 
        CAATTAAGGGTGATGA-1 CAATTTCGTATAAGGG-1 CACAATGAGCTGCTAT-1 CACACGCGCTGTCTTA-1 CACAGCACCCACGGCA-1
Mrpl15                   .                  2                  .                  2                  2
Pcmtd1                   2                  .                  2                  4                  1
Gm26901                  .                  .                  .                  .                  .
Snhg6                    4                  4                  2                  2                  .
Cops5                    6                  2                  3                  2                  3​

I tried to manually import the dataset from the files and I don't have this mismatch. I also have 32285 genes in both matrices.

Do you know where this is coming from?

Best regards,

Perrine Lacour

**Comment by ndelrossi7** [comment]
Hi @PerrineLacour! Would you be able to give me a bit more information on the data that you used? With the tutorial you would still need to download the data and manually input the path.

**Comment by RubD** [comment]
Hi Perrine, 
In addition to @ndelrossi7 input, here are my 2 cents:
1. The difference in number of genes between filtered and raw is normal. The raw matrix typically has a number (10 - 100s) of extra genes, which are filtered out once you remove some spurious spots that have little to no tissue coverage. I actually am surprised that you have the same number of spots in both the raw and filtered matrix. The matrix associated with the raw data should have many more spots.
2. It is surprising that you see different values for the same gene in the same spot when comparing filtered vs raw. In both instances it should indeed give you the same UMI counts. I did a quick check with the publicly available kidney dataset and I don't see the same results. In fact, both matrices are identical (see code below). So I'm not entirely sure what happened here. 

How did you manually extract the 10X matrix? Could you share your code?


# load library
library(Giotto)

# 1. extract 10X filtered data
filter_datadir = '/.../Visium_data/Kidney_data/filtered_feature_bc_matrix/'

## filter ensembl
filter_matrix1 = get10Xmatrix(path_to_data = filter_datadir, gene_column_index = 1)
filter_matrix1[1:5, 1:5]
dim(filter_matrix1)

## filter gene symbol
filter_matrix2 = get10Xmatrix(path_to_data = filter_datadir, gene_column_index = 2)
filter_matrix2[1:5, 1:5]
dim(filter_matrix2)




# 2. extract 10X raw data
raw_datadir = '/.../Data/Visium_data/Kidney_data/raw_feature_bc_matrix//'

## filter ensembl
raw_matrix1 = get10Xmatrix(path_to_data = raw_datadir, gene_column_index = 1)
raw_matrix1[1:5, 1:5]
dim(raw_matrix1)

## filter gene symbol
raw_matrix2 = get10Xmatrix(path_to_data = raw_datadir, gene_column_index = 2)
raw_matrix2[1:5, 1:5]
dim(raw_matrix2)



# 3. same values for filtered and raw?
intersect_genes = intersect(rownames(filter_matrix2), rownames(raw_matrix2))
intersect_spots = intersect(colnames(filter_matrix2), colnames(raw_matrix2))

## subset raw matrix and order according to filter matrix
raw_matrix2_filt = raw_matrix2[rownames(raw_matrix2) %in% intersect_genes, colnames(raw_matrix2) %in% intersect_spots]
raw_matrix2_filt = raw_matrix2_filt[rownames(filter_matrix2), colnames(filter_matrix2)]
raw_matrix2_filt[1:5, 1:5]

## is identical? YES
identical(filter_matrix2, raw_matrix2_filt)



# 4. manual
## check dimensions for filtered matrix
matrixDT = data.table::fread(input = paste0(filter_datadir,'/','matrix.mtx.gz'), header = F, skip = 3)
colnames(matrixDT) = c('gene_id_num', 'cell_id_num', 'umi')

## same dimensions as the filtered matrix? YES
length(unique(matrixDT$gene_id_num))
length(unique(matrixDT$cell_id_num))

**Comment by RubD** [comment]
Follow up: I realize that your observation was after you applied the filter step. The different number of genes starting between raw and filter matrix is still normal, but I'm not sure why the values are different.

Any chance you could give us some reproducible code? Thanks

**Comment by PerrineLacour** [comment]
Hi!

I am using some data from a Visium experiment made in the lab, not yet publicly available. Here is the code I used to import with Giotto:
```
filtered = createGiottoVisiumObject(visium_dir = "outs/",
                                    expr_data = "filter", png_name = 'tissue_lowres_image.png', gene_column_index = 2)

raw_visium = createGiottoVisiumObject(visium_dir = "outs/",
                                      expr_data = "raw", png_name = 'tissue_lowres_image.png', gene_column_index = 2)

raw_filt = subsetGiotto(raw_visium, cell_ids = raw_visium@cell_metadata$cell_ID[raw_visium@cell_metadata$in_tissue==1])

dim(raw_filt@raw_exprs) #[1] 19057   260
dim(filtered@raw_exprs) #[1] 17847   260

raw_ordered = raw_filt@raw_exprs[match(rownames(filtered@raw_exprs),rownames(raw_filt@raw_exprs)),
match(colnames(filtered@raw_exprs),colnames(raw_filt@raw_exprs))]
table(as.vector(raw_ordered)==as.vector(filtered@raw_exprs))
#  FALSE    TRUE 
#1196794 3443426 
```

To manually import the matrices:
```
filter_count_matrix_mtx=readMM("outs/filtered_feature_bc_matrix/matrix.mtx.gz")
rownames(filter_count_matrix_mtx) = fread("outs/filtered_feature_bc_matrix/features.tsv.gz", header=F)$V2
colnames(filter_count_matrix_mtx) = fread("outs/filtered_feature_bc_matrix/barcodes.tsv.gz", header=F)$V1

raw_count_matrix_mtx=readMM("outs/raw_feature_bc_matrix/matrix.mtx.gz")
rownames(raw_count_matrix_mtx) = fread("outs/raw_feature_bc_matrix/features.tsv.gz", header=F)$V2
colnames(raw_count_matrix_mtx) = fread("outs/raw_feature_bc_matrix/barcodes.tsv.gz", header=F)$V1
raw_count_matrix_mtx_filter = raw_count_matrix_mtx[,colnames(raw_count_matrix_mtx)%in%colnames(filter_count_matrix_mtx)]

dim(filter_count_matrix_mtx) #[1] 32285   260
dim(raw_count_matrix_mtx) #[1] 32285  4992
dim(raw_count_matrix_mtx_filter) #[1] 32285   260

table(as.vector(raw_count_matrix_mtx_filter)==as.vector(filter_count_matrix_mtx))
#   TRUE 
#8394100 
```
The matrix I get by manually importing the data is also the same as the h5 matrix, and the same as the one I get when importing with Seurat.
I never had the same problem with publicly available data, so this is also disturbing to me. I checked with 10X support but they confirmed that the output looks normal and thought that the problem could be while importing the data with Giotto.

Best,

**Comment by ndelrossi7** [comment]
Hi @PerrineLacour I've done some digging with the [public mouse brain dataset](https://support.10xgenomics.com/spatial-gene-expression/datasets/1.1.0/V1_Adult_Mouse_Brain). After filtering out genes with expression values of 0, the matrices all match up. Could you give this a try and see if that is what's causing the difference in matrix size?

However, I'm not sure why there would be a discrepancy in expression values. If you would like to privately send me the data (with all of the gene names changed [ie. gene1, gene2, etc.] so no results are identifiable), I would be happy to investigate further.

**Comment by PerrineLacour** [comment]
Hi, 

Sorry for the delay, indeed I get the same dimensions after removing genes that are not expressed in any spots.

Where could I send the data (I changed the gene names as you suggested) so you can have a look at it?

Best,

**Comment by ndelrossi7** [comment]
Hi @PerrineLacour you can email it to me at natalie.delrossi@mssm.edu.

**Comment by RubD** [comment]
Hi @PerrineLacour,
@ndelrossi7  and I have looked further into this issue and we made some changes, based on your input,  to fix this problem . You can simply reinstall Giotto and then this issue should be resolved.
Thanks for letting us know

**Comment by PerrineLacour** [comment]
Hi, 

Sorry for the delay, I had some problem installing the update. 

I checked and it works now, thank you a lot!
