### ISSUE TITLE
Incompatibility of Matrix version for runUMAP and Giotto

### ISSUE THREAD

**Issue by JKSe7en** [giotto-suite/Giotto#1063]
**Describe the Error**

I was trying to run function runUMAP following the tutorial of `Human Breast Cancer` (https://giottosuite.readthedocs.io/en/latest/subsections/datasets/xenium_breast_cancer.html) and got the error message below. It seems this function requires package `Matrix` to be version 1.6-1.
But the Giotto requires `Matrix` to be >= 1.6-2.

The version of Giotto I am using is 4.1.0.

Could you please let me know how to fix this? Thanks so much!

**Error Message**

<details>

```r
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) :
  function 'as_cholmod_sparse' not provided by package 'Matrix'
```
</details>

Please replace the following according to your machine:
 - Version [e.g. 4.0.1]
    - R 4.3.0
    - Giotto 4.1.0
    - Python

**Comment by josschavezf** [comment]
Hi @JKSe7en I believe this issue is fixed in the most recent version of Giotto (v4.1.5) I suggest updating the package. On the other hand, the website you are using is outdated, here is the new website: https://drieslab.github.io/Giotto_website/articles/xenium_breast_cancer.html
