### ISSUE TITLE
How to change Image Extend/cropping, make prefer an option

### ISSUE THREAD

**Issue by MustafaElshani** [giotto-suite/Giotto#1068]
### Discussed in https://github.com/drieslab/Giotto/discussions/1067

<div type='discussions-op-text'>

<sup>Originally posted by **MustafaElshani** November 13, 2024</sup>
Currently when subsetting or after filtering spatPlot shows the image up until nearest spot. How can I change this so that it shows the image as per spatial coordinates? I can see here that you have an option for prefer but how and where do we determine this its seems polygon is the defaults https://github.com/drieslab/GiottoVisuals/blob/9931ad26aacbafcbcd2c5e1e30a5c0417fb32a8a/R/gg_info_layers.R#L1400

</div>

**Comment by josschavezf** [comment]
Hi @MustafaElshani could you please provide a reproducible example with the code you are currently running?

**Comment by MustafaElshani** [comment]
Hi Joselyn 

George answered this in the discussion https://github.com/drieslab/Giotto/discussions/1067 now I use 
```
spatInSituPlotPoints(
  SpatialTrans_DMSO_ONTgene, 
  background_color = "white",
  polygon_fill = "leiden_clus",
  polygon_fill_as_factor = TRUE,
  show_image = TRUE,
  save_plot = FALSE,
  show_legend = FALSE,
  xlim = c(13800, 18300), 
  ylim = c(-17000, -14000)
```

while no attempted approach was working using `spatPlot2D()`

`spatInSituPlotPoints()` has Very useful especially when tissue is small and surround spots are filtered out and you want to increase the FOV.

i just need to figure out how to do the same with gene expression in visium rather than using `spatFeatPlot2D()`
