### ISSUE TITLE
dimFeatPlot2D cannot show gene expression difference in two samples

### ISSUE THREAD

**Issue by xhNorthwestern** [giotto-suite/Giotto#1069]
Hi,

I am using Giotto Suite to do single cell RNA-seq integrated analysis. I want to use dimFeatPlot2D to show one gene's expression difference in two samples. But it does not work. It seems that dimFeatPlot2D does not have "group_by = "list_ID",". Could you give me some suggestions on it? Thanks a lot!

Best wishes,
Xu

**Comment by jiajic** [comment]
Hi, thanks for reporting.
This should be possible now after you install GiottoVisuals 0.2.9 and restart the session.

**Comment by xhNorthwestern** [comment]
OK. Great. I will try it. Thanks a lot!
