### ISSUE TITLE
Reproducible Installation from source only?

### ISSUE THREAD

**Issue by serverhorror** [giotto-suite/Giotto#107]
Hello,

We'd like to try your method. We are running into a few challenges:

* http://spatialgiotto.rc.fas.harvard.edu/giotto.install.2.html &mdash; this talks about a Docker image but we cannot find a `Dockerfile` to reliably create the image in our system and we were unable to find it on hub.docker.com.
  
  Is it possible to add this so that we can rebuild the image internally?

* There's quite a bit of Python code and we're having trouble finding a `requirements.txt` file to rebuild a virtualenv with the package versions you've been using.

  Is it possible to add these so that a `pip install -r requirements.txt` works?

  (Of course if you prefer pipenv or poetry that's perfectly fine too)

**Comment by ndelrossi7** [comment]
Hi @serverhorror, thanks for reaching out! We have recently set up a new [Docker image](https://hub.docker.com/r/delron01/giotto) and I have pushed those changes today. I will be adding instructions to our [site](https://rubd.github.io/Giotto_site/index.html), but I will also add them here: 
1. `docker pull delron01/giotto:latest`
2. `docker run --rm -p 8787:8787 -e PASSWORD=mypassword delron01/giotto:latest` (note that you can use whatever port you want as long as it's available and any password you choose to set for yourself)
3. Open your browser > localhost:8787 (or localhost:yourport)
4. username: rstudio, password: mypassword

This will open an RStudio session and you'll be able to work with Giotto from there. Please let me know if you have any issues with this. 

Currently we have the function `installGiottoEnvironment()` which will create the environment with the necessary Python packages. I'll be working on creating a requirements.txt file with the same information - thank you for the feedback!

**Comment by ndelrossi7** [comment]
I am closing this issue but please don't hesitate to reach out with any questions in the future!

**Comment by serverhorror** [comment]
Thanks!

`installGiottoEnvironment` is a nice starting point. I'll try and see if I can pinpoint to exact versions of the Python packages.

Will you be adding a Dockerfile and requirements.txt (or similiar), I find conda to be quite cumbersome to use. My clients are _not_ able to use conda without licensing and it is quite hard to integrate something so far out of the typical software development ecosystem.

**Comment by ndelrossi7** [comment]
Hi @serverhorror, you can find the Dockerfile [here](https://github.com/RubD/Giotto/blob/master/Dockerfile) as well as the instructions for Docker usage [here](https://rubd.github.io/Giotto_site/articles/docker.html). Thanks again for the feedback regarding a requirements.txt file! We are looking into this. I would be happy to update you when it's complete. Thanks!

**Comment by RubD** [comment]
I would also like to add that `installGiottoEnvironment` will install miniconda and will use that to install all python modules. So while it is the easiest option for most users, it might not be compatible with your clients licensing policy. I'm unfortunately not familiar with this part of software development.
