### ISSUE TITLE
plotUMAP generate distorted pictures

### ISSUE THREAD

**Issue by xhNorthwestern** [giotto-suite/Giotto#1083]
Hi,

I used Giotto suite to analyze integrated two single cell RNA-seq datasets. 
When I ran the following code:
plotUMAP(gobject = giotto_SC,
         dim_reduction_name = 'umap_harmony',
         cell_color = 'leiden_harmony',
         show_NN_network = F,
         point_size = 2.5,
         save_param = list(save_name = "4_cluster_with_integration"))
![4_cluster_with_integration](https://github.com/user-attachments/assets/59fe7a5d-1eb8-4d32-8d6f-b5baee50bdc7)

When I ran the following code:
plotUMAP(gobject = giotto_SC,
         dim_reduction_name = 'umap_harmony',
         cell_color = 'leiden_harmony',
         group_by = 'list_ID',
         show_NN_network = F,
         point_size =2,
         save_param = list(save_name = "4_b_cluster_with_integration"))
![4_b_cluster_with_integration](https://github.com/user-attachments/assets/5fbbeed7-cef4-4354-af77-ade19e8e068f)

My question is that the picture "4_cluster_with _integration" is good for me, but the picture "4_b_cluster_with _integration" looks distorted since the single picture's width becomes narrow. I want to get the result in which each single picture's width and height are same to the integrated picture. Do you have any suggestions to help me achieve it?

Thanks a lot!
Xu

**Comment by jiajic** [comment]
Hi @xhNorthwestern 

You can try adding this to your save param for a one-off image
```r
save_param = list(
    base_width = 18
)
```
(or readjust both base_width and base_height, since this is a pretty large image)



If you want to set defaults more broadly...
The default values for width and height in save outputs can be found in the giotto instructions
```r
instructions(giotto_SC) # to show
instructions(giotto_SC, "width") <- 18 # to apply a new default
```
best,
George

**Comment by xhNorthwestern** [comment]
Hi @jiajic 

It works for me. Thanks a lot for your suggestions.

Best wishes,
Xu
