### ISSUE TITLE
How do I combine multiple samples in giotto?

### ISSUE THREAD

**Issue by smk5g5** [giotto-suite/Giotto#110]
Is there a way to combine multiple samples in giotto? I was looking at the manual and could not find anything regarding that I was wondering if it is possible to do this in giotto? if not is there a workaround for the same?

Thank you!

**Comment by RubD** [comment]
Hi @smk5g5 sorry for the late reply. This is not possible in the current master branch of Giotto, however you can do this (and much more) if you use the **suite** branch. The branch is fully functional, but we're still making changes and improvements and there might be some more bugs. We're happy to help if you run into any issues.

You can simply install the suite branch with the command `devtools::install_github("RubD/Giotto@suite")`.  I'm also attaching an example script (.txt format for github reasons) for the prostate normal & cancer FFPE visium dataset. In this example I'm showing you how to join giotto objects and also how to perform data integration (using Harmony) if that would be of interest.
Best,
Ruben

[Visium_FFPE_prostate_normal_cancer.txt](https://github.com/RubD/Giotto/files/6856267/Visium_FFPE_prostate_normal_cancer.txt)

**Comment by pcantalupo** [comment]
The link is broken.  Can you provide an updated link? Thank you

**Comment by josschavezf** [comment]
@pcantalupo here is the updated link https://drieslab.github.io/Giotto_website/articles/visium_prostate_integration.html
