### ISSUE TITLE
Is there a better way to align cellranger images to giotto using updateGiottoImage?

### ISSUE THREAD

**Issue by smk5g5** [giotto-suite/Giotto#113]
Hi I am trying to use giotto on cellranger output and the first step in using giotto on cellranger is aligning the cellranger images in giotto using a combination of updateGiottoImage and spatPlot in iteration. I was wondering if there is an automated solution to this than to painstakingly keep changing the coordinates in the code below until we get the best overlap?

`B186_1 <- updateGiottoImage(B186_1, image_name = 'image', ymin_adj = 1500, ymax_adj = 2000, xmax_adj = 2550, xmin_adj = 2000) `

`spatPlot(gobject = B186_1, cell_color = 'in_tissue', show_image = T, point_alpha = 0.7, save_param = list(save_name = 'spatplot_image4')) `

**Comment by RubD** [comment]
We have updated it and it should do this automatically now. The manual method is still there to keep that option open. If you have visium data you can simply use `createGiottoVisiumObject()`

**Comment by smk5g5** [comment]
Is this a recent update because I was already using it like this :

`B186_1 <- createGiottoVisiumObject(visium_dir = data_path, expr_data = 'filter', png_name = "tissue_lowres_image.png", gene_column_index = 2, instructions = instrs) # this will read in your spatial object with gene names not symbols, filtered outs, and attach the image to your giotto object`

and then aligning the image to giotto

`spatPlot(gobject = B186_1, cell_color = 'in_tissue', show_image = T, point_alpha = 0.7, save_param = list(save_name = 'unfiltered_spatplot_image')) `

`B186_1 <- updateGiottoImage(B186_1, image_name = 'image', ymin_adj = 1500, ymax_adj = 2000, xmax_adj = 2550, xmin_adj = 2000)`

`spatPlot(gobject = B186_1, cell_color = 'in_tissue', show_image = T, point_alpha = 0.7, save_param = list(save_name = 'spatplot_image4')) `


Do I need to change the way I am using `createGiottoVisiumObject`?

This was using `remotes::install_github("RubD/Giotto")` and not the `devtools::install_github("RubD/Giotto@suite")` as you had previously mentioned btw.

**Comment by RubD** [comment]
It could be that this is only available through the suite branch. The suite branch is also backwards compatible for about 95%, so you could potentially try to use the suite branch instead. It is a little bit more verbose, because we're still working on finalizing this new version.

**Comment by smk5g5** [comment]
I updated to giotto suite and ran this command.

B185_1 <- createGiottoVisiumObject(
  visium_dir='TWBK-B185-01/outs/',
  expr_data="filter",
  h5_tissue_positions_path = 'TWBK-B185-01/outs/spatial/tissue_positions_list.csv',
  h5_image_png_path='TWBK-B185-01/outs/spatial/tissue_lowres_image.png',
  png_name = "tissue_lowres_image.png",
  gene_column_index = 2, instructions = instrs,
  verbose=T)

and this is what I get after running it 
![unfiltered_spatplot_image](https://user-images.githubusercontent.com/6811915/127034509-568f4316-847d-45fb-bdf2-6a663f88fcc1.png)

I am wondering if this is aligned or do I need to do something else?

I tried rerunning updateGiottoImage with default parameters 

B185_1_2 <- updateGiottoImage(B185_1, image_name = 'image') # example settings for what worked for B172-02
spatPlot(gobject = B185_1_2, cell_color = 'in_tissue', show_image = T, point_alpha = 0.7, save_param = list(save_name = 'spatplot_image2')) 

and this is how the image looks now

![spatplot_image2](https://user-images.githubusercontent.com/6811915/127034651-a54b3ccf-6058-4e0a-a4ef-a18572023197.png)

I was wondering if the image I get after running `createGiottoVisiumObject` is already aligned since its missing the surrounding grid present in the second image I get after running `updateGiottoImage`.

**Comment by RubD** [comment]
The image is indeed already aligned and you don't have to do anything else. 
If you want to see a larger size of the image you can always return the ggplot object and manually add the x and/or y limits by adding another ggplot layer.

For example, this should work:

`plot = spatPlot2D(B185_1, show_image = TRUE, return_plot = TRUE)`

`large_plot = plot + ggplot2::coord_cartesian(xlim = c(0, 20000), ylim = c(-20000, 0))`
