### ISSUE TITLE
Error with runSpatialDeconv for giotto suite

### ISSUE THREAD

**Issue by smk5g5** [giotto-suite/Giotto#115]
Hi,

I am trying to run this code

`giotto_obj <- runSpatialDeconv(gobject = giotto_obj, deconv_method = "DWLS", expression_values = "normalized", logbase = 2, cluster_column = "leiden_clus", sign_matrix = sign_matrix, n_cell = 10, cutoff = 2, name = "DWLS_1")` 

 and getting this error

```Use 'get_expression_values' instead.
See help("Deprecated")
NULL
No spatial locations have been selected, the first one - raw - will be used
No spatial locations have been selected, the first one - raw - will be used
Error in quadprog::solve.QP(D, d, A, bzero) :
  constraints are inconsistent, no solution!
Calls: runSpatialDeconv ... optimize_deconvolute_dwls -> solve_OLS_internal -> <Anonymous>
In addition: Warning message:
'select_expression_values' is deprecated.
Use 'get_expression_values' instead.
See help("Deprecated")
Execution halted```

Any particular reason for this problem?

Best regards!

**Comment by ndelrossi7** [comment]
Hi @smk5g5, it's a bit hard for me to know exactly what is going on without some more information. It seems like it might have to do with the signature matrix you have inputted (I found this online: https://stackoverflow.com/questions/39129253/error-in-solve-qp). We'll be putting up a step by step example soon to help users.
