### ISSUE TITLE
Missing functions from auxiliary_giotto.R

### ISSUE THREAD

**Issue by avrobullet** [giotto-suite/Giotto#118]
Hi! Working from the suite branch on a Docker container. I noticed that certain functions previously in auxiliary_giotto.R such as `rowMeans_giotto()` are no longer present. In the current auxiliary_giotto.R file `rowMeans_giotto(temp)` is called but the function itself does not exist. It was previously available in NAMESPACE prior to the suite branch getting an update 7 days ago.

**Comment by drieslab** [comment]
All these `*_giotto()` were removed at some point, but it seems like one of our merges brought them back. They are all replaced with `*_flex()` functions that can be found in the utilities.R file. I've updated auxiliary.R and will also start doing that for all other files.

**Comment by avrobullet** [comment]
Perfect, thanks!
