### ISSUE TITLE
Error in svd(x, nu = 0L, nv = 0L) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by jungsoo0809** [giotto-suite/Giotto#119]
Hello, I'm trying to reveal reference cell type's spatial pattern on Visium samples following giotto's procedure like below.

[WIth 7 Visium samples] 
createGiottoVisiumObject -> normalizeGiotto -> calculateHVG -> runPCA -> createNearestNetwork -> doLeidenCluster

signature_matrix <- makeSignMatrixPAGE(sign_names = levels(factor(reference_data$Major_compartment)), sign_list = reference_data_marker_lists)

my_giotto_object <- runSpatialDeconv(gobject = giotto, sign_matrix = signature_matrix)

But, I'm facing the error like on the title so I wonder what's the problem of it. Sorry for the naive question.

Thank you!

**Comment by ndelrossi7** [comment]
Hi @jungsoo0809! `runSpatialDeconv()` requires a different kind of signature matrix. You can use the function `makeSignMatrixDWLS()` (recently updated on the suite branch). We are in the process of creating a tutorial for using DWLS deconvolution with Giotto which will be out soon! For more information on DWLS deconvolution in Giotto and what the expected input and output are, please check out [this paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02362-7).

**Comment by ndelrossi7** [comment]
Hi @jungsoo0809, just wanted to touch base to see if the issue was resolved! I have created some more in depth explanation of the different functions to create a DWLS signature matrix if that would be helpful.
