### ISSUE TITLE
Unable to generate metagenes following the guide on the giotto website. 

### ISSUE THREAD

**Issue by smk5g5** [giotto-suite/Giotto#120]
Hi,

I am trying to generate the metagenes and the spatial plots using the information here https://rubd.github.io/Giotto_site/articles/tut10_giotto_spatcoexpression.html but when ever I come at the createMetagenes step I get the following error :-

`B185_1 = createMetagenes(B185_1,expression_values = c("scaled"),gene_clusters = cluster_genes, name = 'cluster_metagene',return_gobject=T)`

`Error in select_expression_values(gobject = gobject, values = values) :
  no slot of name "norm_scaled_expr" for this object of class "giotto"`

I only have three slots in my `B185_1@expression$rna` object namely 
`[1] "raw"        "normalized" "scaled"`

I was wondering if there is any step that needs to be run before the metagene generation steps on https://rubd.github.io/Giotto_site/articles/tut10_giotto_spatcoexpression.html  for generating `norm_scaled_expr` slot.

Thanks!

**Comment by RubD** [comment]
Hi,

It seems like you're using the Giotto suite branch. I've just added a first example [here](http://giottosuite.com/articles/mouse_visium_kidney_210830.html ), which has an example for creating metagenes. Hope this helps.
