### ISSUE TITLE
Error in function plotPCA()

### ISSUE THREAD

**Issue by Huimin721** [giotto-suite/Giotto#124]
Hi,

Whenever I try plotPCA, 
data(mini_giotto_single_cell)
plotPCA(mini_giotto_single_cell)
it turns:
plotPCA(mini_giotto_single_cell)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘plotPCA’ for signature ‘"giotto"’
For more context, I am running R version 4.1.0 and Giotto version 1.0.4.

Thank you!

**Comment by ndelrossi7** [comment]
Hi @Huimin721! Can you tell me a bit more about the code you ran prior to running `plotPCA()`? In addition, what other packages have you loaded for this R session?
The function works for me and I am unable to replicate the error but may be able to help with some more information. Thanks!

**Comment by Huimin721** [comment]
> Hi @Huimin721! Can you tell me a bit more about the code you ran prior to running `plotPCA()`? In addition, what other packages have you loaded for this R session?
> The function works for me and I am unable to replicate the error but may be able to help with some more information. Thanks!

Hi Natalie,

Yes. Thank you. I just use the code in the mini seqFISH page. To check what packages I have loaded, I restart Rstudio and it shows no error this time. I guess to install Giotto and setup the environment, I loaded some unnecessary packages yesterday. Thanks!

**Comment by ndelrossi7** [comment]
Great, let us know if you have any questions in the future! :)
