### ISSUE TITLE
Something wrong with addHMRF

### ISSUE THREAD

**Issue by BinDuan** [giotto-suite/Giotto#132]
I followed the tutorial "http://spatialgiotto.rc.fas.harvard.edu/giotto.visium.brain.html".

However, when I ran addHMRF, I got the warnings"FileNotFoundError: [Errno 2] No such file or directory: '11_HMRF/Spatial_genes/SG_topgenes_k20_scaled/result.spatial.zscore/k_20/ftest.beta.10.0.prob.txt'". I checked this file and there is indeed no this file. 

I don't know why, can you give me some suggestions?
Thanks

**Comment by gcyuan** [comment]
Hi

Sorry about the confusion, but the instruction at spatialgiotto.rc.harvard.edu is outdated. We are reconstructing our website, in the meantime, please refer to the website: github.com/RubD/Giotto_site for the up to date instructions. Please let us know if you continue to have any problem.

Best
Guo-Cheng

**Comment by bernard2012** [comment]
Are you trying to access a beta that you did not perform HMRF on? This may explain for lack of the file. Posting the full code might help to debug. Also try the Giotto docker image to see if the issue happens there. The Docker image gets rid of all environment related issues, so as to allow us focus on debugging the code.
