### ISSUE TITLE
runSpatialDeconv takes forever

### ISSUE THREAD

**Issue by linhuawang** [giotto-suite/Giotto#166]
Hi, 

I am trying to run spatialDWLS with my data (10, 000 spots, 8000 marker genes) using the following command:
```
mixture_giotto.A <- runSpatialDeconv(mixture_giotto, deconv_method = c("DWLS"),
                                     expression_values = c("normalized"),logbase = 2,
                                     cluster_column = "leiden_clus", sig_matrix.A,
                                     n_cell = 10, cutoff = 2, return_gobject = TRUE)
```
I used makeSignMatrixDWLSfromMatrix to make the signature matrix, followed the workflow to do QC, processing, normalization, PCA, UMAP, NearestNeighbor, and leidenClustering. 

My code has been running for over 12 hours without any reported issue on a 4-core 16-GB memory macOS. What is the expected elapsed time for tasks like mine? Any suggestions?

Thank you so much!

Best,
Linhua

**Comment by gcyuan** [comment]
Hi, 

Thanks for using Giotto.

It is possible the dataset is too large. Could you try to reduce the size to about 1000 spots and run the program again? 

Best
Guocheng

**Comment by linhuawang** [comment]
Yes, it seems to be a running time issue. Thank you so much!
