### ISSUE TITLE
runGiottoHarmony error: object 'reduction' not found

### ISSUE THREAD

**Issue by lijiacd985** [giotto-suite/Giotto#169]
Hi there,

When I use runGiottoHarmony based on http://giottosuite.com/articles/Visium_prostate_integration_Sep30_21.html, there is an error:

comb = runGiottoHarmony(comb, vars_use = 'list_ID', do_pca = F)
using 'Harmony' to integrate different datasets. If used in published research, please cite: 

  Korsunsky, I., Millard, N., Fan, J. et al.
                      Fast, sensitive and accurate integration of single-cell data with Harmony.
                      Nat Methods 16, 1289–1296 (2019).
                      https://doi.org/10.1038/s41592-019-0619-0 
Harmony 1/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 2/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony converged after 2 iterations
Error in set_dimReduction(gobject = gobject, feat_type = feat_type, spat_unit = spat_unit,  : 
  object 'reduction' not found

I checked the object ,there is reduction in pca and umap as following:

Thanks,

Best,

Jia 
>comb
An object of class giotto 
features =  rna 
 features across samples.
 
Steps and parameters used: 
 
$`0_subset`
            gobject           spat_unit           feat_type 
          "gobject"         "spat_unit"         "feat_type" 
           cell_ids            feat_ids           poly_info 
"selected_cell_ids" "selected_feat_ids"         "poly_info" 
            verbose     toplevel_params       cells removed 
          "verbose"                 "2"              "3935" 
      feats removed 
             "9673" 

$`1_filter`
               gobject      expression_values   expression_threshold 
                "comb"                  "raw"                    "1" 
 feat_det_in_min_cells min_det_feats_per_cell              poly_info 
                  "50"                  "500"                 "cell" 
               verbose 
                   "T" 

$`2_normalize`
          gobject expression_values      norm_methods library_size_norm 
           "comb"             "raw"        "standard"            "TRUE" 
      scalefactor          log_norm        log_offset           logbase 
           "6000"            "TRUE"               "1"               "2" 
      scale_feats       scale_cells       scale_order             theta 
           "TRUE"            "TRUE"     "first_feats"             "100" 
      update_slot           verbose 
         "scaled"            "TRUE" 

$`3_feat_stats`
            gobject   expression_values detection_threshold 
             "comb"               "raw"                 "0" 
     return_gobject 
             "TRUE" 

$`4_cell_stats`
            gobject   expression_values detection_threshold 
             "comb"               "raw"                 "0" 
     return_gobject 
             "TRUE" 

$`5_hvf`
             gobject    expression_values               method 
              "comb"         "normalized"         "cov_groups" 
   reverse_log_scale              logbase expression_threshold 
             "FALSE"                  "2"                  "0" 
nr_expression_groups     zscore_threshold              HVFname 
                "20"                "1.5"                "hvf" 
   difference_in_cov        var_threshold            show_plot 
               "0.1"                "1.5"                 "NA" 
         return_plot            save_plot           save_param 
                "NA"                 "NA"             "list()" 
   default_save_name       return_gobject 
           "HVFplot"               "TRUE" 

$`6_pca`
          gobject expression_values         reduction      feats_to_use 
           "comb"      "normalized"           "cells"             "hvf" 
   return_gobject            center        scale_unit               ncp 
           "TRUE"            "TRUE"            "TRUE"             "100" 
           method     method_params               rev          set_seed 
          "irlba"        "list(NA)"           "FALSE"            "TRUE" 
      seed_number           verbose               ... 
           "1234"            "TRUE"                "" 

$`7_nn_network`
             gobject                 type dim_reduction_to_use 
              "comb"                "sNN"                "pca" 
  dim_reduction_name    dimensions_to_use    expression_values 
               "pca"               "1:10"         "normalized" 
                name       return_gobject                    k 
           "sNN.pca"               "TRUE"                 "15" 
      minimum_shared           top_shared              verbose 
                 "5"                  "3"                  "T" 
                 ... 
                  "" 

$`8_cluster`
                         gobject                             name 
                          "comb"                    "leiden_clus" 
               nn_network_to_use                     network_name 
                           "sNN"                        "sNN.pca" 
                      resolution                       weight_col 
                           "0.2"                         "weight" 
                  partition_type                     n_iterations 
"RBConfigurationVertexPartition"                           "1000" 
                  return_gobject                         set_seed 
                          "TRUE"                              "T" 
                     seed_number 
                          "1234" 

$`9_umap`
             gobject    expression_values            reduction 
              "comb"         "normalized"              "cells" 
dim_reduction_to_use    dimensions_to_use       return_gobject 
               "pca"               "1:10"               "TRUE" 
         n_neighbors         n_components             n_epochs 
                "40"                  "2"                "400" 
            min_dist            n_threads               spread 
              "0.01"                 "NA"                  "5" 
            set_seed          seed_number              verbose 
              "TRUE"               "1234"                  "T" 
     toplevel_params                  ... 
                 "2"                   "" 

$`10_umap`
             gobject    expression_values            reduction 
              "comb"         "normalized"              "cells" 
dim_reduction_to_use    dimensions_to_use       return_gobject 
               "pca"               "1:10"               "TRUE" 
         n_neighbors         n_components             n_epochs 
                "40"                  "2"                "400" 
            min_dist            n_threads               spread 
              "0.01"                 "NA"                  "5" 
            set_seed          seed_number              verbose 
              "TRUE"               "1234"                  "T" 
     toplevel_params                  ... 
                 "2"                   "" 

> sessionInfo("Giotto")
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
character(0)

other attached packages:
[1] Giotto_2.0.0.991

loaded via a namespace (and not attached):
  [1] Seurat_4.0.5          Rtsne_0.15            colorspace_2.0-2     
  [4] deldir_0.2-10         ellipsis_0.3.2        ggridges_0.5.3       
  [7] rprojroot_2.0.2       rstudioapi_0.13       spatstat.data_2.1-0  
 [10] farver_2.1.0          leiden_0.3.9          listenv_0.8.0        
 [13] stats_4.0.3           remotes_2.4.0         ggrepel_0.9.1        
 [16] RSpectra_0.16-0       fansi_0.5.0           R.methodsS3_1.8.1    
 [19] codetools_0.2-18      splines_4.0.3         polyclip_1.10-0      
 [22] jsonlite_1.7.2        ica_1.0-2             base_4.0.3           
 [25] cluster_2.1.2         R.oo_1.24.0           png_0.1-7            
 [28] uwot_0.1.10           shiny_1.6.0           sctransform_0.3.2    
 [31] spatstat.sparse_2.0-0 compiler_4.0.3        httr_1.4.2           
 [34] assertthat_0.2.1      SeuratObject_4.0.2    Matrix_1.3-4         
 [37] fastmap_1.1.0         lazyeval_0.2.2        cli_3.0.1            
 [40] BiocSingular_1.6.0    later_1.3.0           htmltools_0.5.1.1    
 [43] prettyunits_1.1.1     tools_4.0.3           rsvd_1.0.5           
 [46] igraph_1.2.6          gtable_0.3.0          glue_1.4.2           
 [49] RANN_2.6.1            reshape2_1.4.4        dplyr_1.0.7          
 [52] grDevices_4.0.3       Rcpp_1.0.7            scattermore_0.7      
 [55] vctrs_0.3.8           nlme_3.1-152          lmtest_0.9-38        
 [58] stringr_1.4.0         globals_0.14.0        ps_1.6.0             
 [61] beachmat_2.6.4        mime_0.11             miniUI_0.1.1.1       
 [64] lifecycle_1.0.0       irlba_2.3.3           goftest_1.2-2        
 [67] future_1.21.0         MASS_7.3-54           zoo_1.8-9            
 [70] scales_1.1.1          spatstat.core_2.3-0   MatrixGenerics_1.2.1 
 [73] graphics_4.0.3        promises_1.2.0.1      spatstat.utils_2.2-0 
 [76] parallel_4.0.3        RColorBrewer_1.1-2    utils_4.0.3          
 [79] curl_4.3.2            reticulate_1.20       pbapply_1.4-3        
 [82] gridExtra_2.3         ggplot2_3.3.5         datasets_4.0.3       
 [85] rpart_4.1-15          stringi_1.7.3         S4Vectors_0.28.1     
 [88] harmony_0.1.0         BiocGenerics_0.36.1   BiocParallel_1.24.1  
 [91] pkgbuild_1.2.0        rlang_0.4.11          pkgconfig_2.0.3      
 [94] matrixStats_0.60.0    lattice_0.20-44       ROCR_1.0-11          
 [97] purrr_0.3.4           tensor_1.5            labeling_0.4.2       
[100] patchwork_1.1.1       htmlwidgets_1.5.3     cowplot_1.1.1        
[103] processx_3.5.2        tidyselect_1.1.1      parallelly_1.27.0    
[106] RcppAnnoy_0.0.19      plyr_1.8.6            magrittr_2.0.1       
[109] R6_2.5.1              IRanges_2.24.1        magick_2.7.3         
[112] generics_0.1.0        DelayedArray_0.16.3   DBI_1.1.1            
[115] mgcv_1.8-36           pillar_1.6.2          withr_2.4.2          
[118] fitdistrplus_1.1-5    survival_3.2-12       abind_1.4-5          
[121] tibble_3.1.3          future.apply_1.8.1    crayon_1.4.1         
[124] KernSmooth_2.23-20    utf8_1.2.2            spatstat.geom_2.2-2  
[127] plotly_4.9.4.1        grid_4.0.3            data.table_1.14.0    
[130] callr_3.7.0           methods_4.0.3         digest_0.6.27        
[133] xtable_1.8-4          dbscan_1.1-8          tidyr_1.1.3          
[136] httpuv_1.6.2          R.utils_2.10.1        stats4_4.0.3         
[139] munsell_0.5.0         viridisLite_0.4.0

**Comment by RubD** [comment]
@JunxiangXu can you take a look? I believe you created and wrote this example. Thanks

**Comment by JunxiangXu** [comment]
Hello, Sorry for the late reply.
I tried to run the same commands on the latest Giotto Suite package and I cannot reproduce the same error as you provided. Could you please provide a little bit more information here or try again the latest Giotto suite?
Could you also check the installed package version of Harmony?

**Comment by joe-jhou2** [comment]
I gotta the same error here
> testcombo = runGiottoHarmony(testcombo, vars_use = 'list_ID', do_pca = F)
using 'Harmony' to integrate different datasets. If used in published research, please cite: 

  Korsunsky, I., Millard, N., Fan, J. et al.
                      Fast, sensitive and accurate integration of single-cell data with Harmony.
                      Nat Methods 16, 1289–1296 (2019).
                      https://doi.org/10.1038/s41592-019-0619-0 
Harmony 1/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 2/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 3/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 4/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 5/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 6/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony 7/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Harmony converged after 7 iterations
Error in set_dimReduction(gobject = gobject, feat_type = feat_type, spat_unit = spat_unit,  : 
  object 'reduction' not found

> session_info()
─ Session info ────────────────────────────────────────────────────────
 setting  value
 version  R version 4.0.3 (2020-10-10)
 os       macOS Big Sur 10.16
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2022-02-22
 rstudio  1.3.1093 Apricot Nasturtium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────
 package        * version   date (UTC) lib source
 beachmat         2.6.4     2020-12-20 [1] Bioconductor
 BiocGenerics     0.36.1    2021-04-16 [1] Bioconductor
 BiocParallel     1.24.1    2020-11-06 [1] Bioconductor
 BiocSingular     1.6.0     2020-10-27 [1] Bioconductor
 bit              4.0.4     2020-08-04 [1] CRAN (R 4.0.2)
 bit64            4.0.5     2020-08-30 [1] CRAN (R 4.0.2)
 brio             1.1.3     2021-11-30 [1] CRAN (R 4.0.2)
 cachem           1.0.6     2021-08-19 [1] CRAN (R 4.0.2)
 callr            3.7.0     2021-04-20 [1] CRAN (R 4.0.2)
 cli              3.2.0     2022-02-14 [1] CRAN (R 4.0.3)
 codetools        0.2-18    2020-11-04 [1] CRAN (R 4.0.2)
 colorspace       2.0-2     2021-06-24 [1] CRAN (R 4.0.2)
 cowplot          1.1.1     2020-12-30 [1] CRAN (R 4.0.2)
 crayon           1.5.0     2022-02-14 [1] CRAN (R 4.0.3)
 curl             4.3.2     2021-06-23 [1] CRAN (R 4.0.2)
 data.table       1.14.2    2021-09-27 [1] CRAN (R 4.0.2)
 dbscan           1.1-10    2022-01-15 [1] CRAN (R 4.0.5)
 DelayedArray     0.16.3    2021-03-24 [1] Bioconductor
 desc             1.4.0     2021-09-28 [1] CRAN (R 4.0.2)
 devtools       * 2.4.3     2021-11-30 [1] CRAN (R 4.0.2)
 digest           0.6.29    2021-12-01 [1] CRAN (R 4.0.2)
 dplyr            1.0.8     2022-02-08 [1] CRAN (R 4.0.5)
 ellipsis         0.3.2     2021-04-29 [1] CRAN (R 4.0.2)
 fansi            1.0.2     2022-01-14 [1] CRAN (R 4.0.5)
 farver           2.1.0     2021-02-28 [1] CRAN (R 4.0.2)
 fastmap          1.1.0     2021-01-25 [1] CRAN (R 4.0.2)
 FNN              1.1.3     2019-02-15 [1] CRAN (R 4.0.2)
 fs               1.5.2     2021-12-08 [1] CRAN (R 4.0.2)
 generics         0.1.2     2022-01-31 [1] CRAN (R 4.0.5)
 ggplot2          3.3.5     2021-06-25 [1] CRAN (R 4.0.2)
 ggrepel          0.9.1     2021-01-15 [1] CRAN (R 4.0.2)
 Giotto         * 2.0.0.992 2022-02-18 [1] Github (RubD/Giotto@1b99729)
 glue             1.6.1     2022-01-22 [1] CRAN (R 4.0.5)
 gtable           0.3.0     2019-03-25 [1] CRAN (R 4.0.2)
 harmony        * 0.1.0     2022-02-22 [1] Github (immunogenomics/harmony@c93de54)
 hdf5r            1.3.5     2021-11-15 [1] CRAN (R 4.0.2)
 here             1.0.1     2020-12-13 [1] CRAN (R 4.0.2)
 htmltools        0.5.2     2021-08-25 [1] CRAN (R 4.0.2)
 httpuv           1.6.5     2022-01-05 [1] CRAN (R 4.0.5)
 igraph           1.2.11    2022-01-04 [1] CRAN (R 4.0.5)
 IRanges          2.24.1    2020-12-12 [1] Bioconductor
 irlba            2.3.5     2021-12-06 [1] CRAN (R 4.0.2)
 jsonlite         1.7.3     2022-01-17 [1] CRAN (R 4.0.5)
 labeling         0.4.2     2020-10-20 [1] CRAN (R 4.0.2)
 later            1.3.0     2021-08-18 [1] CRAN (R 4.0.2)
 lattice          0.20-45   2021-09-22 [1] CRAN (R 4.0.2)
 lifecycle        1.0.1     2021-09-24 [1] CRAN (R 4.0.2)
 magick           2.7.3     2021-08-18 [1] CRAN (R 4.0.2)
 magrittr         2.0.2     2022-01-26 [1] CRAN (R 4.0.5)
 Matrix           1.4-0     2021-12-08 [1] CRAN (R 4.0.2)
 MatrixGenerics   1.2.1     2021-01-30 [1] Bioconductor
 matrixStats      0.61.0    2021-09-17 [1] CRAN (R 4.0.2)
 memoise          2.0.1     2021-11-26 [1] CRAN (R 4.0.2)
 mime             0.12      2021-09-28 [1] CRAN (R 4.0.2)
 munsell          0.5.0     2018-06-12 [1] CRAN (R 4.0.2)
 pillar           1.7.0     2022-02-01 [1] CRAN (R 4.0.5)
 pkgbuild         1.3.1     2021-12-20 [1] CRAN (R 4.0.2)
 pkgconfig        2.0.3     2019-09-22 [1] CRAN (R 4.0.2)
 pkgload          1.2.4     2021-11-30 [1] CRAN (R 4.0.2)
 png              0.1-7     2013-12-03 [1] CRAN (R 4.0.2)
 prettyunits      1.1.1     2020-01-24 [1] CRAN (R 4.0.2)
 processx         3.5.2     2021-04-30 [1] CRAN (R 4.0.2)
 promises         1.2.0.1   2021-02-11 [1] CRAN (R 4.0.2)
 ps               1.6.0     2021-02-28 [1] CRAN (R 4.0.2)
 purrr            0.3.4     2020-04-17 [1] CRAN (R 4.0.2)
 R6               2.5.1     2021-08-19 [1] CRAN (R 4.0.2)
 RColorBrewer     1.1-2     2014-12-07 [1] CRAN (R 4.0.2)
 Rcpp           * 1.0.8     2022-01-13 [1] CRAN (R 4.0.5)
 remotes          2.4.2     2021-11-30 [1] CRAN (R 4.0.2)
 reticulate       1.24      2022-01-26 [1] CRAN (R 4.0.5)
 rlang            1.0.1     2022-02-03 [1] CRAN (R 4.0.5)
 rprojroot        2.0.2     2020-11-15 [1] CRAN (R 4.0.2)
 RSpectra         0.16-0    2019-12-01 [1] CRAN (R 4.0.2)
 rstudioapi       0.13      2020-11-12 [1] CRAN (R 4.0.2)
 rsvd             1.0.5     2021-04-16 [1] CRAN (R 4.0.2)
 S4Vectors        0.28.1    2020-12-09 [1] Bioconductor
 scales           1.1.1     2020-05-11 [1] CRAN (R 4.0.2)
 sessioninfo      1.2.2     2021-12-06 [1] CRAN (R 4.0.2)
 shiny            1.7.1     2021-10-02 [1] CRAN (R 4.0.2)
 testthat         3.1.2     2022-01-20 [1] CRAN (R 4.0.5)
 tibble           3.1.6     2021-11-07 [1] CRAN (R 4.0.2)
 tidyr            1.2.0     2022-02-01 [1] CRAN (R 4.0.5)
 tidyselect       1.1.1     2021-04-30 [1] CRAN (R 4.0.2)
 tinytex          0.36      2021-12-19 [1] CRAN (R 4.0.2)
 usethis        * 2.1.5     2021-12-09 [1] CRAN (R 4.0.2)
 utf8             1.2.2     2021-07-24 [1] CRAN (R 4.0.2)
 uwot             0.1.11    2021-12-02 [1] CRAN (R 4.0.2)
 vctrs            0.3.8     2021-04-29 [1] CRAN (R 4.0.2)
 withr            2.4.3     2021-11-30 [1] CRAN (R 4.0.2)
 xfun             0.29      2021-12-14 [1] CRAN (R 4.0.2)
 xtable           1.8-4     2019-04-21 [1] CRAN (R 4.0.2)

 [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

─ Python configuration ────────────────────────────────────────────────────────
 python:         /Users/jhou2/Library/r-miniconda/envs/giotto_env/bin/pythonw
 libpython:      /Users/jhou2/Library/r-miniconda/envs/giotto_env/lib/libpython3.6m.dylib
 pythonhome:     /Users/jhou2/Library/r-miniconda/envs/giotto_env:/Users/jhou2/Library/r-miniconda/envs/giotto_env
 version:        3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:16)  [GCC Clang 11.0.1]
 numpy:          /Users/jhou2/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages/numpy
 numpy_version:  1.19.5
 pandas:         /Users/jhou2/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages/pandas
 
 NOTE: Python version was forced by use_python function

**Comment by joe-jhou2** [comment]
It seems object "reduction" is required for this step, is that possible the "reduction" refer to the object testcombo@dimension_reduction? Could you please address this issue? THanks.

**Comment by RubD** [comment]
I've pushed a fix to the Giotto Suite branch. With a recent update the reduction parameter was not defined anymore. I believe it should work now, but we will also test it on our side.

**Comment by JunxiangXu** [comment]
Could you please try updating to the latest Giotto suite and rerun everything? 
The runGiottoHarmony function should work now.

**Comment by joe-jhou2** [comment]
Just do this remotes::install_github("RubD/Giotto@suite", force = TRUE) to reinstall the package, but it's still 2.0.0.992
did I do it wrong way?

**Comment by joe-jhou2** [comment]
problem fixed! restart R! But, new problem shows: could you please comment? thanks.

> plotUMAP(gobject = testcombo,
+          dim_reduction_name = 'umap_harmony',
+          cell_color = 'leiden_harmony', show_NN_network = T, point_size = 1.5,
+          save_param = list(save_name = "4.2a_plot"))

 nn_network_to_use or network_name does not exist, 

           create a nearest-neighbor network first 
Error in igraph::as_data_frame(selected_nn_network, what = "edges") : 
  Not a graph object

**Comment by JunxiangXu** [comment]
Hi mimisikai, Giotto_2.0.0.992 should be working.
Did you run the createNearestNetwork, doLeidenCluster and runUMAP before you plot this? How's your Giotto object look like? 
You can use this command to see how is Giotto object look like:
str(Giotto_Object, max.level = 3)

You should get something like this if you check your Giotto object information:
> testcombo@nn_network
$cell
$cell$sNN
$cell$sNN$sNN.pca
IGRAPH f8fa66b DNW- 6911 60994 -- 
+ attr: name (v/c), weight (e/n), distance (e/n), shared (e/n), rank
| (e/n)
+ edges from f8fa66b (vertex names):
 [1] NP-AAACAAGTATCTCCCA-1->NP-AGTGAACAAACTTCTC-1
 [2] NP-AAACAAGTATCTCCCA-1->NP-CGCTGGTGACTACCCT-1
 [3] NP-AAACAAGTATCTCCCA-1->NP-CAGCAGTCCAGACTAT-1
 [4] NP-AAACAAGTATCTCCCA-1->NP-ACAATTTGGCCATATT-1
 [5] NP-AAACAAGTATCTCCCA-1->NP-GGTTTAGCCTTTCTTG-1
 [6] NP-AAACAAGTATCTCCCA-1->NP-TGAATGTCAGCCGGCC-1
 [7] NP-AAACAATCTACTAGCA-1->NP-TACCAGCTAGGTTTAA-1
+ ... omitted several edges

$cell$sNN$NN.harmony
IGRAPH 4851567 DNW- 6911 55750 -- 
+ attr: name (v/c), weight (e/n), distance (e/n), shared (e/n), rank
| (e/n)
+ edges from 4851567 (vertex names):
 [1] NP-AAACAAGTATCTCCCA-1->NP-AGTGAACAAACTTCTC-1
 [2] NP-AAACAAGTATCTCCCA-1->NP-CGCTGGTGACTACCCT-1
 [3] NP-AAACAAGTATCTCCCA-1->NP-TTGACAGGAGCTCCCG-1
 [4] NP-AAACAAGTATCTCCCA-1->NP-CAGCAGTCCAGACTAT-1
 [5] NP-AAACAAGTATCTCCCA-1->NP-CGGCTCTAAAGCTGCA-1
 [6] NP-AAACAAGTATCTCCCA-1->NP-GCGCCTCCCACTCCGA-1
 [7] NP-AAACAATCTACTAGCA-1->CP-CAGAACTTAGCCCTCT-1
+ ... omitted several edges

**Comment by joe-jhou2** [comment]
This what I have
>str(testcombo, max.level = 3)
Formal class 'giotto' [package "Giotto"] with 21 slots
  ..@ expression         :List of 1
  .. ..$ cell:List of 1
  ..@ expression_feat    : chr "rna"
  ..@ spatial_locs       :List of 1
  .. ..$ cell:List of 1
  ..@ spatial_info       : NULL
  ..@ cell_metadata      :List of 1
  .. ..$ cell:List of 1
  ..@ feat_metadata      :List of 1
  .. ..$ cell:List of 1
  ..@ feat_info          : NULL
  ..@ cell_ID            :List of 1
  .. ..$ cell: chr [1:2137] "A1-AAACGAGACGGTTGAT-1" "A1-AAATAGCTTAGACTTT-1" "A1-AAATTAACGGGTAGCT-1" "A1-AAATTACCTATCGATG-1" ...
  ..@ feat_ID            :List of 1
  .. ..$ rna: chr [1:14580] "A1BG" "A1BG-AS1" "A2M" "A2M-AS1" ...
  ..@ spatial_network    : NULL
  ..@ spatial_grid       : NULL
  ..@ spatial_enrichment : NULL
  ..@ dimension_reduction:List of 1
  .. ..$ cells:List of 1
  ..@ nn_network         :List of 1
  .. ..$ cell:List of 1
  ..@ images             :List of 4
  .. ..$ A1-image:Formal class 'giottoImage' [package "Giotto"] with 7 slots
  .. ..$ B1-image:Formal class 'giottoImage' [package "Giotto"] with 7 slots
  .. ..$ C1-image:Formal class 'giottoImage' [package "Giotto"] with 7 slots
  .. ..$ D1-image:Formal class 'giottoImage' [package "Giotto"] with 7 slots
  ..@ largeImages        : NULL
  ..@ parameters         :List of 13
  .. ..$ 0_subset    : Named chr [1:6] "testcombo" "in_tissue_barcodes" "TRUE" "2" ...
  .. .. ..- attr(*, "names")= chr [1:6] "gobject" "cell_ids" "verbose" "toplevel_params" ...
  .. ..$ 1_subset    : Named chr [1:10] "gobject" "spat_unit" "feat_type" "selected_cell_ids" ...
  .. .. ..- attr(*, "names")= chr [1:10] "gobject" "spat_unit" "feat_type" "cell_ids" ...
  .. ..$ 2_filter    : Named chr [1:7] "testcombo" "raw" "1" "10" ...
  .. .. ..- attr(*, "names")= chr [1:7] "gobject" "expression_values" "expression_threshold" "feat_det_in_min_cells" ...
  .. ..$ 3_normalize : Named chr [1:14] "testcombo" "raw" "standard" "TRUE" ...
  .. .. ..- attr(*, "names")= chr [1:14] "gobject" "expression_values" "norm_methods" "library_size_norm" ...
  .. ..$ 4_feat_stats: Named chr [1:4] "testcombo" "raw" "0" "TRUE"
  .. .. ..- attr(*, "names")= chr [1:4] "gobject" "expression_values" "detection_threshold" "return_gobject"
  .. ..$ 5_cell_stats: Named chr [1:4] "testcombo" "raw" "0" "TRUE"
  .. .. ..- attr(*, "names")= chr [1:4] "gobject" "expression_values" "detection_threshold" "return_gobject"
  .. ..$ 6_hvf       : Named chr [1:17] "testcombo" "normalized" "cov_groups" "FALSE" ...
  .. .. ..- attr(*, "names")= chr [1:17] "gobject" "expression_values" "method" "reverse_log_scale" ...
  .. ..$ 7_pca       : Named chr [1:15] "testcombo" "normalized" "cells" "hvf" ...
  .. .. ..- attr(*, "names")= chr [1:15] "gobject" "expression_values" "reduction" "feats_to_use" ...
  .. ..$ 8_harmony   : Named chr [1:9] "testcombo" "list_ID" "F" "normalized" ...
  .. .. ..- attr(*, "names")= chr [1:9] "gobject" "vars_use" "do_pca" "expression_values" ...
  .. ..$ 9_nn_network: Named chr [1:13] "testcombo" "sNN" "harmony" "harmony" ...
  .. .. ..- attr(*, "names")= chr [1:13] "gobject" "type" "dim_reduction_to_use" "dim_reduction_name" ...
  .. ..$ 10_cluster  : Named chr [1:11] "testcombo" "leiden_harmony" "sNN" "NN.harmony" ...
  .. .. ..- attr(*, "names")= chr [1:11] "gobject" "name" "nn_network_to_use" "network_name" ...
  .. ..$ 11_umap     : Named chr [1:19] "testcombo" "normalized" "cells" "harmony" ...
  .. .. ..- attr(*, "names")= chr [1:19] "gobject" "expression_values" "reduction" "dim_reduction_to_use" ...
  .. ..$ 12_umap     : Named chr [1:19] "testcombo" "normalized" "cells" "harmony" ...
  .. .. ..- attr(*, "names")= chr [1:19] "gobject" "expression_values" "reduction" "dim_reduction_to_use" ...
  ..@ instructions       :List of 11
  .. ..$ python_path: chr "/Users/jhou2/Library/r-miniconda/envs/giotto_env/bin/pythonw"
  .. ..$ show_plot  : logi FALSE
  .. ..$ return_plot: logi TRUE
  .. ..$ save_plot  : logi TRUE
  .. ..$ save_dir   : chr "/Users/jhou2/Documents/Jia10X/GiottoResult"
  .. ..$ plot_format: chr "png"
  .. ..$ dpi        : num 300
  .. ..$ units      : chr "in"
  .. ..$ height     : num 9
  .. ..$ width      : num 9
  .. ..$ is_docker  : logi FALSE
  ..@ offset_file        : NULL
  ..@ OS_platform        : chr "unix"
  ..@ join_info          :List of 7
  .. ..$ list_IDs   : chr [1:4] "A1" "B1" "C1" "D1"
  .. ..$ join_method: chr "shift"
  .. ..$ z_vals     : num 1000
  .. ..$ x_shift    : NULL
  .. ..$ y_shift    : NULL
  .. ..$ x_padding  : num 0
  .. ..$ y_padding  : num 0
> testcombo@nn_network
$cell
$cell$sNN
$cell$sNN$NN.harmony
IGRAPH e74d651 DNW- 2137 19728 -- 
+ attr: name (v/c), weight (e/n), distance (e/n), shared (e/n), rank (e/n)
+ edges from e74d651 (vertex names):
 [1] A1-AAACGAGACGGTTGAT-1->A1-TTGAATATGGACTTTC-1 A1-AAACGAGACGGTTGAT-1->A1-ACCCGGATGACGCATC-1
 [3] A1-AAACGAGACGGTTGAT-1->A1-GGGCCGGCCGAAGTAC-1 A1-AAACGAGACGGTTGAT-1->A1-GTACTGGAGTTAGACC-1
 [5] A1-AAACGAGACGGTTGAT-1->A1-TAGGTTCGAGTTCGTC-1 A1-AAACGAGACGGTTGAT-1->A1-TTACTCCGGCCGGGAA-1
 [7] A1-AAACGAGACGGTTGAT-1->B1-TGCAGAGTACCGAGCA-1 A1-AAACGAGACGGTTGAT-1->A1-TAGGGAGCTTGGGATG-1
 [9] A1-AAACGAGACGGTTGAT-1->B1-ATCCTGCGTGGAATGG-1 A1-AAACGAGACGGTTGAT-1->B1-TACGACGCTTGCTGCG-1
[11] A1-AAACGAGACGGTTGAT-1->C1-ATCAATCTGGGCTGCA-1 A1-AAATAGCTTAGACTTT-1->A1-TAGACTACCTAGCGTT-1
[13] A1-AAATAGCTTAGACTTT-1->B1-TCGTCTTAGGCGTTAA-1 A1-AAATAGCTTAGACTTT-1->B1-ACTCGTCAGTAATCCC-1
[15] A1-AAATAGCTTAGACTTT-1->A1-TCCCGTGTGCAATTTG-1 A1-AAATAGCTTAGACTTT-1->B1-AAGGTGATAAACCAGC-1
+ ... omitted several edges

**Comment by JunxiangXu** [comment]
Hi, sorry for the confusing messages. After looking into that, in order to show NN Network on the Umap plot for Harmony Integration, you will need to:
set show_NN_network = T,
specify nn_network_to_use = 'sNN' and network_name = 'NN.harmony', 
otherwise by default it will try to load network information from the sNN.pca space as in without integration.
