### ISSUE TITLE
Multiple sections and integration

### ISSUE THREAD

**Issue by moutazhelal** [giotto-suite/Giotto#179]
Dear Giotto team,

Thank you for making such as amazing tool.

I am currently working on 10Visium data and I would like to analyze two capture area at once and if possible do an integration on these data would that be possible?

Best,
Moutaz

**Comment by RubD** [comment]
Hi @moutazhelal 

Thanks for the kind words. Which version of Giotto are you currently using? `packageVersion('Giotto')`

In the new and improved Giotto Suite (suite branch) we offer this functionality, see giottosuite.com and more specifically http://giottosuite.com/articles/Visium_prostate_integration_Sep30_21.html 

You can simply install Giotto Suite like `remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("RubD/Giotto@suite")` and almost any previous code you have should still work. I'm also adding @JunxiangXu to the conversation who could help with potential issues.

It's still a work in progress, but it definitely works and has the latest additions and we'll be adding more in the future.

**Comment by moutazhelal** [comment]
Hi @RubD ,

Thank you very much for your help. I was using Giotto Version 1.0 but after installing Giotto Suite  and following the tutorial on giottosuite.com I managed to merge and integrate my data.

Thank you very much,
Best,
Moutaz

**Comment by RubD** [comment]
Ok great, let us know if you run into other problems and keep an eye out for updates in the near future.
