### ISSUE TITLE
Extract Cell-Cell Interaction Information from cellProximityEnrichment()

### ISSUE THREAD

**Issue by evanmaes** [giotto-suite/Giotto#180]
Hi all, 

I am working with a CODEX dataset. I previously annotated the cell-types outside of Giotto. Next, I initialized the Giotto Object. Here I am using a list to hold all of my patient data with 1 patient as each Giotto Object.
```
metadata = pDataDT(my_giotto_object)
giotto.list<-list()
for(i in 1:length(patient_ids)){
  subset_cell_IDs<-metadata[metadata$orig.ident==patient_ids[i],]$cell_ID
  patient = subsetGiotto(my_giotto_object, cell_ids = subset_cell_IDs)
  giotto.list[[i]]<-patient
}
names(giotto.list)<-patient_ids
```

Next, I used the Delaunay method to construct the spatial network/voronoi tessellation. 
```
giotto.list <- lapply(X = giotto.list, FUN = function(x) {
  x <- createSpatialNetwork(gobject = x, 
                            method = "Delaunay", #default
                            delaunay_method = "deldir", #default,
                            minimum_k = 2, #minimum nearest neighbors
                            k=10, #number of nearest neighbors based on physical distance
                            maximum_distance_delaunay = 200) #distance cutoff for nearest neighbors
})
```
Here I use the cellProximityEnrichment() function-- my goal is to calculate the observed frequency of cell-cell proximity interactions.
```
cell_proximities.list<-lapply(X = names(giotto.list), FUN = function(x) {
  x <- cellProximityEnrichment(gobject = giotto.list[[x]],
                               cluster_column = 'classification',
                               spatial_network_name = 'Delaunay_network',
                               adjust_method = 'fdr',
                               number_of_simulations = 1)
})
names(cell_proximities.list)<-patient_ids
```
Your notes on the cell proximity function say: "The first data.table (raw_sim_table) shows the raw observations of both the original and simulated networks". **By selecting "original" am I selecting the actual counts of all cell-cell interactions in my dataset?** At this time I do not need the enrichment/simulated network information. I would like counts of the real interactions occurring in my data.
https://rubd.github.io/Giotto_site/reference/cellProximityEnrichment.html
```
cell_proximities.list1<-lapply(X = cell_proximities.list, FUN = function(x) {
  x<-data.frame(x$raw_sim_table)
  x<-x[x$round=="original",]
})
```
Here I merge it back into a dataframe. My goal was to have a dataframe with the frequency of the actual cell-cell interactions occurring in my tissue per patient.
```
df_cell_cell <- lapply(names(cell_proximities.list1), function(i){
  cell_proximities.list1[[i]]$patient_ID<-i
  return(cell_proximities.list1[[i]])
}) %>%
  do.call(rbind, .)
```

Can you also clarify how exactly you count edges in the delaunay network as a cell-cell interaction? I saw in your function definition double edges between same cells were removed? Can you clarify this please.
https://github.com/RubD/Giotto/blob/master/R/spatial_interaction.R
```
 # remove double edges between same cells #
  spatial_network_annot = sort_combine_two_DT_columns(spatial_network_annot,
                                                      column1 = 'from', column2 = 'to',
                                                      myname = 'unified_cells')
  spatial_network_annot = spatial_network_annot[!duplicated(unified_cells)]
```

Thanks for your great package!

**Comment by RubD** [comment]
Hi @evanmaes ,
Can you let us know which version of Giotto you're currently using: `packageVersion('Giotto')`. That will help us to respond to your questions and provide additional support if needed.
Thanks

**Comment by XuanCao-CX** [comment]
Hi @evanmaes,

1, For this question "By selecting "original" am I selecting the actual counts of all cell-cell interactions in my dataset? ",   when running the code below, the column name “V1” is the counts of all cell-cell interactions for the ‘Delaunay_network’.

>cell_proximities = [cellProximityEnrichment](https://rubd.github.io/Giotto_site/reference/cellProximityEnrichment.html)(gobject = Giotto_object,  
cluster_column = 'cell_types',
                                           spatial_network_name = 'Delaunay_network',
                                           adjust_method = 'fdr',
                                           number_of_simulations = 2000)


> cell_proximities$raw_sim_table[round=="original”]

![image](https://user-images.githubusercontent.com/57889560/154767987-71a5178e-df82-4923-83fd-6bf9b538a591.png)

2, For the question “Can you also clarify how exactly you count edges in the delaunay network as a cell-cell interaction?”,  after running Giotto function annotateSpatialNetwork(),  interacted cell-cell pairs were listed in column ‘unified_int’ were used.

“a simplified network does not have double edges between cells”, so double edges between the same cells should be removed.

![image](https://user-images.githubusercontent.com/57889560/154768685-96612d01-0db0-4c0c-94d7-ae4dc5edcdfd.png)

![image](https://user-images.githubusercontent.com/57889560/154768697-ce9dfb91-381b-41fa-8359-ddb027c95239.png)

Thanks

**Comment by evanmaes** [comment]
Hello @XuanCao-CX @RubD 
Great, thank you very much for your response. That answered my questions! I was using version ‘1.0.4’. It may be helpful to note that in the instructions for those who wish to get the rawcounts of the cell-cell interactions. 

Similarly, when working with multiple samples -- I used the subsetGiotto() to build a list of subsetted Giotto objects based on my patient ID. This functionality may be found elsewhere in your documentation and maybe I missed it. It may be helpful to model after Seurat and build a SplitObject() functionality to aid in integrating large datasets in the future:
https://satijalab.org/seurat/reference/splitobject 

I appreciate your work! 
Best,
Evan

**Comment by RubD** [comment]
Thanks for the suggestion @evanmaes . We have the opposite function in the new development version of Giotto (>2, suite branch), i.e. to join multiple objects together. See http://giottosuite.com/reference/joinGiottoObjects.html and an example http://giottosuite.com/articles/Visium_prostate_integration_Sep30_21.html, but I agree that having a split function would also help for data analysis. 

You would just need to watch out, because you will distort the underlying spatial network. This is because you will likely remove specific cells from the dataset and create 'holes' in the tissue.
