### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by mreg05** [giotto-suite/Giotto#189]
I haven't been able to install the Giotto Suite using
> library(remotes)
> remotes::install_github("RubD/Giotto@suite") 

I get the following error, which I haven't been able to resolve:
> * installing *source* package ‘Giotto’ ...
> ** using staged installation
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** byte-compile and prepare package for lazy loading
> Note: possible error in 'set_default_spat_unit(gobject = gobject, ': unused argument (feat_type = feat_type) 
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded from temporary location
> Error: package or namespace load failed for ‘Giotto’ in namespaceExport(ns, exports):
>  undefined exports: spatPlotInteractive
> Error: loading failed
> Execution halted
> ERROR: loading failed

Any pointers on fixing this issue would be greatly appreciated!
-Mary

**Comment by RubD** [comment]
Hi @mreg05 Thanks for letting us know. I just pushed an update and I believe this should be fixed now. We're actively working on Giotto Suite and we forgot to update documentation, which led to this error. Let me know if this isn't resolved for you.

**Comment by mreg05** [comment]
Perfect - fixed! Thanks for the speedy response!!
