### ISSUE TITLE
No module named 'leidenalg'

### ISSUE THREAD

**Issue by howtofindme** [giotto-suite/Giotto#194]
hi,
when i run  this code:
    mini_visium <- doLeidenCluster(gobject = mini_visium, 
                               resolution = 0.4, n_iterations = 1000) 

a problem occurs : 
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'leidenalg'

Detailed traceback:
  File "<string>", line 10, in <module>
  File "D:\Win10 System\Documents\R\win-library\4.1\reticulate\python\rpytools\loader.py", line 44, in _import_hook
    level=level

So,i checked this :
![image](https://user-images.githubusercontent.com/72066151/158738342-41dde3b9-01b5-43b2-8d0d-3fd7090976c8.png)

And using conda, i found this:  leidenalg is there!!!
![image](https://user-images.githubusercontent.com/72066151/158738811-fbfa3f49-0257-4b0e-9dfd-3cc8e96e50f2.png)

And then i tried this : Although  leidenalg , pandas AND pillow is in my evrironment,but only pandas could be uesed.
![image](https://user-images.githubusercontent.com/72066151/158742932-66e17c48-9376-4e68-b69b-9d5cb5317c69.png)

Could you please help sovle this problem?

**Comment by RubD** [comment]
Hi,

Could you look at #207 and see if reinstalling the Giotto environment fixes the issue? 

I currently can not reproduce this issue on my hardware.

Thanks

**Comment by howtofindme** [comment]
Thanks, problem was solved after I re-configured conda environment.

By the way , I have another question about your published paper entitled "Giotto: a toolbox for integrative analysis and visualization of spatial expression data"

question1.Why √m is multiplexed in the equation?  Is there some evidence that suppots what you did ? 
question2.Is there any ideas if I want to know which cell type is most dominent in one spot?
For some cell types , the vaule of m  is small or obscure ;while for others, the value of m is large and specific. In this situation, I think there is no sense to compare ES value between two different cell types.Therefore, using this kind of enrichment method cannot distinguish which cell type is the most dominent in one spot.Am I right? If so, how can I  distinguish which cell type is the most dominent in one spot.

![image](https://user-images.githubusercontent.com/72066151/160232253-8d2bbf5d-3bf0-44c0-b3fe-b2e1cc88832f.png)

thank you again for your patience and comment

**Comment by RubD** [comment]
Sorry missed this comment. It's generally a better idea to start a new issue if you have a very different or unrelated question. I believe we did saw a very strong correlation between enrichment scores and quantitative deconvolution results.

I believe m is squared to reduce the weight of larger genesets
