### ISSUE TITLE
Convert giotto object to spatial anndata

### ISSUE THREAD

**Issue by TaoShiyue** [giotto-suite/Giotto#247]
Hi! Ruben
Since I want to convert my Giotto object into anndata to import in Scanpy, could I convert Giotto object to h5ad or loom data?
I only find the function that could convert anndata h5ad file into a Giotto object. 
Please help me with any possible solution. Thanks!

Best,
Shiyue

**Comment by RubD** [comment]
Hi @TaoShiyue , we currently don't have a stable and working solution for this problem. We hope to make this available in the near future. Thanks

**Comment by yubin-ai** [comment]
Hi Giotto developer, I am curious if there are any updates on this Giotto object to anndata conversion?

**Comment by RubD** [comment]
@mattobny is this something for which you have a working version?
