### ISSUE TITLE
Error in py_run_file_impl(file, local, convert) :    ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by agathalactiae** [giotto-suite/Giotto#251]
Hi, 

I am trying to do Leiden Clustering, but it seems like the code doesn't work really well on my M1 MacBook Air.

Here the code I have run: 
my_giotto_object_n = doLeidenCluster(gobject = my_giotto_object_n, name = "leiden_clus")

and here is the error message I got:
Error in py_run_file_impl(file, local, convert) : ModuleNotFoundError: No module named 'dataclasses'

I am trying to google it, but it says that the error is due to python3.6 which does not support it. I also have no idea about this message when I install the environment, it seems like it changes the python3.8 to python3.6 with message on below:

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env

  added / updated specs:
    - python=3.6

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/osx-64::certifi-2021.5.30-py36hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-12.0.0-h2f01273_0

The following packages will be REMOVED:

  python_abi-3.8-2_cp38

Please suggest what should I do for this error, thank you

**Comment by RubD** [comment]
Seems like this might the same issue as #250

**Comment by agathalactiae** [comment]
> Seems like this might the same issue as #250

Thank you for your prompt reply

I am not really sure that the issue is similar with #250 because I don't have any error messages like this : Error: installation of 'python=3.6' into environment 'giotto_env' failed [error code 1]

Below is the detail of the successful installation message:
|---- install local miniconda ----| 
* Installing Miniconda -- please wait a moment ...
* Downloading 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh' ...
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh'
Content type 'application/x-sh' length 58693864 bytes (56.0 MB)
==================================================
downloaded 56.0 MB

PREFIX=/Users/agathanabillalestari/Library/r-miniconda
Unpacking payload ...
Collecting package metadata (current_repodata.json): ...working... done                                        
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda

  added / updated specs:
    - brotlipy==0.7.0=py39h9ed2024_1003
    - ca-certificates==2022.3.29=hecd8cb5_1
    - certifi==2021.10.8=py39hecd8cb5_2
    - cffi==1.15.0=py39hc55c11b_1
    - charset-normalizer==2.0.4=pyhd3eb1b0_0
    - colorama==0.4.4=pyhd3eb1b0_0
    - conda-content-trust==0.1.1=pyhd3eb1b0_0
    - conda-package-handling==1.8.1=py39hca72f7f_0
    - conda==4.12.0=py39hecd8cb5_0
    - cryptography==36.0.0=py39hf6deb26_0
    - idna==3.3=pyhd3eb1b0_0
    - libcxx==12.0.0=h2f01273_0
    - libffi==3.3=hb1e8313_2
    - ncurses==6.3=hca72f7f_2
    - openssl==1.1.1n=hca72f7f_0
    - pip==21.2.4=py39hecd8cb5_0
    - pycosat==0.6.3=py39h9ed2024_0
    - pycparser==2.21=pyhd3eb1b0_0
    - pyopenssl==22.0.0=pyhd3eb1b0_0
    - pysocks==1.7.1=py39hecd8cb5_0
    - python.app==3=py39hca72f7f_0
    - python==3.9.12=hdfd78df_0
    - readline==8.1.2=hca72f7f_1
    - requests==2.27.1=pyhd3eb1b0_0
    - ruamel_yaml==0.15.100=py39h9ed2024_0
    - setuptools==61.2.0=py39hecd8cb5_0
    - six==1.16.0=pyhd3eb1b0_1
    - sqlite==3.38.2=h707629a_0
    - tk==8.6.11=h7bc2e8c_0
    - tqdm==4.63.0=pyhd3eb1b0_0
    - tzdata==2022a=hda174b7_0
    - urllib3==1.26.8=pyhd3eb1b0_0
    - wheel==0.37.1=pyhd3eb1b0_0
    - xz==5.2.5=h1de35cc_0
    - yaml==0.2.5=haf1e3a3_0
    - zlib==1.2.12=h4dc903c_1


The following NEW packages will be INSTALLED:

  colorama           pkgs/main/noarch::colorama-0.4.4-pyhd3eb1b0_0
  conda-content-tru~ pkgs/main/noarch::conda-content-trust-0.1.1-pyhd3eb1b0_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1

The following packages will be SUPERSEDED by a higher-priority channel:

  tqdm               pkgs/main/osx-64::tqdm-4.64.0-py39hec~ --> pkgs/main/noarch::tqdm-4.63.0-pyhd3eb1b0_0
  urllib3            pkgs/main/osx-64::urllib3-1.26.9-py39~ --> pkgs/main/noarch::urllib3-1.26.8-pyhd3eb1b0_0

The following packages will be DOWNGRADED:

  ca-certificates                      2022.4.26-hecd8cb5_0 --> 2022.3.29-hecd8cb5_1
  certifi                        2022.5.18.1-py39hecd8cb5_0 --> 2021.10.8-py39hecd8cb5_2
  conda                               4.13.0-py39hecd8cb5_0 --> 4.12.0-py39hecd8cb5_0
  cryptography                        37.0.1-py39hf6deb26_0 --> 36.0.0-py39hf6deb26_0
  openssl                                 1.1.1o-hca72f7f_0 --> 1.1.1n-hca72f7f_0
  sqlite                                  3.38.3-h707629a_0 --> 3.38.2-h707629a_0
  tk                                      8.6.11-h3fd3227_1 --> 8.6.11-h7bc2e8c_0
  xz                                       5.2.5-hca72f7f_1 --> 5.2.5-h1de35cc_0
  zlib                                    1.2.12-h4dc903c_2 --> 1.2.12-h4dc903c_1


Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda

  added / updated specs:
    - conda


The following packages will be REMOVED:

  colorama-0.4.4-pyhd3eb1b0_0
  conda-content-trust-0.1.1-pyhd3eb1b0_0
  six-1.16.0-pyhd3eb1b0_1

The following packages will be UPDATED:

  ca-certificates                      2022.3.29-hecd8cb5_1 --> 2022.4.26-hecd8cb5_0
  certifi                          2021.10.8-py39hecd8cb5_2 --> 2022.5.18.1-py39hecd8cb5_0
  conda                               4.12.0-py39hecd8cb5_0 --> 4.13.0-py39hecd8cb5_0
  cryptography                        36.0.0-py39hf6deb26_0 --> 37.0.1-py39hf6deb26_0
  openssl                                 1.1.1n-hca72f7f_0 --> 1.1.1o-hca72f7f_0
  sqlite                                  3.38.2-h707629a_0 --> 3.38.3-h707629a_0
  tk                                      8.6.11-h7bc2e8c_0 --> 8.6.11-h3fd3227_1
  tqdm               pkgs/main/noarch::tqdm-4.63.0-pyhd3eb~ --> pkgs/main/osx-64::tqdm-4.64.0-py39hecd8cb5_0
  urllib3            pkgs/main/noarch::urllib3-1.26.8-pyhd~ --> pkgs/main/osx-64::urllib3-1.26.9-py39hecd8cb5_0
  xz                                       5.2.5-h1de35cc_0 --> 5.2.5-hca72f7f_1
  zlib                                    1.2.12-h4dc903c_1 --> 1.2.12-h4dc903c_2


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/r-reticulate

  added / updated specs:
    - numpy
    - python=3.8


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4
  ca-certificates    conda-forge/osx-64::ca-certificates-2022.5.18.1-h033912b_0
  libblas            conda-forge/osx-64::libblas-3.9.0-14_osx64_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-14_osx64_openblas
  libcxx             conda-forge/osx-64::libcxx-14.0.4-hc203e6f_0
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-14_osx64_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.20-openmp_hb3cd9ec_0
  libzlib            conda-forge/osx-64::libzlib-1.2.11-h6c3fc93_1014
  llvm-openmp        conda-forge/osx-64::llvm-openmp-14.0.4-ha654fa7_0
  ncurses            conda-forge/osx-64::ncurses-6.3-h96cf925_1
  numpy              conda-forge/osx-64::numpy-1.22.4-py38h3ad0702_0
  openssl            conda-forge/osx-64::openssl-3.0.3-hfe4f2af_0
  pip                conda-forge/noarch::pip-22.1.1-pyhd8ed1ab_0
  python             conda-forge/osx-64::python-3.8.13-h66c20e1_0_cpython
  python_abi         conda-forge/osx-64::python_abi-3.8-2_cp38
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  setuptools         conda-forge/osx-64::setuptools-62.3.2-py38h50d1736_0
  sqlite             conda-forge/osx-64::sqlite-3.38.5-hd9f0692_0
  tk                 conda-forge/osx-64::tk-8.6.12-h5dbffcc_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h6c3fc93_1014


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
* Miniconda has been successfully installed at "~/Library/r-miniconda".

 giotto environment found at 
 /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/bin/pythonw 

Remove all packages in environment /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env:


## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env


The following packages will be REMOVED:

  arpack-3.7.0-hefb7bc6_2
  bzip2-1.0.8-h0d85af4_4
  ca-certificates-2022.4.26-hecd8cb5_0
  certifi-2020.6.20-pyhd3eb1b0_3
  cycler-0.11.0-pyhd8ed1ab_0
  freetype-2.10.4-h4cff582_1
  glpk-4.65-h0f52abe_1004
  gmp-6.2.1-h2e338ed_0
  icu-69.1-he49afe7_0
  igraph-0.9.6-ha5be149_0
  jbig-2.1-h0d85af4_2003
  joblib-1.1.0-pyhd8ed1ab_0
  jpeg-9e-h5eb16cf_1
  kiwisolver-1.3.1-py36hc61eee1_1
  lcms2-2.12-h577c468_0
  leidenalg-0.8.7-py36hefe7e0e_0
  lerc-3.0-he49afe7_0
  libblas-3.9.0-14_osx64_openblas
  libcblas-3.9.0-14_osx64_openblas
  libcxx-12.0.0-h2f01273_0
  libdeflate-1.10-h0d85af4_0
  libffi-3.3-hb1e8313_2
  libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5-9.3.0-h6c81a4c_23
  libiconv-1.16-haf1e3a3_0
  liblapack-3.9.0-14_osx64_openblas
  libopenblas-0.3.20-openmp_hb3cd9ec_0
  libpng-1.6.37-h7cec526_2
  libtiff-4.3.0-h17f2ce3_3
  libwebp-base-1.2.2-h0d85af4_1
  libxml2-2.9.12-h7e28ab6_1
  libzlib-1.2.11-h6c3fc93_1014
  llvm-openmp-14.0.4-ha654fa7_0
  lz4-c-1.9.3-he49afe7_1
  matplotlib-base-3.3.4-py36h4ea959b_0
  metis-5.1.0-h2e338ed_1006
  mpfr-4.1.0-h0f52abe_1
  ncurses-6.3-h96cf925_1
  networkx-2.7.1-pyhd8ed1ab_0
  numpy-1.19.5-py36h08b5fde_2
  olefile-0.46-pyh9f0ad1d_1
  openjpeg-2.4.0-h6e7aa92_1
  openssl-1.1.1o-hca72f7f_0
  pandas-1.1.5-py36h2be6da3_0
  pillow-8.3.2-py36h950f3bb_0
  pip-21.2.2-py36hecd8cb5_0
  pyparsing-3.0.9-pyhd8ed1ab_0
  python-3.6.13-h88f2d9e_0
  python-dateutil-2.8.2-pyhd8ed1ab_0
  python-igraph-0.9.6-py36h576965e_0
  python-louvain-0.15-pyhd8ed1ab_1
  python.app-1.3-py36hfa26744_5
  python_abi-3.6-2_cp36m
  pytz-2022.1-pyhd8ed1ab_0
  readline-8.1-h05e3726_0
  scikit-learn-0.24.2-py36h979b75d_1
  scipy-1.5.3-py36h4f136de_1
  setuptools-58.0.4-py36hecd8cb5_0
  six-1.16.0-pyh6c4a22f_0
  sqlite-3.38.5-hd9f0692_0
  suitesparse-5.10.1-h7aff33d_1
  tbb-2021.5.0-h940c156_0
  texttable-1.6.4-pyhd8ed1ab_0
  threadpoolctl-3.1.0-pyh8a188c0_0
  tk-8.6.12-h5dbffcc_0
  tornado-6.1-py36hfa26744_1
  wheel-0.37.1-pyhd8ed1ab_0
  xz-5.2.5-haf1e3a3_1
  zlib-1.2.11-h6c3fc93_1014
  zstd-1.5.2-h582d3a0_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

 |---- install giotto environment ----| 
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4
  ca-certificates    conda-forge/osx-64::ca-certificates-2022.5.18.1-h033912b_0
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5
  libzlib            conda-forge/osx-64::libzlib-1.2.11-h6c3fc93_1014
  ncurses            conda-forge/osx-64::ncurses-6.3-h96cf925_1
  openssl            conda-forge/osx-64::openssl-3.0.3-hfe4f2af_0
  pip                conda-forge/noarch::pip-22.1.1-pyhd8ed1ab_0
  python             conda-forge/osx-64::python-3.8.13-h66c20e1_0_cpython
  python_abi         conda-forge/osx-64::python_abi-3.8-2_cp38
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  setuptools         conda-forge/osx-64::setuptools-62.3.2-py38h50d1736_0
  sqlite             conda-forge/osx-64::sqlite-3.38.5-hd9f0692_0
  tk                 conda-forge/osx-64::tk-8.6.12-h5dbffcc_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h6c3fc93_1014


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

  certifi            pkgs/main/osx-64::certifi-2021.5.30-py36hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-12.0.0-h2f01273_0

The following packages will be REMOVED:

  python_abi-3.8-2_cp38

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.5.1~ --> pkgs/main::ca-certificates-2022.4.26-hecd8cb5_0
  libffi               conda-forge::libffi-3.4.2-h0d85af4_5 --> pkgs/main::libffi-3.3-hb1e8313_2
  openssl             conda-forge::openssl-3.0.3-hfe4f2af_0 --> pkgs/main::openssl-1.1.1o-hca72f7f_0
  pip                conda-forge/noarch::pip-22.1.1-pyhd8e~ --> pkgs/main/osx-64::pip-21.2.2-py36hecd8cb5_0
  python             conda-forge::python-3.8.13-h66c20e1_0~ --> pkgs/main::python-3.6.13-h88f2d9e_0
  setuptools         conda-forge::setuptools-62.3.2-py38h5~ --> pkgs/main::setuptools-58.0.4-py36hecd8cb5_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env

  added / updated specs:
    - leidenalg
    - networkx
    - pandas
    - python-igraph
    - python-louvain
    - python.app
    - python=3.6
    - scikit-learn


The following NEW packages will be INSTALLED:

  arpack             conda-forge/osx-64::arpack-3.7.0-hefb7bc6_2
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  freetype           conda-forge/osx-64::freetype-2.10.4-h4cff582_1
  glpk               conda-forge/osx-64::glpk-4.65-h0f52abe_1004
  gmp                conda-forge/osx-64::gmp-6.2.1-h2e338ed_0
  icu                conda-forge/osx-64::icu-69.1-he49afe7_0
  igraph             conda-forge/osx-64::igraph-0.9.6-ha5be149_0
  jbig               conda-forge/osx-64::jbig-2.1-h0d85af4_2003
  joblib             conda-forge/noarch::joblib-1.1.0-pyhd8ed1ab_0
  jpeg               conda-forge/osx-64::jpeg-9e-h5eb16cf_1
  kiwisolver         conda-forge/osx-64::kiwisolver-1.3.1-py36hc61eee1_1
  lcms2              conda-forge/osx-64::lcms2-2.12-h577c468_0
  leidenalg          conda-forge/osx-64::leidenalg-0.8.7-py36hefe7e0e_0
  lerc               conda-forge/osx-64::lerc-3.0-he49afe7_0
  libblas            conda-forge/osx-64::libblas-3.9.0-14_osx64_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-14_osx64_openblas
  libdeflate         conda-forge/osx-64::libdeflate-1.10-h0d85af4_0
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  libiconv           conda-forge/osx-64::libiconv-1.16-haf1e3a3_0
  liblapack          conda-forge/osx-64::liblapack-3.9.0-14_osx64_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.20-openmp_hb3cd9ec_0
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  libtiff            conda-forge/osx-64::libtiff-4.3.0-h17f2ce3_3
  libwebp-base       conda-forge/osx-64::libwebp-base-1.2.2-h0d85af4_1
  libxml2            conda-forge/osx-64::libxml2-2.9.12-h7e28ab6_1
  llvm-openmp        conda-forge/osx-64::llvm-openmp-14.0.4-ha654fa7_0
  lz4-c              conda-forge/osx-64::lz4-c-1.9.3-he49afe7_1
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.3.4-py36h4ea959b_0
  metis              conda-forge/osx-64::metis-5.1.0-h2e338ed_1006
  mpfr               conda-forge/osx-64::mpfr-4.1.0-h0f52abe_1
  networkx           conda-forge/noarch::networkx-2.7.1-pyhd8ed1ab_0
  numpy              conda-forge/osx-64::numpy-1.19.5-py36h08b5fde_2
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openjpeg           conda-forge/osx-64::openjpeg-2.4.0-h6e7aa92_1
  pandas             conda-forge/osx-64::pandas-1.1.5-py36h2be6da3_0
  pillow             conda-forge/osx-64::pillow-8.3.2-py36h950f3bb_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-igraph      conda-forge/osx-64::python-igraph-0.9.6-py36h576965e_0
  python-louvain     conda-forge/noarch::python-louvain-0.15-pyhd8ed1ab_1
  python.app         conda-forge/osx-64::python.app-1.3-py36hfa26744_5
  python_abi         conda-forge/osx-64::python_abi-3.6-2_cp36m
  pytz               conda-forge/noarch::pytz-2022.1-pyhd8ed1ab_0
  scikit-learn       conda-forge/osx-64::scikit-learn-0.24.2-py36h979b75d_1
  scipy              conda-forge/osx-64::scipy-1.5.3-py36h4f136de_1
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  suitesparse        conda-forge/osx-64::suitesparse-5.10.1-h7aff33d_1
  tbb                conda-forge/osx-64::tbb-2021.5.0-h940c156_0
  texttable          conda-forge/noarch::texttable-1.6.4-pyhd8ed1ab_0
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.1.0-pyh8a188c0_0
  tornado            conda-forge/osx-64::tornado-6.1-py36hfa26744_1
  zstd               conda-forge/osx-64::zstd-1.5.2-h582d3a0_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.4.26-~ --> conda-forge::ca-certificates-2022.5.18.1-h033912b_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2021.5.30-py36hecd~ --> conda-forge::certifi-2021.5.30-py36h79c6626_0
  openssl              pkgs/main::openssl-1.1.1o-hca72f7f_0 --> conda-forge::openssl-1.1.1o-hfe4f2af_0
  python                pkgs/main::python-3.6.13-h88f2d9e_0 --> conda-forge::python-3.6.13-h7728216_0_cpython


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env

  added / updated specs:
    - python=3.6


The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.5.1~ --> pkgs/main::ca-certificates-2022.4.26-hecd8cb5_0
  certifi            conda-forge/osx-64::certifi-2021.5.30~ --> pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
  openssl            conda-forge::openssl-1.1.1o-hfe4f2af_0 --> pkgs/main::openssl-1.1.1o-hca72f7f_0
  python             conda-forge::python-3.6.13-h7728216_0~ --> pkgs/main::python-3.6.13-h88f2d9e_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Activated conda python: /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/bin/python
Collecting smfishhmrf
  Using cached smfishHmrf-1.3.3-py3-none-any.whl (51 kB)
Requirement already satisfied: matplotlib in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from smfishhmrf) (3.3.4)
Collecting seaborn
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Requirement already satisfied: pandas in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from smfishhmrf) (1.1.5)
Requirement already satisfied: scipy in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from smfishhmrf) (1.5.3)
Requirement already satisfied: numpy in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from smfishhmrf) (1.19.5)
Requirement already satisfied: python-dateutil>=2.1 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from matplotlib->smfishhmrf) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from matplotlib->smfishhmrf) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from matplotlib->smfishhmrf) (8.3.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from matplotlib->smfishhmrf) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from matplotlib->smfishhmrf) (3.0.9)
Requirement already satisfied: six>=1.5 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib->smfishhmrf) (1.16.0)
Requirement already satisfied: pytz>=2017.2 in /Users/agathanabillalestari/Library/r-miniconda/envs/giotto_env/lib/python3.6/site-packages (from pandas->smfishhmrf) (2022.1)
Installing collected packages: seaborn, smfishhmrf
Successfully installed seaborn-0.11.2 smfishhmrf-1.3.

I am trying to use python_path on the function, but it throws another error message
<img width="932" alt="Screenshot 2022-05-27 at 15 00 22" src="https://user-images.githubusercontent.com/93100652/170714697-06f01988-1048-4125-8a5d-0e16cdd23d0b.png">

can you advise what should I do?, thank you

**Comment by agathalactiae** [comment]
I have tried using python path instead of the Giotto environment using python3.9, yet I got the same exact message ModuleNotFoundError: No module named 'dataclasses' again 
<img width="1023" alt="Screenshot 2022-05-27 at 16 03 36" src="https://user-images.githubusercontent.com/93100652/170726577-49020902-952a-4bf2-9464-a6862ed54583.png">

I wonder what could be done to solve this error, thank you in advance.

**Comment by agathalactiae** [comment]
Thank you so much for your help, finally I use a python virtual environment for x84 Mac instead of the M1 and now the function can be run in the 4.1.2 Bird Hippie R x84 as well :)
