### ISSUE TITLE
missing function on the Giotto

### ISSUE THREAD

**Issue by agathalactiae** [giotto-suite/Giotto#256]
Hi, 

I am trying to do Cell-type enrichment and now on step 33 and 34 from cp_manuscript_code.Rmd. 

However, upon running the function on my laptop, I encounter some error as functions are not found such as:
- could not find function "makeSignMatrixDWLSfromMatrix"
- could not find function "rowMeans_flex"
- could not find function "runDWLSDeconv"

and even if I copy and paste the function manually to my R, in the step 34, I got this error message: 
- Error in select_expression_values(gobject = gobject, values = values) : 
  run first normalization step

Would anyone please suggest what am I supposed to do to solve these errors?

Thank you and I would be appreciate for any helps. 

Cheers, 

Agatha

**Comment by XuanCao-CX** [comment]
Hi,

Could you upload your cp_manuscript_code.Rmd? Then I will take a look.

Best,
Xuan

**Comment by XuanCao-CX** [comment]
Hi,

Which version of Giotto did you use?

Best,

Xuan

**Comment by agathalactiae** [comment]
Hi!, 

I'm using this version (Giotto_1.0.4):
<img width="675" alt="Screenshot 2022-06-09 at 10 37 52" src="https://user-images.githubusercontent.com/93100652/172816860-503fd43c-44a5-4b10-9a7f-8d9eeb09a659.png">

Please kindly suggest and thank you for your help.

Cheers, 

Agatha

**Comment by agathalactiae** [comment]
Hi, 

I closed and opened a new-project, re-did the installation and now I can use the Giotto_1.1.1, and now it runs smoothly. Thank you for your help and guidance. 

Cheers, 
Agatha
