### ISSUE TITLE
Status 1 in step 45 and error message in step 50

### ISSUE THREAD

**Issue by agathalactiae** [giotto-suite/Giotto#258]
Hi, 

I'm so sorry for asking many question, but I encounter this error when I am trying to run step 45 and 50 on cp_manuscript_code.Rmd with the 2020_ST_STCC data. 

Below is the details:

the script for step 45:

```
hmrf_folder <- paste0(path.expand(save_directory),'/','11_HMRF/')
if(!file.exists(hmrf_folder)) dir.create(hmrf_folder, recursive = T)

# input is the top 40 genes per co-expression module
HMRF_spat_genes <- doHMRF(gobject = st_stcc_object,
                          expression_values = "normalized",
                          spatial_genes = names(cluster_genes),
                          spatial_network_name = "Delaunay_network",
                          zscore = "none",
                          k = 8,
                          betas = c(0,5,6),
                          output_folder = paste0(hmrf_folder, 'HMRF_output2'))

## add HMRF of interest to giotto object
st_stcc_object <- addHMRF(gobject = st_stcc_object,
                            HMRFoutput = HMRF_spat_genes,
                            k = 8, betas_to_add = c(0, 10, 15, 20),
                            hmrf_name = 'HMRF')
```

and here is the error message:

> The operation couldn’t be completed. Unable to locate a Java Runtime.
> Please visit http://www.java.com for information on installing Java.
> 
> Done reading expression
> Done reading location
> Done reading graph
> Start calculating independent regions
> Edges for component 0
> Traceback (most recent call last):
>   File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/reader2.py", line 215, in <module>
>     f = open(block_file)
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore/blocks.txt'
> [1] "/Users/agathanabillalestari/opt/miniconda3/envs/summer-research/bin/python3 /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/get_result2.py -r \"/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore\" -a test -k 8 -b 0"
> Traceback (most recent call last):
>   File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/get_result2.py", line 64, in <module>
>     cl = reader.read_classes("%s/k_%d/f%s.beta.%.1f.prob.txt" % (args.result_dir, args.k, args.name, args.beta))
>   File "/Users/agathanabillalestari/opt/miniconda3/envs/summer-research/lib/python3.9/site-packages/smfishHmrf/reader.py", line 75, in read_classes
>     f = open(n)
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore/k_8/ftest.beta.0.0.prob.txt'
> Warning in system(command = result_command, intern = T) :
>   running command '/Users/agathanabillalestari/opt/miniconda3/envs/summer-research/bin/python3 /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/get_result2.py -r "/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore" -a test -k 8 -b 0' had status 1
> 
>  these column names were already used:  HMRF_k8_b.0 
>  and will be overwritten 
> [1] "/Users/agathanabillalestari/opt/miniconda3/envs/summer-research/bin/python3 /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/get_result2.py -r \"/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore\" -a test -k 8 -b 10"
> Traceback (most recent call last):
>   File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/get_result2.py", line 64, in <module>
>     cl = reader.read_classes("%s/k_%d/f%s.beta.%.1f.prob.txt" % (args.result_dir, args.k, args.name, args.beta))
>   File "/Users/agathanabillalestari/opt/miniconda3/envs/summer-research/lib/python3.9/site-packages/smfishHmrf/reader.py", line 75, in read_classes
>     f = open(n)
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore/k_8/ftest.beta.10.0.prob.txt'
> Warning in system(command = result_command, intern = T) :
>   running command '/Users/agathanabillalestari/opt/miniconda3/envs/summer-research/bin/python3 /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/get_result2.py -r "/Users/agathanabillalestari/summer_research_project/Giotto/save_dir/11_HMRF/HMRF_output2/result.spatial.zscore" -a test -k 8 -b 10' had status 1

Meanwhile for step number 50, the problem is in ICGscoresHighGenes 

```
## select top 25th highest expressing genes
gene_metadata <- fDataDT(st_stcc_object)

high_expressed_genes <- gene_metadata[mean_expr_det > quantile(gene_metadata$mean_expr_det)[4]]$gene_ID

## identify genes that are associated with proximity to other cell types
ICGscoresHighGenes <-  findInteractionChangedGenes(gobject = st_stcc_object2,
                                                   selected_genes = high_expressed_genes,
                                                   spatial_network_name = 'Delaunay_network',
                                                   cluster_column = 'HMRF_k8_b.20',
                                                   diff_test = 'permutation',
                                                   adjust_method = 'fdr',
                                                   nr_permutations = 2000,
                                                   do_parallel = TRUE, cores = 4)
## visualize
plotCellProximityGenes(my_giotto_object,
                       cpgObject = ICGscoresHighGenes,
                       method = 'dotplot')

```

and below is the error message:

> Error in `:=`(spec_int, paste0(cell_type, "--", int_cell_type)) : Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

Please kindly suggest a solution for this problems. 

Thank you and cheers, 

Agatha

**Comment by RubD** [comment]
Hi Agatha,
It seems that the first error could potentially be resolved by installing java on your machine.

We would need more information to resolve the second issue, do you know after which exact command you see this error?

Thanks

**Comment by agathalactiae** [comment]
Hi, 

Thank you for responding, I'll try to re-install the Java, seems weird as it is on the bin folder. 

For the second problem, it is on:
```
ICGscoresHighGenes <-  findInteractionChangedGenes(gobject = st_stcc_object2,
                                                   selected_genes = high_expressed_genes,
                                                   spatial_network_name = 'Delaunay_network',
                                                   cluster_column = 'HMRF_k8_b.20',
                                                   diff_test = 'permutation',
                                                   adjust_method = 'fdr',
                                                   nr_permutations = 2000,
                                                   do_parallel = TRUE, cores = 4)
```

Would you please suggest what should I do to re-solve this issue?

Thank you and cheers, 

Agatha

**Comment by agathalactiae** [comment]
Hi, 

After I installed the java, and reduce the nr_permutations to 100, it works. However, it raises a question, how many permutation is recommended to run this function? as 2000 kills my laptop (I run in MacBook Air M1, 8 Gb RAM). 

Looking forward for your suggestion

Thanks and cheers, 

Agatha
