### ISSUE TITLE
Transfer seuratToGiotto result object: error PCA/UMAP + meta.data information

### ISSUE THREAD

**Issue by kokonech** [giotto-suite/Giotto#260]
Hi, thanks a lot for developing awesome tool! 
Just wanted to note that I found a possible error in the code with conversion from Seurat to Giotto:
https://github.com/RubD/Giotto/blob/suite/R/interoperability.R 

When converting PCA/UMAP the function plotPCA/UMAP did not work. From inspecting the code I found that names are not provided correctly, "test" word is used there:
```
  umap = list(type = "cells",
                  spat_unit = "cell",
                  name = "test",
                  reduction_method = 'umap',
                  coordinates = umap_coord,
                  misc = NULL)
```
This was fixed by naming the figure by the type:
```
  umap = list(type = "cells",
                  spat_unit = "cell",
                  name = "umap",
                  reduction_method = 'umap',
                  coordinates = umap_coord,
                  misc = NULL)
```
However, I noticed that some useful info is not transferred from Seurat: meta.data annotation. Is there any easy way to include it in order to allow use further using in Giotto e.g. in spatPlot or as assigned clusters for further analysis?

**Comment by RubD** [comment]
Tagging @EmmaKelley here who helped develop this function. It should be relatively simple to transfer additional metadata and we'll take a look. Thanks for the suggestion.

**Comment by kokonech** [comment]
Thanks for quick reply, look forward to the news! Is there already possible fix available in other repo (szheng29)? Is it going to be merged with "suite"?

**Comment by RubD** [comment]
Yes, I just merged it. Thanks @szheng29 for fixing this issue!

**Comment by kokonech** [comment]
Great, tnx!
