### ISSUE TITLE
bugs report

### ISSUE THREAD

**Issue by JLiLab** [giotto-suite/Giotto#270]
Thank you for creating such a promising tool!

I noticed a bug in the new Giotto suite: pDataDT() seems to stop working, creating problems for other functions depending on the cell_metatdata, such as addStatistics() and runGiottoHarmony().

addStatistics(giottoObject) produced the following error message:
"Error in data.table::merge.data.table(cell_metadata, by.x = "cell_ID",  : 
  Elements listed in `by.x` must be valid column names in x."

runGiottoHarmony(giottoObject) produced the following error message: 
"Error in harmony::HarmonyMatrix(data_mat = matrix_to_use, meta_data = metadata,  : 
  meta_data must be either a data.frame or a vector with batch values for each cell"

 It may have something to do with how giottoObject is created with createGiottoObject function.

**Comment by RubD** [comment]
If you still see this issue could you please provide a minimal reproducible example? See also https://giottosuite.readthedocs.io/en/latest/github_issues.html 

We have not been able to reproduce this error. I'd advise to use the latest Giotto Suite version (suit branch > 3.0).
