### ISSUE TITLE
Error with Nanostring CosMx Subcellular Lung Cancer example

### ISSUE THREAD

**Issue by bicciatolab** [giotto-suite/Giotto#297]
Hi, 

I am trying the Nanostring CosMx Subcellular Lung Cancer example but this code chunk: 

`fovsubset = createGiottoObjectSubcellular(gpoints = list('rna' = tx_coord),
                                            gpolygons = list('cell' = segmentation_mask),
                                            polygon_mask_list_params = list(mask_method = 'guess',
                                                                            flip_vertical = TRUE,
                                                                            flip_horizontal = FALSE,
                                                                            shift_horizontal_step = FALSE),
                                            instructions = instrs)`

 is always retiring this error:

1. Start extracting polygon information 
[1] 0
[1] 3648
2. Finished extracting polygon information 
3. Start extracting spatial feature information 
Selecting "gene_id" as feat_ID column
Selecting "x" and "y" as x and y respectively
4. Finished extracting spatial feature information 
**Error: [$] feat_ID is not a variable name in x**

as the gobject@feat_info[[feat]]@spatVector does not contain any "feat_ID" field.

Am I wrong, or `createGiottoObjectSubcellular` should allow also extracting the polygons of Lung12 sample?

I am running Giotto version 2.0.0.998 in R version 4.2.1.

Thanks a lot in advance,
Silvio

**Comment by jiajic** [comment]
Hi Silvio,

Thank you for bringing this issue to our attention! I'll take a look at it.

Best,
George

**Comment by jiajic** [comment]
Hi Silvio,

We have pushed an update that should address this issue. It will require a reinstall of Giotto Suite.

The CosMx vignette has also been checked and updated for code consistency (keep in mind however that updates to dependency packages since the writing of the vignette have made it so that the vignette's figures are different from what you will get when running the code).

Best,
George

**Comment by bicciatolab** [comment]
Hi George

Thanks a lot for the prompt update.
Everything works perfectly right now. I could create a Giotto object for each FOVs, join the objects, and extract the polygon data from combined cell data.
I run it quite smoothly on using all FOVs of Lung12 and Lung5_Rep1 samples on a MacBook Pro with 32 GB.
Thanks again.

Kind regards
Silvio

---
Silvio Bicciato
Professor of Bioengineering
Dept. of Life Sciences
University of Modena and Reggio Emilia
Via G. Campi, 287 – 41100 Modena
phone: +39 059 2055219<tel:+39%20059%20205%205219>
fax: +39 059 2055410<tel:+39%20059%20205%205410>
skype: silvbicc
web: Silvio Bicciato at UniMORE<http://personale.unimore.it/Rubrica/Dettaglio/sbicciat>




From: George Chen ***@***.***>
Reply to: RubD/Giotto ***@***.***>
Date: Monday, 15 August 2022 at 7:23 PM
To: RubD/Giotto ***@***.***>
Cc: Bicciato Lab ***@***.***>, Author ***@***.***>
Subject: Re: [RubD/Giotto] Error with Nanostring CosMx Subcellular Lung Cancer example (Issue #297)


Hi Silvio,

We have pushed an update that should address this issue. It will require a reinstall of Giotto Suite.

The CosMx vignette has also been checked and updated for code consistency (keep in mind however that updates to dependency packages since the writing of the vignette have made it so that the vignette's figures are different from what you will get when running the code).

Best,
George
