### ISSUE TITLE
There is something wrong in running initHMRF_V2 and doHMRF_V2

### ISSUE THREAD

**Issue by Tidebear** [giotto-suite/Giotto#300]
dear sir,
     I have some trouble in  running initHMRF_V2 this function, what i am suprised is i have met none problem before running this funtion. Here are the problems I encountered:
hmrf=initHMRF_V2(adata, spatial_network_name="spatial_network", use_spatial_genes="silhouetteRank", k=7, nstart=10)
Error in stats::hclust(d = cor_dist, method = hclust_method) : 
  NA/NaN/Inf in foreign function call (arg 10)
In addition: Warning messages:
1: In stats::cor(x, ...) : standard deviation is zero
2: In stats::cor(x, ...) : standard deviation is zero

**Comment by XuanCao-CX** [comment]
Hi @Tidebear ,

Could you please provide all the record when you run initHMRF_V2? It will be helpful.

Thanks

Xuan

**Comment by Tidebear** [comment]
Hi @XuanCao-CX  ,
Thank you for your advice, I know what went wrong with the last question : there is something wrong with my Giotto running enviroment, and i I've taken care of it. However i meet another problem when running HMRF, Here is the complete procedure I ran:
[1] "Doing beta=0.000"
Iteration 1: relative error of mean = 0.5; covariance = 0.6
Iteration 2: relative error of mean = 0.7; covariance = 0.7
Iteration 3: relative error of mean = 0.03; covariance = 0.02
Iteration 4: relative error of mean = 0.002; covariance = 0.001
Iteration 5: relative error of mean = 3e-04; covariance = 3e-04
Iteration 6: relative error of mean = 0.006; covariance = 0.007
Iteration 7: relative error of mean = 0.007; covariance = 0.009
Iteration 8: relative error of mean = 2e-04; covariance = 3e-04
Iteration 9: relative error of mean = 0.02; covariance = 0.03
Iteration 10: relative error of mean = 0.02; covariance = 0.03
Iteration 11: relative error of mean = 0.006; covariance = 0.007
Iteration 12: relative error of mean = 0.04; covariance = 0.04
Iteration 13: relative error of mean = 5e-08; covariance = 5e-08

HMRF is stopping at large beta >= 0, numerical error occurs, results of smaller betas were stored
Error in class(result.hmrf) <- append(class(result.hmrf), "HMRFoutput") : 
    attempt to set an attribute on NULL

I don "t know whether  the number of top_genes is enough, hmrf function always selects 500 spatial genes to run and my sample(my sample is DLPFC-151507) have more than 20000 genes(after running filter function).

Thanks

Tidebear

**Comment by pacificma** [comment]
Hi, @Tidebear 

Thank you for noticing us that you fixed the previous issue.
Would you provide more information about your previous steps and parameter setting for this hmrf clustering analysis? Maybe you can also send us the piece of code that you were using? 

For the number of genes to select in the analysis, among total 20000 genes in your data sets, only a small subset could be identified as highly variable genes or spatially variable genes, and those genes will be mainly contributing the domain clustering. We would imagine, by using the full set of genes, it won't provide much improve on the result, but cost huge increase on the computation burden. That is why many clustering analysis were performed only on a focused subset of gene such as we have in Giotto.


Best, Weiping

**Comment by Tidebear** [comment]
Hi,Weiping


Thank you very much for your letter and your warm reply.
I have solved the problem with the code， After I install Giotto on the new computer, it can run. It is amazing. Personally, I think there is a compatibility problem between the running environment and the updated package. Besides, I can't use the Python environment created by myself to run Giotto, so I can only use the Miniconda environment created by you by default. I see many users also have this problem, and may need to optimize the code.&nbsp;


At the same time, I am working on problems related to spatial transcriptomes, and recently I need to use Giotto to identify spatial domains. The tool you developed is very good in the field of single cell omics, but it seems that the performance of spatial domain recognition is not very good. (I know Giotto doesn't seem to be used for spatial cortex recognition), so I used Giotto to test the DLPFC dataset (Human dorsolateral prefrontal Cortex Data of spatialLIBD), and although I adjusted a lot of parameters, I found that the results of each cluster are quite different, and I wonder if you can test the relevant data sets. At the end, I will attach the errors of the previous code running and some results of spatial domain identification with Giotto.
Looking forward to your reply





Best, Tidebear


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RubD/Giotto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月20日(星期六) 凌晨3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RubD/Giotto] There is something wrong in running initHMRF_V2 and doHMRF_V2 (Issue #300)





 
Hi, @Tidebear
 
Thank you for noticing us that you fixed the previous issue.
 Would you provide more information about your previous steps and parameter setting for this hmrf clustering analysis? Maybe you can also send us the piece of code that you were using?
 
For the number of genes to select in the analysis, among total 20000 genes in your data sets, only a small subset could be identified as highly variable genes or spatially variable genes, and those genes will be mainly contributing the domain clustering. We would imagine, by using the full set of genes, it won't provide much improve on the result, but cost huge increase on the computation burden. That is why many clustering analysis were performed only on a focused subset of gene such as we have in Giotto.
 
Best, Weiping

**Comment by gcyuan** [comment]
Hi Tidebear

Thank you very much for your helpful feedback. I think the reason you have
different results may be attributed to two reasons: 1. k-means associated
random initialization; 2. beta value too large. Although this can be
'fixed' by starting with a fixed value of random seed for initialization,
we didn't implement this approach because we think the degree of
variability offers insights re the quality of the parameter setting, i.e.,
if the setting is appropriate, the variation between different runs should
be minor. We will continue to improve the HMRF algorithm to increase its
robustness and accuracy.
Could you explain what you mean by 'I know Giotto doesn't seem to be used
for spatial cortex recognition'? In our Giotto paper (as well as two
previous papers: Zhu et al 2018 and Eng 2018), we did apply HMRF to
identify spatial domains in cortex region. Not sure if you have something
else in mind.

Best
GC
