### ISSUE TITLE
module: leidenalg was not found with python

### ISSUE THREAD

**Issue by moutazhelal** [giotto-suite/Giotto#305]
Dear Authors,

Thank you for reading my message and I would appreciate any help
I have faced a problem while using Giotto when I load the environment by running createGiottoInstructions and then start creating Giotto object I get this warring message 

```
instrs = createGiottoInstructions(save_dir = "A1_Human_Tumor/",
                                  save_plot = TRUE,
                                  show_plot = TRUE,
                                  plot_format= "pdf")


## directly from visium folder
BT = createGiottoVisiumObject(
        visium_dir = NULL,
        expr_data =  "filter",
        gene_column_index = 1,
        h5_visium_path = "F:/Spatial_transcriptomics/outs/filtered_feature_bc_matrix.h5",
        h5_tissue_positions_path = "F:/Spatial_transcriptomics/outs/spatial/tissue_positions_list.csv",
        h5_image_png_path = "F:/Spatial_transcriptomics/outs/spatial/tissue_lowres_image.png",
        h5_json_scalefactors_path = "F:/Spatial_transcriptomics/outs/spatial/scalefactors_json.json",
        png_name = "tissue_lowres_image.png",
        instructions = instrs,
        verbose = TRUE)
```

```
Warning message:
In createGiottoObject(expression = raw_matrix, expression_feat = "rna",  :
  module: leidenalg was not found with python path: C:/Users/moutaz/AppData/Local/r-miniconda\envs\giotto_env\python.exe
```
and then when I cluster an Error comes up 

```
Error in py_run_file_impl(file, local, convert) : 
  ImportError: DLL load failed: The specified procedure could not be found.

```
I tried re-installing Giotto environment using 
installGiottoEnvironment(force_environment = TRUE) with no success.

I also ran commands that were recommended by @RubD  in previous issues   
 ```
reticulate::conda_list()
          name                                                                        python
1         base                     C:\\Users\\moutaz\\AppData\\Local\\r-miniconda/python.exe
2   giotto_env   C:\\Users\\moutaz\\AppData\\Local\\r-miniconda\\envs\\giotto_env/python.exe
3 r-reticulate C:\\Users\\moutaz\\AppData\\Local\\r-miniconda\\envs\\r-reticulate/python.exe
```
```
reticulate::py_config()
python:         C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/python.exe
libpython:      C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/python36.dll
pythonhome:     C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env
version:        3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/Lib/site-packages/numpy
numpy_version:  1.19.5
pandas:         C:\Users\moutaz\AppData\Local\R-MINI~1\envs\GIOTTO~1\lib\site-packages\pandas\__init__.p

NOTE: Python version was forced by use_python function

```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       Europe/Berlin
 date     2022-08-18
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package         * version   date (UTC) lib source
 abind             1.4-5     2016-07-21 [1] CRAN (R 4.2.0)
 assertthat        0.2.1     2019-03-21 [1] CRAN (R 4.2.1)
 beachmat          2.12.0    2022-04-26 [1] Bioconductor
 BiocGenerics      0.42.0    2022-04-26 [1] Bioconductor
 BiocParallel      1.30.3    2022-06-07 [1] Bioconductor
 BiocSingular      1.12.0    2022-04-26 [1] Bioconductor
 bit               4.0.4     2020-08-04 [1] CRAN (R 4.2.1)
 bit64             4.0.5     2020-08-30 [1] CRAN (R 4.2.1)
 cachem            1.0.6     2021-08-19 [1] CRAN (R 4.2.1)
 callr             3.7.1     2022-07-13 [1] CRAN (R 4.2.1)
 cli               3.3.0     2022-04-25 [1] CRAN (R 4.2.1)
 cluster           2.1.3     2022-03-28 [2] CRAN (R 4.2.1)
 codetools         0.2-18    2020-11-04 [2] CRAN (R 4.2.1)
 colorspace        2.0-3     2022-02-21 [1] CRAN (R 4.2.1)
 cowplot           1.1.1     2020-12-30 [1] CRAN (R 4.2.1)
 crayon            1.5.1     2022-03-26 [1] CRAN (R 4.2.1)
 data.table        1.14.2    2021-09-27 [1] CRAN (R 4.2.1)
 DBI               1.1.3     2022-06-18 [1] CRAN (R 4.2.1)
 dbscan            1.1-10    2022-01-15 [1] CRAN (R 4.2.1)
 DelayedArray      0.22.0    2022-04-26 [1] Bioconductor
 deldir            1.0-6     2021-10-23 [1] CRAN (R 4.2.0)
 devtools          2.4.4     2022-07-20 [1] CRAN (R 4.2.1)
 digest            0.6.29    2021-12-01 [1] CRAN (R 4.2.1)
 dplyr             1.0.9     2022-04-28 [1] CRAN (R 4.2.1)
 ellipsis          0.3.2     2021-04-29 [1] CRAN (R 4.2.1)
 fansi             1.0.3     2022-03-24 [1] CRAN (R 4.2.1)
 farver            2.1.1     2022-07-06 [1] CRAN (R 4.2.1)
 fastmap           1.1.0     2021-01-25 [1] CRAN (R 4.2.1)
 fitdistrplus      1.1-8     2022-03-10 [1] CRAN (R 4.2.1)
 fs                1.5.2     2021-12-08 [1] CRAN (R 4.2.1)
 future            1.27.0    2022-07-22 [1] CRAN (R 4.2.1)
 future.apply      1.9.0     2022-04-25 [1] CRAN (R 4.2.1)
 generics          0.1.3     2022-07-05 [1] CRAN (R 4.2.1)
 ggplot2           3.3.6     2022-05-03 [1] CRAN (R 4.2.1)
 ggrepel           0.9.1     2021-01-15 [1] CRAN (R 4.2.1)
 ggridges          0.5.3     2021-01-08 [1] CRAN (R 4.2.1)
 Giotto          * 2.0.0.998 2022-08-18 [1] Github (RubD/Giotto@b9b5432)
 globals           0.16.0    2022-08-05 [1] CRAN (R 4.2.1)
 glue              1.6.2     2022-02-24 [1] CRAN (R 4.2.1)
 goftest           1.2-3     2021-10-07 [1] CRAN (R 4.2.0)
 gridExtra         2.3       2017-09-09 [1] CRAN (R 4.2.1)
 gtable            0.3.0     2019-03-25 [1] CRAN (R 4.2.1)
 hdf5r             1.3.5     2021-11-15 [1] CRAN (R 4.2.1)
 here              1.0.1     2020-12-13 [1] CRAN (R 4.2.1)
 htmltools         0.5.3     2022-07-18 [1] CRAN (R 4.2.1)
 htmlwidgets       1.5.4     2021-09-08 [1] CRAN (R 4.2.1)
 httpuv            1.6.5     2022-01-05 [1] CRAN (R 4.2.1)
 httr              1.4.4     2022-08-17 [1] CRAN (R 4.2.1)
 ica               1.0-3     2022-07-08 [1] CRAN (R 4.2.1)
 igraph            1.3.4     2022-07-19 [1] CRAN (R 4.2.1)
 IRanges           2.30.0    2022-04-26 [1] Bioconductor
 irlba             2.3.5     2021-12-06 [1] CRAN (R 4.2.1)
 jsonlite          1.8.0     2022-02-22 [1] CRAN (R 4.2.1)
 KernSmooth        2.23-20   2021-05-03 [2] CRAN (R 4.2.1)
 labeling          0.4.2     2020-10-20 [1] CRAN (R 4.2.0)
 later             1.3.0     2021-08-18 [1] CRAN (R 4.2.1)
 lattice           0.20-45   2021-09-22 [2] CRAN (R 4.2.1)
 lazyeval          0.2.2     2019-03-15 [1] CRAN (R 4.2.1)
 leiden            0.4.2     2022-05-09 [1] CRAN (R 4.2.1)
 lifecycle         1.0.1     2021-09-24 [1] CRAN (R 4.2.1)
 listenv           0.8.0     2019-12-05 [1] CRAN (R 4.2.1)
 lmtest            0.9-40    2022-03-21 [1] CRAN (R 4.2.1)
 magick            2.7.3     2021-08-18 [1] CRAN (R 4.2.1)
 magrittr          2.0.3     2022-03-30 [1] CRAN (R 4.2.1)
 MASS              7.3-57    2022-04-22 [2] CRAN (R 4.2.1)
 Matrix            1.4-1     2022-03-23 [2] CRAN (R 4.2.1)
 MatrixGenerics    1.8.1     2022-06-30 [1] Bioconductor
 matrixStats       0.62.0    2022-04-19 [1] CRAN (R 4.2.1)
 memoise           2.0.1     2021-11-26 [1] CRAN (R 4.2.1)
 mgcv              1.8-40    2022-03-29 [2] CRAN (R 4.2.1)
 mime              0.12      2021-09-28 [1] CRAN (R 4.2.0)
 miniUI            0.1.1.1   2018-05-18 [1] CRAN (R 4.2.1)
 munsell           0.5.0     2018-06-12 [1] CRAN (R 4.2.1)
 nlme              3.1-157   2022-03-25 [2] CRAN (R 4.2.1)
 parallelly        1.32.1    2022-07-21 [1] CRAN (R 4.2.1)
 patchwork         1.1.1     2020-12-17 [1] CRAN (R 4.2.1)
 pbapply           1.5-0     2021-09-16 [1] CRAN (R 4.2.1)
 pillar            1.8.0     2022-07-18 [1] CRAN (R 4.2.1)
 pkgbuild          1.3.1     2021-12-20 [1] CRAN (R 4.2.1)
 pkgconfig         2.0.3     2019-09-22 [1] CRAN (R 4.2.1)
 pkgload           1.3.0     2022-06-27 [1] CRAN (R 4.2.1)
 plotly            4.10.0    2021-10-09 [1] CRAN (R 4.2.1)
 plyr              1.8.7     2022-03-24 [1] CRAN (R 4.2.1)
 png               0.1-7     2013-12-03 [1] CRAN (R 4.2.0)
 polyclip          1.10-0    2019-03-14 [1] CRAN (R 4.2.0)
 prettyunits       1.1.1     2020-01-24 [1] CRAN (R 4.2.1)
 processx          3.7.0     2022-07-07 [1] CRAN (R 4.2.1)
 profvis           0.3.7     2020-11-02 [1] CRAN (R 4.2.1)
 progressr         0.10.1    2022-06-03 [1] CRAN (R 4.2.1)
 promises          1.2.0.1   2021-02-11 [1] CRAN (R 4.2.1)
 ps                1.7.1     2022-06-18 [1] CRAN (R 4.2.1)
 purrr             0.3.4     2020-04-17 [1] CRAN (R 4.2.1)
 R6                2.5.1     2021-08-19 [1] CRAN (R 4.2.1)
 ragg              1.2.2     2022-02-21 [1] CRAN (R 4.2.1)
 RANN              2.6.1     2019-01-08 [1] CRAN (R 4.2.1)
 rappdirs          0.3.3     2021-01-31 [1] CRAN (R 4.2.1)
 RColorBrewer      1.1-3     2022-04-03 [1] CRAN (R 4.2.0)
 Rcpp              1.0.9     2022-07-08 [1] CRAN (R 4.2.1)
 RcppAnnoy         0.0.19    2021-07-30 [1] CRAN (R 4.2.1)
 remotes           2.4.2     2021-11-30 [1] CRAN (R 4.2.1)
 reshape2          1.4.4     2020-04-09 [1] CRAN (R 4.2.1)
 reticulate        1.25      2022-05-11 [1] CRAN (R 4.2.1)
 rgeos             0.5-9     2021-12-15 [1] CRAN (R 4.2.1)
 rlang             1.0.4     2022-07-12 [1] CRAN (R 4.2.1)
 ROCR              1.0-11    2020-05-02 [1] CRAN (R 4.2.1)
 rpart             4.1.16    2022-01-24 [2] CRAN (R 4.2.1)
 rprojroot         2.0.3     2022-04-02 [1] CRAN (R 4.2.1)
 rstudioapi        0.13      2020-11-12 [1] CRAN (R 4.2.1)
 rsvd              1.0.5     2021-04-16 [1] CRAN (R 4.2.1)
 Rtsne             0.16      2022-04-17 [1] CRAN (R 4.2.1)
 S4Vectors         0.34.0    2022-04-26 [1] Bioconductor
 ScaledMatrix      1.4.0     2022-04-26 [1] Bioconductor
 scales            1.2.0     2022-04-13 [1] CRAN (R 4.2.1)
 scattermore       0.8       2022-02-14 [1] CRAN (R 4.2.1)
 sctransform       0.3.3     2022-01-13 [1] CRAN (R 4.2.1)
 sessioninfo       1.2.2     2021-12-06 [1] CRAN (R 4.2.1)
 Seurat            4.1.1     2022-08-18 [1] Github (satijalab/seurat@3bee84a)
 SeuratObject      4.1.0     2022-05-01 [1] CRAN (R 4.2.1)
 shiny             1.7.2     2022-07-19 [1] CRAN (R 4.2.1)
 sp                1.5-0     2022-06-05 [1] CRAN (R 4.2.1)
 spatstat.core     2.4-4     2022-05-18 [1] CRAN (R 4.2.1)
 spatstat.data     2.2-0     2022-04-18 [1] CRAN (R 4.2.1)
 spatstat.geom     2.4-0     2022-03-29 [1] CRAN (R 4.2.1)
 spatstat.random   2.2-0     2022-03-30 [1] CRAN (R 4.2.1)
 spatstat.sparse   2.1-1     2022-04-18 [1] CRAN (R 4.2.1)
 spatstat.utils    2.3-1     2022-05-06 [1] CRAN (R 4.2.1)
 stringi           1.7.8     2022-07-11 [1] CRAN (R 4.2.1)
 stringr           1.4.0     2019-02-10 [1] CRAN (R 4.2.1)
 survival          3.3-1     2022-03-03 [2] CRAN (R 4.2.1)
 systemfonts       1.0.4     2022-02-11 [1] CRAN (R 4.2.1)
 tensor            1.5       2012-05-05 [1] CRAN (R 4.2.0)
 textshaping       0.3.6     2021-10-13 [1] CRAN (R 4.2.1)
 tibble            3.1.8     2022-07-22 [1] CRAN (R 4.2.1)
 tidyr             1.2.0     2022-02-01 [1] CRAN (R 4.2.1)
 tidyselect        1.1.2     2022-02-21 [1] CRAN (R 4.2.1)
 urlchecker        1.0.1     2021-11-30 [1] CRAN (R 4.2.1)
 usethis           2.1.6     2022-05-25 [1] CRAN (R 4.2.1)
 utf8              1.2.2     2021-07-24 [1] CRAN (R 4.2.1)
 uwot              0.1.13    2022-08-16 [1] CRAN (R 4.2.1)
 vctrs             0.4.1     2022-04-13 [1] CRAN (R 4.2.1)
 viridisLite       0.4.0     2021-04-13 [1] CRAN (R 4.2.1)
 xtable            1.8-4     2019-04-21 [1] CRAN (R 4.2.1)
 zoo               1.8-10    2022-04-15 [1] CRAN (R 4.2.1)

 [1] C:/Users/moutaz/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.1/library
Python configuration ──────────────────────────────────────────────────────────────────────────────────────────────────────
 python:         C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/python.exe
 libpython:      C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/python36.dll
 pythonhome:     C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env
 version:        3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
 Architecture:   64bit
 numpy:          C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/Lib/site-packages/numpy
 numpy_version:  1.19.5
 pandas:         C:\Users\moutaz\AppData\Local\R-MINI~1\envs\GIOTTO~1\lib\site-packages\pandas\__init__.p
 
 NOTE: Python version was forced by use_python function

**Comment by mattobny** [comment]
Hello! 

I have had this same issue, but I believe I have found a workaround for it. We will continue to work on a more succinct solution in the initial installation. 

Within your Giotto environment ( C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/ ), can you please open a command prompt or anaconda powershell terminal, run python.exe, and provide the full startup message? It will provide some insight to what is going on within your environment.

**Comment by moutazhelal** [comment]
Dear @mattobny ,
Thank you for your response. 
please find the welcome message below:
![image](https://user-images.githubusercontent.com/63544197/186431789-a42bf1ed-eeca-4de0-93d3-298fd5164bc1.png)

**Comment by mattobny** [comment]
Just as was the case with my issue, it seems that your miniconda environment has not been activated according to that warning message. Please close RStudio if you have an active session, open a fresh anaconda terminal (type anaconda in the Windows search bar to find and launch it), and run the following command:

`C:\Users\moutaz\AppData\Local\r-miniconda\Scripts\activate C:\Users\moutaz\AppData\Local\r-miniconda\envs\giotto_env`

Then, leave the anaconda terminal open, reopen RStudio, and try to create your Giotto object. 

Quick side question: how are you importing Giotto into your R session? Are you using `devtools::load_all(path\to\Giotto)`, or have you installed it locally and call `library(Giotto)` to import the package?

**Comment by moutazhelal** [comment]
@mattobny Thank you for sharing your solution with me
to answer you question I import the environment using  `createGiottoInstructions` function 

I solved the problem by installing Giotto again.

**Comment by mattobny** [comment]
My pleasure! Glad to hear you solved the problem. Should it arise again, I have found a solution other than the workaround I provided above. 

First, I direct reticulate to use the Giotto environment in a fresh R session before importing:
`reticulate::use_python('C:/Users/moutaz/AppData/Local/r-miniconda/envs/giotto_env/python.exe')` 

Then, I ensure the packages are accessible:
` reticulate::py_module_available('igraph')`
` reticulate::py_module_available('leidenalg')`
` reticulate::py_module_available('networkx')`
` reticulate::py_module_available('community')`
` reticulate::py_module_available('sklearn')`

Finally, I import Giotto. This methodology will be shown in Giotto Suite tutorials within the coming weeks, and hopefully it will mitigate these Python issues.

**Comment by julietusc** [comment]
Hi @mattobny! I am having a similar issue with `leidenalg`. The `doLeidenCluster` function returns this error: 

Error in py_run_file_impl(path.expand(file), local, convert) :
ImportError: DLL load failed: The specified procedure could not be found.

I tried the suggested solutions above, and all packages except `leidenalg` are being found by my system. I tried `reticulate::py_install('leidenalg')` and it looked like it installed; however when I run the `py_module_available('leidenalg')` it is still false. I realize this may be an issue for reticulate, but I was hoping you may have some suggestions for Giotto specifically.

![image](https://github.com/drieslab/Giotto/assets/75763586/d50cd749-494f-4adb-9c74-e01a697eb6c6)

I also opened my giotto python.exe and there are no error messages or warnings when I open it in terminal. 

Also, is the `python_path` supposed to include the `python.exe` file name or just the folder it is in?

Any help is greatly appreciated!
