### ISSUE TITLE
Error in installGiottoEnvironment

### ISSUE THREAD

**Issue by vwtlin** [giotto-suite/Giotto#309]
Hi Giotto team, thanks for developing such an amazing tool for spatial data. I would like to use it to analyse the ligand receptor interaction but I could not install it properly. I will be grateful if you could provide some help.

I ran this code but having an error:

giotto environment found at
/home/cph/.local/share/r-miniconda/envs/giottoenv/bin/python
/tmp/RtmpI3W0nT/filed7f970edaae.sh:4:/home/cph/anaconda3/envs/giotto_env/etc/conda/deactivate.d/deactivate-r-base.sh:[[:notfound
/tmp/RtmpI3W0nT/filed7f970edaae.sh:5:/home/cph/anaconda3/envs/giotto_env/etc/conda/deactivate.d/deactivate-gxx_linux-64.sh:Syntaxerror:"("unexpected
Error in Sys.setenv(PATH = new _path)
: wrong length for argument
In addition: Warning message:
In system2(Sys.which("sh"), fi, stdout = if (identical(intern, FALSE)) ' else intern)
running command
"'/usr/bin/sh'/tmp/RtmpI3W0nT/filed7f970edaae.sh'had status 2

**Comment by RubD** [comment]
Did you use the `installGiottoEnvironment`? 
I'm also tagging @mattobny here who has been streamlining this process lately.

**Comment by mattobny** [comment]
Hello @vwtlin, `installGiottoEnvironment` has undergone some breaking changes over the past few weeks. Please try to run `installGiottoEnvironment(force_environment = TRUE, force_miniconda = TRUE)`; this should remove the old installation and reinstall the environment with the proper specs.

**Comment by vwtlin** [comment]
Hi @RubD @mattobny Thanks very much for your help. After following the updated tutorial, which is more clear to me, I was able to install the python environment manually and assign my python to Gitto. Everything is working now. 

Cheers,
Weitao
