### ISSUE TITLE
How to use intensity values without normalization

### ISSUE THREAD

**Issue by ymk555** [giotto-suite/Giotto#314]
Hello,

I'm interested in using Giotto for my spatial proteome data. 
Now I'm trying to follow your protocol (doi: 10.1002/cpz1.405) step by step using my proteome data.
The input expression data that I'm using is protein intensity data, not a gene count data. Also, there are missing values.
I'm not entirely sure if I understand exactly, the Giotto package is optimized for the gene count matrix and the normalization step is mandatory for further steps. But the embedded normalization is not appropriate for my intensity data. Also, if there is NaN, all values are changed to NaN after normalization.

Can I use raw input value for further steps without the normalization step?
For example, for `calculateHVG()`, it doesn't seem like that I can use raw expression values.
`expression_values = c("normalized", "scaled", "custom")`

Thank you,
Yumi

**Comment by RubD** [comment]
Hi Yumi,

Which Giotto version are you currently using? With Giotto Suite (in beta) you should be able to use any matrix as input. Or you could also copy your values directly into the normalized slot as a quick solution.

Ruben

**Comment by ymk555** [comment]
Now I'm using Giotto v 1.1.1. 
I tried to copy the raw expression data into the normalized exprs at your suggestion, and it worked for further analysis.
`my_giotto_object@norm_expr<-my_giotto_object@raw_exprs`

I'll also try Giotto Suite as well. 

Thank you

Yumi
