### ISSUE TITLE
Error in system("which python", intern = T) : 'which' not found

### ISSUE THREAD

**Issue by gerrardmai** [giotto-suite/Giotto#34]
> ## create
> VC_test <- createGiottoObject(raw_exprs = VC_exprs, spatial_locs = stitch_file, offset_file = my_offset_file)
Error in system("which python", intern = T) : 'which' not found

what is the matter? I run this code a couple of days ago, still work.

**Comment by RubD** [comment]
Does running `system("which python", intern = T)` in the R console work?

Alternatively, did you try reinstalling Giotto?
`library(remotes);
remotes::install_github("RubD/Giotto")`

We are currently working on some updates and maybe something broke. New tutorials for multiple datasets should all be up in the next couple of days.

**Comment by RubD** [comment]
I fixed the error in case you were running Giotto on a Windows machine, which does not have the **which** command. You can manually set your python path by running `createGiottoInstructions` and providing that output to the `createGiottoObject` function.

The updated version of Giotto creates an instruction file at the beginning which allows you to set a couple of parameters in the beginning and save figures automatically if desired. See [link](https://github.com/RubD/Giotto/blob/master/inst/faqs/instructions_and_plotting/instructions_and_plotting.md) for more information.
