### ISSUE TITLE
runPCA error : Error in if (R < eps2) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by pillar-github** [giotto-suite/Giotto#499]
stereo_go <- stereo_go %>% runPCA(expression_values = 'scaled', feats_to_use = 'hvf')

  "hvf" was found in the feats metadata information and will be used to select  highly variable features 
  class of selected matrix:  dgeMatrix 

   Error in if (R < eps2) { : missing value where TRUE/FALSE needed

**Comment by Ed2uiz** [comment]
Hey @pillar-github. Could you share which version of Giotto you are using? Also, did you modify the Stereo-seq tutorial code in anyway (e.g. different input data or different parameters upstream of runPCA)?

**Comment by Ed2uiz** [comment]
Hey @pillar-github I've double-checked the Stereo-seq tutorial and I cannot reproduce your error nor I have seen this error before. My guess is that you have modified the upstream commands from `stereo_go <- stereo_go %>% runPCA(expression_values = 'scaled', feats_to_use = 'hvf')` leading to the error. Please open another issue if you need further help, and be sure to share output of `sessionInfo() `and any upstream steps of your code.
