### ISSUE TITLE
filterGiotto does not filter according to given criteria

### ISSUE THREAD

**Issue by corecontingency** [giotto-suite/Giotto#500]
The filterGiotto command does not follow the filtering criteria given to it. For example, in the following code:

```
library(Giotto)
library(data.table)
library(magrittr)
library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyr)

# set results directory
results_folder <- '/home/user/src/results_alpha'

# create instructions
instrs <- createGiottoInstructions(save_dir = results_folder,
                                   python_path = "/home/user/.local/share/r-miniconda/bin/python",
                                   show_plot = FALSE,
                                   return_plot = FALSE,
                                   save_plot = FALSE,
                                   plot_format = "png",
                                   dpi = 300)

# set data directories
data_path_F4_h5 = "/path/to/dir/F4/outs/raw_feature_bc_matrix.h5"

data_path_F4_tissue_positions = "/path/to/dir/F4/outs/spatial/tissue_positions_list.csv"

data_path_F4_image = "/path/to/dir/F4/outs/spatial/tissue_hires_image.png"

data_path_F4_scalefactors = "/path/to/dir/F4/outs/spatial/scalefactors_json.json"


# create Giotto objects
F4 <- createGiottoVisiumObject(h5_visium_path = data_path_F4_h5,
				h5_tissue_positions_path = data_path_F4_tissue_positions,
				h5_image_png_path = data_path_F4_image,
				h5_json_scalefactors_path = data_path_F4_scalefactors,
                               instructions = instrs)


# subset on spots that were covered by tissue
metadata <- pDataDT(F4)
in_tissue_barcodes <- metadata[in_tissue == 1]$cell_ID
F4 <- subsetGiotto(F4, cell_ids = in_tissue_barcodes)

# clear unused variables
rm(metadata, in_tissue_barcodes)

# filter
F4 <- filterGiotto(gobject = F4,
                  expression_threshold = 1,
                  feat_det_in_min_cells = 5,
                  min_det_feats_per_cell = 1000,
                  expression_values = c('raw'),
                  verbose = T)

F4 <- addStatistics(F4, expression_values = "raw")

## normalize with standard log protocol - scalefactor is set to 6000
# normalize
F4_normalized_standard_6000 <- normalizeGiotto(gobject = F4, norm_methods = "standard", scalefactor = 6000, verbose = T)

# add gene & cell statistics
F4_normalized_standard_6000 <- addStatistics(gobject = F4_normalized_standard_6000)

# calculate HVF for the standard_6000 normalized data
F4_normalized_standard_6000 <- calculateHVF(gobject = F4_normalized_standard_6000)

subDir <- "hvf/"
dir.create(file.path(results_folder, subDir), recursive = T)
setwd(file.path(results_folder, subDir))
rm(subDir)

F4_metaDT <- F4_normalized_standard_6000@feat_metadata[["cell"]][["rna"]]@metaDT
write.csv(F4_metaDT, file = "F4_metaDT.csv")
```

filterGiotto contains this line, `feat_det_in_min_cells = 5`, which means that genes that are present in less than five spots should be removed. However, looking at the output data `F4_metaDT.csv`:

![Screenshot from 2023-01-16 12-24-01](https://user-images.githubusercontent.com/54042889/212752725-746ce973-5ae8-4285-8229-df81c24ab498.png)

we can see that the genes SAMD11, NOC2L, and KLH17 should be eliminated, as they do not fulfill the filtering criteria (they are only present in four spots, not five). However, they have not been eliminated.

The example data used is the same as in issue #483 .

Why is the `filterGiotto` command not following the given filtering settings?

Thank you for your help.

**Comment by RubD** [comment]
Thanks for the feedback. Could this be a result of filtering features (genes) first and then cells? In other words in the final matrix cells might have been deleted that expressed these very specific genes.

**Comment by mattobny** [comment]
@corecontingency 
@RubD is on the right track here. Features are filtered before cells and are used to filter cells as such: 
```
filter_index_feats = rowSums_flex(expr_values >= expression_threshold) >= feat_det_in_min_cells
selected_feat_ids = names(filter_index_feats[filter_index_feats == TRUE])

filter_index_cells = colSums_flex(expr_values[filter_index_feats, ] >= expression_threshold) >= min_det_feats_per_cell
selected_cell_ids = names(filter_index_cells[filter_index_cells == TRUE])
```
Therefore, Giotto essentially sums the amount of times expression for a given feature (hence the sum across rows) exceeds the expression threshold, and allows it to pass further down the filter process if that amount of instances (cells in which expression of a particular feature is greater than the threshold) is greater than `feat_det_in_min_cells`. Then, it sums the amount of times expression of these features exceeds the threshold within one cell, and allows it to pass through the filter if that amount of instances (features detected within one cell) is greater than `min_det_feats_per_cell`

I have your data already, and gave this script a quick run. I got the same exact results, except for the `nr_cells` column: 
![image](https://user-images.githubusercontent.com/59712683/212997480-4025a28a-b882-4014-aaf9-d7d9c0757631.png)

I would ensure that you have sorted and saved the data properly, as there are only three features, DLX6, TRBV28, and GPR82 , for which `nr_cells = 4`. Perhaps only the `nr_cells` column was sorted in ascending order, which would have led to the confusion here. Below is the same table, properly sorted with `nr_cells` in ascending order. It should be noted that all three of these features were found to be highly variable.

![image](https://user-images.githubusercontent.com/59712683/213008012-8aa28568-cbab-4388-8f0e-7f0db5a4d3d3.png)

Regardless, Ruben's intuition is correct. I'd venture to say that these three features passed the first filtering step, however some number of cells which contain those three features did not contain enough features to pass the second filtering step, resulting in `nr_cells = 4` for these features. 

**EDIT**
I just tested this briefly, and found that this is the case for all three features (i.e., each has `nr_cells = 5` prior to filtering):

```
F1 <- createGiottoVisiumObject(h5_visium_path = data_path_F4_h5,
				h5_tissue_positions_path = data_path_F4_tissue_positions,
				h5_image_png_path = data_path_F4_image,
				h5_json_scalefactors_path = data_path_F4_scalefactors,
                               instructions = instrs)

metadata <- pDataDT(F1)
in_tissue_barcodes <- metadata[in_tissue == 1]$cell_ID
F1 <- subsetGiotto(F1, cell_ids = in_tissue_barcodes)

F1 <- addStatistics(F1, expression_values = "raw")

print(fDataDT(F1)[][feat_ID == "DLX6"]$nr_cells) 
print(fDataDT(F1)[][feat_ID == "TRBV28"]$nr_cells)
print(fDataDT(F1)[][feat_ID == "GPR82"]$nr_cells)
```

**Comment by corecontingency** [comment]
@mattobny Thank you for your help! Yes, I can confirm that I sorted incorrectly previously. I accidentally only sorted on the nr_cells column - which meant that the other columns did not change. Correctly sorting on all columns according to nr_cells gives the below results:

![F4_metaDT_old](https://user-images.githubusercontent.com/54042889/213247121-7dd10c42-b6d9-488a-8b0b-7bdeda650bc0.png)

I think you are correct about the problem, as my code currently: 

```
F4 <- filterGiotto(gobject = F4,
                  expression_threshold = 1,
                  feat_det_in_min_cells = 5,
                  min_det_feats_per_cell = 1000,
                  expression_values = c('raw'),
                  verbose = T)
```
filters genes that are in five spots first, and then deletes spots that do not have 1000 genes. This could delete some of the five spots that DLX6, TRBV28, and GPR82 rely on.

However, there is still a problem. If I fix my code so filterGiotto filters spots first, then genes, like so:
```

F4 <- filterGiotto(gobject = F4,
                  expression_threshold = 1,
                  min_det_feats_per_cell = 1000,
                  feat_det_in_min_cells = 5,
                  expression_values = c('raw'),
                  verbose = T)
```
which should mean every gene has at least five spots (since spots are filtered first),

I get the same output result as above:

![F4_metaDT_updated](https://user-images.githubusercontent.com/54042889/213248558-5f298eb1-910a-4b47-b10a-0aecb69ef4ef.png)

I believe this means that the filterGiotto command is ignoring the order the user gives for filtering criteria.

I assume that is because the filtering order for filterGiotto is hardcoded in as you posted above?

```
filter_index_feats = rowSums_flex(expr_values >= expression_threshold) >= feat_det_in_min_cells
selected_feat_ids = names(filter_index_feats[filter_index_feats == TRUE])

filter_index_cells = colSums_flex(expr_values[filter_index_feats, ] >= expression_threshold) >= min_det_feats_per_cell
selected_cell_ids = names(filter_index_cells[filter_index_cells == TRUE])
```

**Comment by mattobny** [comment]
@corecontingency changing the order of keyword arguments will not affect any function's output, assuming that the function in question was coded with keyword arguments and only keyword arguments are re-ordered. From the  source code:

https://github.com/drieslab/Giotto/blob/98fb335e40f32f6ff094c1720ea92da5a533e54b/R/auxiliary_giotto.R#L2036-L2052

Giotto almost exclusively uses keyword arguments to streamline class checks and null catches so that functions behave accordingly at runtime. Changing the order in which these keyword arguments are provided to the function does not change the value each argument takes within the function or how the function behaves. 

Currently, `filterGiotto()` only filters data in the previously described order, features, then cells. However, a workaround could be to filter by cells first, setting `feat_det_in_min_cells = 0` and `min_det_feats_per_cell = 1000`,  then filtering again with  both criteria, `feat_det_in _min_cells = 5` and `min_det_feats_per_cell = 1000`. 

```
F4_test = F4

F4 <- addStatistics(F4, expression_values = "raw")
F4_test <- addStatistics(F4_test, expression_values = "raw")

# filter all at once
F4 <- filterGiotto(gobject = F4,
                  expression_threshold = 1,
                  feat_det_in_min_cells = 5,
                  min_det_feats_per_cell = 1000,
                  expression_values = c('raw'),
                  verbose = T)

# first filter spots, ignore features
F4_test <- filterGiotto(gobject = F4_test,
                  expression_threshold = 1,
                  feat_det_in_min_cells = 0,
                  min_det_feats_per_cell = 1000,
                  expression_values = c('raw'),
                  verbose = T)
# now filter both 
F4_test <- filterGiotto(gobject = F4_test,
                  expression_threshold = 1,
                  feat_det_in_min_cells = 5,
                  min_det_feats_per_cell = 1000,
                  expression_values = c('raw'),
                  verbose = T)

dim(fDataDT(F4))  # int [1:2] 15718 6
dim(fDataDT(F4_test)) # int [1:2] 15715 6; loss of three rows(features)

fDataDT(F4_test)[feat_ID == "DLX6"]  # Classes 'data.table' and 'data.frame':	0 obs. of  6 variables:
fDataDT(F4_test)[feat_ID == "TRBV28"] # Classes 'data.table' and 'data.frame':	0 obs. of  6 variables:
fDataDT(F4_test)[feat_ID == "GPR82"] # Classes 'data.table' and 'data.frame':	0 obs. of  6 variables:
```

It should be noted that these features (DLX6, TRBV28, GPR82) are, in fact, present in 5 cells. If `addStatistics()` is run prior to filtering, each has `nr_cells = 5`. Because one cell did not pass the criteria for inclusion in the filtering step for cells, this value drops to 4, yet the underlying truth is that these features are present in 5 cells in this dataset.

**Comment by corecontingency** [comment]
@mattobny Thank you for your help and the explanation of how the function works! Yes, using two separate `filterGiotto` commands like you suggest works.

Should this issue be closed? I am unsure if you think this behavior should be explained in the [filterGiotto command documentation](https://giottosuite.readthedocs.io/en/latest/subsections/md_rst/filterGiotto.html).

**Comment by mattobny** [comment]
Of course, and yes. I will add a brief description of this behavior to the documentation.
