### ISSUE TITLE
Where are each type cell expression profiles stored after using Giotto Suite analyzing 10X Single Cell RNA Sequencing data?

### ISSUE THREAD

**Issue by xhNorthwestern** [giotto-suite/Giotto#509]
Hi,

Recently I tried to use Giotto Suite package to analyze 10X Single Cell RNA Sequencing data. After cell type annotation, I want to compare the pathway difference between two specific cell types, for example, two subpopulations of macrophages. The pathway difference can be shown with GO, KEGG or GSEA analysis. Are the GO, KEGG or GSEA analysis included in Giotto Suite package? If not, could you tell me where each type cell expression profiles are stored? I want to export them for further analysis.

Thanks a lot!

**Comment by Ed2uiz** [comment]
Hey @xhNorthwestern 

We currently do not have any native functions for performing GSEA/GO/KEGG analysis with Giotto object. You can access the expression matrix of your Giotto object with `get_expression_values(gobject, spat_unit = 'cell', feat_type = 'rna', output = 'matrix')` to use with your preferred external pathway analysis tool. Please re-open your issues if you have any further questions, happy to help!
