### ISSUE TITLE
with R 4.0 mini_visium_test example can throw an error

### ISSUE THREAD

**Issue by vjcitn** [giotto-suite/Giotto#51]
...
 start with cluster  5 
Error in rbindlist(l, use.names, fill, idcol) : 
  Column 5 ['logFC.1_3_4_5'] of item 2 is missing in item 1. Use fill=TRUE to fill with NA (NULL for list columns), or use.names=FALSE to ignore column names.

**Comment by RubD** [comment]
Thanks for reporting this issue Vince. It turns out that it was not because of R 4.0. It seems that it was because scran (v1.16.0) changed the output of their findMarkers function. This is now fixed.
