### ISSUE TITLE
how can I start the single cell RNA seq analysis with Giotto Suite based on the differential gene expression results

### ISSUE THREAD

**Issue by xhNorthwestern** [giotto-suite/Giotto#532]
Hi,

Recently I tried to use Giotto Suite to do single cell RNA seq data analysis. I obtained the data from one published paper, but my analysis results are not consistent with the figures in the paper, especially cluster number and cluster annotation. Later I found their DGE data including four files, barcodes_anno.csv, dge.csv, gene.csv and markers.csv. Can I reproduce the paper results with these four files? Could you give me some suggestions on how I start the analysis with these files?

I really appreciate your help! Many thanks!

**Comment by RubD** [comment]
Hi @xhNorthwestern 

It's hard to provide suggestions since we don't really know how the data looks like. You can in theory use Giotto as a scRNA-seq data analysis tool, but at minimum you'll need to have gene expression matrix with raw  and/or normalized counts.

Best,
Ruben
