### ISSUE TITLE
HVFcalculate function provides very few common HVFs across multiple samples from the same tumor type

### ISSUE THREAD

**Issue by krigia** [giotto-suite/Giotto#539]
@gcyuan @RubD  @mattobny 

Hello Giotto team,

We run **HVFcalculate** using method = "**cov_groups**" for a set of 12 tumor samples. Please see below an example of the command line:

_F1_normalized_standard_6000 <- calculateHVF(gobject = F1_normalized_standard_6000, method = "cov_groups", expression_values = c("normalized"), zscore_threshold = 1.65, show_plot = F, save_plot = T, save_param = list(save_folder = "hvf", save_name = "F1_normalized_standard_6000_hvf_cov_groups"))_

For the 12 FFPE samples from the same tumor type with similar QC results and a variable number of HVFs with a range 550-1000 (median ~800 HVFs), we observed a very low number of common HVF genes (range 1-13 common HVFs for different combination of samples). Particularly for one case with two tumor samples from the same individual, we only found 11 common HVF out of ~800 HVF genes. I understand **HVFcalculate** identifies the highly variable genes by definition for each sample, but I would expect to see some similarities regarding HVFs across all or subset of samples to some extent. Have you observed similar results in your analyzed cohorts?

**Comment by mattobny** [comment]
There are various factors that could affect the number of HVFs within and across samples, not limited to: QC measures, differing local tumor composition, or technical issues. As we do not have the bandwidth to provide specific analytical advice in scenarios like this, I can supply you with resources that could provide some insight:
- [Evaluation of tools for HVG Discovery from scRNAseq data](https://pubmed.ncbi.nlm.nih.gov/29481632/)
- [Feature Selections](http://bioconductor.org/books/3.15/OSCA.basic/feature-selection.html)
