### ISSUE TITLE
Error in setnames(x, value) : Can't assign 6 names to a 5 column data.table

### ISSUE THREAD

**Issue by hndyilm** [giotto-suite/Giotto#540]
Hi everyone,

I analyzed Visium spatial transcriptomics data using giotto.
When using "createGiottoVisiumObject", it returns "Error in setnames(x, value) : Can't assign 6 names to a 5 column data.table"
Does anyone has any idea about that? 

Thanks in advance for your help!!
Hande

**Comment by mattobny** [comment]
@hndyilm Hello, can you provide the full command you ran along with the full error message? Also, can you run `sessionInfo()` after loading Giotto and let us know what version of Giotto are you running?
