### ISSUE TITLE
problem with devtools::install_github("drieslab/Giotto@suite")

### ISSUE THREAD

**Issue by hndyilm** [giotto-suite/Giotto#615]
I have R and Giotto installed on my laptop. When I try to install another package called "GiottoData" and "Giotto@suite" using any of the below three methods: I get this error:

devtools::install_github("drieslab/Giotto@suite")

Calls: <Anonymous> ... <Anonymous> -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘Giotto’

* removing ‘/home/leinehome/.conda/envs/g_spatial/lib/R/library/Giotto’
* restoring previous ‘/home/leinehome/.conda/envs/g_spatial/lib/R/library/Giotto’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpoaWtNS/filed90a29a1b870/Giotto_3.2.tar.gz’ had non-zero exit status

Is there any recommodation about that? Thank you in advance

**Comment by mattobny** [comment]
Hello @hndyilm, 

Can you please provide the versions of Giotto and R that you currently have installed? Calling `sessionInfo()` after loading Giotto will display the version if it is not already shown when loaded.

There may be some sort of conflict with the installation since you already have Giotto installed.

**Comment by hndyilm** [comment]
Hello @mattobny 

Giotto_1.1.2
R version 4.2.2

Thanks

**Comment by mattobny** [comment]
@hndyilm Thank you!

I assume that you would like to upgrade from Giotto to Giotto Suite. Note that this will overwrite the previous version of Giotto, i.e. that which you currently have installed. To upgrade, please open a brand new, fresh, R session and retry running the command from before, but now with an added argument:

`devtools::install_github("drieslab/Giotto@suite", force = T)`

I verified that this works; I created a new library directory on my machine to mimic a fresh installation without affecting my development installation, and successfully installed from the ground up. 

If you run into this, or any similar issue, again, it may be the result of some packages still being attached or loaded to the R session. If using R Studio, click `Session > New Session` on the toolbar, then retry this workflow. Please follow up with any further developments.

**Comment by hndyilm** [comment]
Hello @mattobny 
Unfortunately,  It is still not working. It says " 
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/leinehome/.conda/envs/gs_spatial/lib/R/library/terra/libs/terra.so':
  libproj.so.15: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... <Anonymous> -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘Giotto’
* removing ‘/home/leinehome/.conda/envs/gs_spatial/lib/R/library/Giotto’
* restoring previous ‘/home/leinehome/.conda/envs/gs_spatial/lib/R/library/Giotto’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpRLVAgN/file462ac27c92/Giotto_3.2.tar.gz’ had non-zero exit status "

Thank you!

**Comment by RubD** [comment]
This might be a terra issue. Can you load and work with terra in your conda environment? Might try deleting and re-installing terra first.

**Comment by hndyilm** [comment]
Thanks. I will try to install it
