### ISSUE TITLE
while running HMRF in the docker image: Permission denied: '/tmp/edges.txt'

### ISSUE THREAD

**Issue by vipulsinghal02** [giotto-suite/Giotto#62]
I downloaded the docker image and when running the doHMRF function, I get the following error: 

> Traceback (most recent call last):
>   File "/usr/local/lib/R/site-library/Giotto/python/reader.py", line 194, in <module>
>     fw = open(edge_file, "w")
> PermissionError: [Errno 13] Permission denied: '/tmp/edges.txt'

When I look at the permissions of the offending file, I find that it belongs to root, and but there are read rights (but I guess no execute rights..) available to all groups: 

> dean@xxxxxxxxxx:/tmp$ ls -la
> total 228
> drwxrwxrwt 1 root root  4096 Jul 15 09:10 .
> drwxr-xr-x 1 root root  4096 Jul 15 01:22 ..
> drwx------ 4 dean dean  4096 Apr 17 22:28 RtmpEFoBv3
> drwx------ 2 dean dean  4096 Feb  1 11:09 RtmpHgq2P0
> drwx------ 2 dean dean  4096 Jul 15 09:37 RtmpRemm4l
> drwx------ 2 dean dean  4096 Feb  1 11:13 Rtmpo1QRXC
> drwx------ 2 dean dean  4096 Feb  1 11:05 RtmppUE0AF
> -rw-r--r-- 1 root root 79385 Jun 27  2019 adjacent.txt
> -rw-r--r-- 1 root root 10072 Jun 27  2019 blocks.txt
> -rw-r--r-- 1 root root 33336 Jun 27  2019 edges.txt

So how should I try to fix the issue here? If I try to sudo chmod it, it asks for dean's password. I don't have this password (I tied "dean"; does not work)

Thanks!
Vipul

**Comment by RubD** [comment]
Hi Vipul, 
Thank you for letting us know. We'll look into it and try to fix it asap.
Ruben

**Comment by vipulsinghal02** [comment]
Thank you for the quick response. Looking forward to the fix!

**Comment by bernard2012** [comment]
Thanks for testing the docker image. 
Very informative that you provide the "ls -ltr /tmp" listing. 
The solution is simple. When you login to docker, root is the default user (for example I see "root@dd44d817d0c1:/#" upon entering docker run -it ... command).
At the command prompt ("root@dd44d817d0c1:/#"), you could try to remove the three files as root "rm -rf /tmp/edges.txt /tmp/adjacent.txt /tmp/blocks.txt". Then use Giotto in Rstudio again, and repeat doHMRF analysis. It should work. 

The three remnant files in /tmp are from my previous attempt of running Giotto as root, and forgot to delete them in /tmp afterward. 
Lesson learned: if you run your analysis as root, be sure to clean up /tmp afterward (as root). If you use Rstudio, then it will run as the user "dean".  Usually it is not recommended to run analysis as user root.
