### ISSUE TITLE
Tutorial not updated?

### ISSUE THREAD

**Issue by onahman** [giotto-suite/Giotto#63]
Hi,
I am trying to work on the tutorial here: http://spatialgiotto.rc.fas.harvard.edu/giotto.visium.brain.html
I was able to finish all the installation successfully, but very strangely, I am unable to run some of Giotto functions.
for example: createGiottoInstructions, get10Xmatrix are not found.
But other seem to be recognized like createGiottoObject.
The functions I mentions that were not found, were also not listed here: Documentation for package ‘Giotto’ version 0.1.0.
What makes me think you have might have made changes in the package without updating the tutorials. 
Right now I am unable to run the tutorial - your help in solving this problem would be appreciated.

Ornit

**Comment by RubD** [comment]
Hi Ornit,

Can you let me know how you installed Giotto? Did you use docker or the native installation? The current version of Giotto is 0.3.6 . So I would advise you to first install the newest version. 0.1.0 is quite old and does not work anymore with the current dataset examples.

The examples on this site https://rubd.github.io/Giotto_site/ are currently also more up-to-date.

Ruben

**Comment by onahman** [comment]
Hi,
Thank you very much for the fast reply!
I used the naive installation.
As is listed here:

Native InstallationGiotto consists of two modules: analyzer and viewer. The
requirements of Giotto installation are:

   - R (at least 3.5.1)
   - Python (at least 3.0)
   - Java 1.6+
   - Unix / Linux environment

1. Native install on Ubuntu LinuxOnce you have installed R, go into R, and
install the following

library(remotes)# to install the latest stable version (advised)
remotes::install_github("RubD/Giotto")# to install a specific release
version (example)
remotes::install_github("RubD/Giotto@v0.1.0")# install HMRF required by Giotto
install.packages("devtools")
library(devtools)
install_bitbucket("qzhudfci/smfishhmrf-r", ref="default")

**Comment by RubD** [comment]
You just have to run the first two lines:
- library(remotes)
- remotes::install_github("RubD/Giotto")

That will install everything you need to run the R package.

If you run this at the end: remotes::install_github("RubD/Giotto@v0.1.0"), then that will install a specific version (0.1.0) of Giotto. And 0.1.0 is an old version.

For more up-to-date installation instructions and potential problems have a look [here](https://rubd.github.io/Giotto_site/).

Hopefully this will fix everything.
Ruben

**Comment by onahman** [comment]
I actually did what you suggested before I opened the issue.
I will try to remove the package installation and re-install without that
line.
I believe it will solve it.

Thanks again!
Ornit
