### ISSUE TITLE
Cannot Run RunPCA on R

### ISSUE THREAD

**Issue by zhli12** [giotto-suite/Giotto#657]
I was running the script from [https://rubd.github.io/Giotto_site/articles/mouse_seqFISH_cortex_200914.html] and I was able to run the script chunk by chunk until PCA. My R session crushed whenever I tried to run the `RunPCA()` function. I installed the Giotto package via the `remotes::install_github("drieslab/Giotto@suite")`. 

**System Information**

My system is MacOS 12.5, R version is 4.1.1, Giotto package version is 3.3.0. The function `checkGiottoEnvironment()` returns the virtual environment /Users/username/Library/r-miniconda/envs/giotto_env/bin/pythonw. I activated the environment using `conda activate /Users/username/Library/r-miniconda/envs/giotto_env`, but i was not able to run `python -V`, which returns NameError: name 'python' is not defined.

**Comment by zhli12** [comment]
Update: I was actually able to check the python environment within the Giotto env, which is Python 3.10.2.

**Comment by mattobny** [comment]
Hello @zhli12, unfortunately, that article is out-of-date and relevant only to the `master` branch of Giotto (a release associated with [our previous work](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02286-2)). Please see [here](https://giottosuite.readthedocs.io/en/latest/) for our new, up-to-date website, and [here](https://giottosuite.readthedocs.io/en/latest/datasets.html) for the most up-to-date dataset tutorials. If your problem persists when running these tutorials, please let us know.

**Comment by zhli12** [comment]
Thanks for your help! The issue was solved after I updated by R version and the Giotto package.

> Hello @zhli12, unfortunately, that article is out-of-date and relevant only to the `master` branch of Giotto (a release associated with [our previous work](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02286-2)). Please see [here](https://giottosuite.readthedocs.io/en/latest/) for our new, up-to-date website, and [here](https://giottosuite.readthedocs.io/en/latest/datasets.html) for the most up-to-date dataset tutorials. If your problem persists when running these tutorials, please let us know.
