### ISSUE TITLE
`setExpression` function overwrites existing metadata

### ISSUE THREAD

**Issue by jmodlis** [giotto-suite/Giotto#682]
Hello!

Thank you for the massive effort you have put into this package. I'm working with some Nanostring CosMx data and have happened upon the bug described below.

Thanks,
Jen

**When calling `setExpression`, the cell metadata is always overwritten.**

Here is the relevant portion of the function `setExpression`, which is not in an if/else block. 

```  
    cm_avail = is.null(list_cell_metadata(gobject = gobject, 
        spat_unit = spat_unit, feat_type = feat_type))
    fm_avail = is.null(list_feat_metadata(gobject = gobject, 
        spat_unit = spat_unit, feat_type = feat_type))
    if (!spatID_exist) 
        gobject = set_cell_id(gobject = gobject, spat_unit = spat_unit, 
            cell_IDs = "initialize", set_defaults = FALSE)
    if (!featID_exist) 
        gobject = set_feat_id(gobject = gobject, feat_type = feat_type, 
            feat_IDs = "initialize", set_defaults = FALSE)
    if (!is.null(cm_avail)) 
        gobject = set_cell_metadata(gobject = gobject, metadata = "initialize", 
            spat_unit = spat_unit, feat_type = feat_type, provenance = if (is.null(provenance)) 
                spat_unit
            else provenance, verbose = FALSE, set_defaults = FALSE)
    if (!is.null(fm_avail)) 
        gobject = set_feature_metadata(gobject = gobject, metadata = "initialize", 
            spat_unit = spat_unit, feat_type = feat_type, provenance = if (is.null(provenance)) 
                spat_unit
            else provenance, verbose = FALSE, set_defaults = FALSE)
    return(gobject)
```
I believe running `cm_avail = is.null(list_cell_metadata(gobject = gobject, 
                                                spat_unit = spat_unit, 
                                                 feat_type = feat_type))`  will return `TRUE` or `FALSE` for parameter `cm_avail`. I say I believe because although I can view the help for `list_cell_metadata` function, I cannot run the function from the console, either on it's own or as `Giotto::list_cell_metadata`

Running `!is.null(cm_avail)`  always returns `TRUE` and initializes cell_metadata (thus overwriting existing data) regardless of whether `cm_avail` is `TRUE` or `FALSE` (neither is null).

The same thing happens with feature metadata.

**Potential solution**
Running `Giotto::set_expression_values` instead of `Giotto::setExpression` does not overwrite the cell metadata. However, it does supply a warning that the function is deprecated.
```
Warning: 'Giotto::set_expression_values' is deprecated.
Use 'setExpression' instead.
See help("Deprecated")
```

**System Information**
```                   
platform       x86_64-conda-linux-gnu      
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          2.3                         
year           2023                        
month          03                          
day            15                          
svn rev        83980                       
language       R                           
version.string R version 4.2.3 (2023-03-15)
nickname       Shortstop Beagle      

> packageVersion("Giotto")
[1] ‘3.2’

Python 3.11.2

```

**Comment by jmodlis** [comment]
The other obvious potential solution is to just change
` cm_avail = is.null(list_cell_metadata(gobject = gobject, 
        spat_unit = spat_unit, feat_type = feat_type))`
to 
` cm_avail = list_cell_metadata(gobject = gobject, 
        spat_unit = spat_unit, feat_type = feat_type)`

And remove the exclamation mark here `if (!is.null(cm_avail)) `, then do the same for `fm_avail`

**Comment by mattobny** [comment]
Hello @jmodlis, 

This issue was fixed on the previous version bump to `v3.3`. According to your system information, the version you have installed is `v3.2`. Please update Giotto by reinstalling the R package, i.e. `devtools::install_github("drieslab/Giotto")`. This should solve your issue; please let us know if we can help!

**Comment by jmodlis** [comment]
Thank you!  This update solved the issue for me (along with some problems I was having with joining Giotto objects). It just took a while to confirm because I had to create an entirely new conda environment.

**Comment by mattobny** [comment]
Glad to hear this is solved! Feel free to post a new issue should you need further assistance.
