### ISSUE TITLE
Giotto & Scanpy / Python 

### ISSUE THREAD

**Issue by romain-lopez** [giotto-suite/Giotto#69]
I am trying to load an Anndata containing my spatial dataset. I usually do this in R using reticulate. 

library(Giotto)
instrs = createGiottoInstructions(python_path = "anaconda3/envs/myenv")
library(tidyverse)
library(reticulate)
library(Matrix)
sc <- import("scanpy")
pd <- import("pandas")

However, both python import lines fail in this example on my machine. I see that it comes from the fact that Giotto uses also reticulate and it seems to create conflicts. I looked into your codebase and I tried removing the import and adding reticulate:: as a suffix, without success. 

Any idea on how I could do that? It would be extremely handy.

**Comment by romain-lopez** [comment]
This is an unrelated problem with my path! I might reopen this thread if I encounter other problems. Also, let me know if this is an interesting piece of code that you would me to post somewhere or send. It might be useful to some users!

**Comment by RubD** [comment]
Ok, good you figured it out. Improving the interoperability of Giotto is high on the list, so if you have something that works for Anndata then I would be happy to give it a try and incorporate it in the development version, which we hope to release soon.
Thanks!

**Comment by romain-lopez** [comment]
Update on this, it was finally super quick. Here is my code

```
library(Giotto)
instrs = createGiottoInstructions(python_path = "/home/ubuntu/anaconda3/envs/myenv/bin/python")
library(tidyverse)
library(reticulate)
library(Matrix)
sc <- import("scanpy")
pd <- import("pandas")
adata <- sc$read("my.h5ad")
## Load count data 
exprs <- t(adata$X)
colnames(exprs) <- adata$obs_names$to_list()
rownames(exprs) <- adata$var_names$to_list()

spatial <- as.data.frame(adata$obsm["spatial"])
colnames(spatial) <- c("X", "Y")
row.names(spatial) <- colnames(exprs)

# Obs
obs <- adata$obs
# Metadata
metadata <- obs[, c("total_counts", "pct_counts_mt")]

visium_LN <- createGiottoObject(raw_exprs = exprs,
                                   spatial_locs = spatial,
                                   instructions = instrs,
                                   cell_metadata = metadata)
```

**Comment by RubD** [comment]
Thanks! I can probably turn that into a simple wrapper. I might ask you some more specific questions via email.
