### ISSUE TITLE
When the python_path argument is supplied, Giotto still reverts to the default system python path

### ISSUE THREAD

**Issue by cgaray-p4** [giotto-suite/Giotto#705]
**Describe the Error**

I have installed the Giotto dependencies into a non-default (non-conda) installation of Python. Even after setting the `python_path` argument to Giotto functions, Giotto still tries to use the default system Python path.
...

**Error Message**

<details>

```r
> Giotto::loadGiotto(
  path_to_folder = 'giotto_data',
  python_path = "/opt/python/3.9.13/bin/python"
)

 external python path provided and will be used 

no external python path or giotto environment was specified, will check if a
 default python path is available
Warning: Previous request to `use_python("/opt/python/3.9.13/bin/python", required = TRUE)` will be ignored. It is superseded by request to `use_python("/usr/bin/python3")
A default python path was found: /usr/bin/python3 and will be used
```
</details>

**To Reproduce**

Steps to reproduce the behavior, i.e.:
1. Install Python to a non-default path on the system
2. Make a call to a Giotto function and set the `python_path` argument

**Expected behavior**

The `python_path` specified by the user is used.

**System Information**

Please replace the following according to your machine:
 - OS: RHEL8
 - Version [e.g. 4.0.1]
    - R [4.2.1]
    - Giotto [latest commit of the suite branch]
    - Python [3.9.13]

**Additional context**

When the `python_path` argument is supplied, this is recognized and an appropriate call to `reticulate::use_python` is made here: https://github.com/drieslab/Giotto/blob/22b5c97ad3a83b47214cd049bbad2c6937c36e0e/R/python_environment.R#L427. However, this call is superseded when we reach this block: https://github.com/drieslab/Giotto/blob/22b5c97ad3a83b47214cd049bbad2c6937c36e0e/R/python_environment.R#L457.

**Comment by zbjbiubiubiu** [comment]
I encountered a similar problem. I specified the python environment in checkGiottoEnvironment, but the python environment I specified was not used later.  Am I using it wrong? Is there any new progress?

# Specify Python environment
![image](https://github.com/drieslab/Giotto/assets/85217904/2737c729-ae9d-41a0-a322-2b3a1404ae3d)

# The following message still says that the environment I specified is not used.
![image](https://github.com/drieslab/Giotto/assets/85217904/21dc5ccf-4cc5-48ee-a313-fa9bce47d680)

**Comment by zbjbiubiubiu** [comment]
> I encountered a similar problem. I specified the python environment in checkGiottoEnvironment, but the python environment I specified was not used later. Am I using it wrong? Is there any new progress?
> 
> # Specify Python environment
> ![image](https://private-user-images.githubusercontent.com/85217904/333071731-2737c729-ae9d-41a0-a322-2b3a1404ae3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDc3NDcsIm5iZiI6MTcxNjQ0NzQ0NywicGF0aCI6Ii84NTIxNzkwNC8zMzMwNzE3MzEtMjczN2M3MjktYWU5ZC00MWEwLWEzMjItMmIzYTE0MDRhZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA2NTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZWVjYzJjMDY4M2ExNTZmNjEyMDliNTg0NjA1NTFmMTI0OGI0YjBjOWY5ZTAwYjlmMjExM2ZlMDZkZjUwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dhVZO693kgTydu6SjSRGZkUfua1-yFUYEHuQx-4ZOtM)
> 
> # The following message still says that the environment I specified is not used.
> ![image](https://private-user-images.githubusercontent.com/85217904/333072025-21dc5ccf-4cc5-48ee-a313-fa9bce47d680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDc3NDcsIm5iZiI6MTcxNjQ0NzQ0NywicGF0aCI6Ii84NTIxNzkwNC8zMzMwNzIwMjUtMjFkYzVjY2YtNGNjNS00OGVlLWEzMTMtZmE5YmNlNDdkNjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA2NTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMTYwZmRjNjIyNDdkOGI5ZDkwMmY3ZTk1OTU3OTA5NDI2M2Q4ZWFiZDZkOTBjN2ZkYjhjODMyYmU4YWFhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ppIFWF5PVhNARaligmbXg5yYr0nwNYlmLdFR3BgXX8)

I used
Sys.setenv(RETICULATE_PYTHON = "/hwfssz1/ST_HEALTH/P20Z10200N0170/zhengbingjie/Anaconda3/envs/giotto_env/bin/python")
library(reticulate)
to solve this problem. Now I can use the python environment I specified.
