### ISSUE TITLE
Warn that `python.app` is only for OSX in pip instructions as well

### ISSUE THREAD

**Issue by eturkes** [giotto-suite/Giotto#71]
Hi,

I was following your Python manual installation instructions (https://rubd.github.io/Giotto_site/articles/installation_issues.html#python-manual-installation) using the pip installation and the install kept failing at `python.app`. It took me a while before I noticed your comment in the Conda install section that says "(!!only for OSX!!)". So I suggest also putting that comment in a place where pip users will see it.

Thank you for the really nice package otherwise!

**Comment by RubD** [comment]
Hi,

Thanks for the feedback! I agree and I was already afraid that something like this might happen. We are close to releasing the development version, which has a lot of updates, additional documentation and bug/error fixes. I'll also include some additional information about the python.app module for pip users in the new release.
FYI, Giotto can also install everything automatically in a small miniconda environment, although I understand that many users prefer to use their own python environment.

Have a great week,
Ruben
