### ISSUE TITLE
tutorial question about  osmFISH Dataset

### ISSUE THREAD

**Issue by caiquanyou** [giotto-suite/Giotto#72]
Hello ,
I run this tutorial `http://spatialgiotto.rc.fas.harvard.edu/giotto.osmFISH.html`
and sometthing wrong in this line `osm_locs = osm_locs[rownames(osm_locs) %in% colnames(osm_exprs),]`
it makes the osm-locs became 0 obs 
and the next  command `osm_test <- normalizeGiotto(gobject = osm_test)`
can not find the object osm_test
is this tutorial code wrong ?
wait for reply
thanks
best regards
cqy

**Comment by caiquanyou** [comment]
and another one http://spatialgiotto.rc.fas.harvard.edu/giotto.slideseq.html
the data loading,cannot find these data in the link
expr = read.table(paste0(data_folder,'/','l1.cerebellum.txt'))
cell_names = fread(paste0(data_folder,'/','l1.cerebellum.cells.2.txt'), header = F)
gene_names = fread(paste0(data_folder,'/','l1.cerebellum.genes.txt'), header = F)

**Comment by RubD** [comment]
Hi,

Thanks for the feedback. We are aware that there are some errors in the code. In a few days we will have a new version of Giotto with updated examples available. This will make it easier to use Giotto and reproduce our results.

Best,
Ruben

**Comment by caiquanyou** [comment]
hi, Ruben
thanks for your reply
could you please send me the download link of the correct tutorial data
best&nbsp;
cqy



---Original---

**Comment by caiquanyou** [comment]
hi,Ruben
how to use spatial_deconvolution as I can not found in the tutorial 
best
cqy

**Comment by RubD** [comment]
Hi Cqy,
Sorry for my delayed reply.

**osmFISH question:**
If you install the development version: remotes::install_github("RubD/Giotto@development"), then you can follow this osmFISH tutorial https://rubd.github.io/Giotto_site/articles/mouse_osmFISH_SScortex_200915.html  
It also has a command to download the dataset, so you can just copy the commands. Let me know if it works or you have additional questions.

**deconvolution question:**
This function is actually not live yet, but we're working on providing an example and it will be up on the websites soon.

Thanks,
Ruben

**Comment by caiquanyou** [comment]
Thanks! I will try it !




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RubD/Giotto"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 晚上11:37
收件人:&nbsp;"RubD/Giotto"<Giotto@noreply.github.com&gt;;
抄送:&nbsp;"xianmao"<951463554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RubD/Giotto] tutorial question about  osmFISH Dataset (#72)





 
Hi Cqy,
 Sorry for my delayed reply.
 
osmFISH question:
 If you install the development version: remotes::install_github("RubD/Giotto@development"), then you can follow this osmFISH tutorial https://rubd.github.io/Giotto_site/articles/mouse_osmFISH_SScortex_200915.html
 It also has a command to download the dataset, so you can just copy the commands. Let me know if it works or you have additional questions.
 
deconvolution question:
 This function is actually not live yet, but we're working on providing an example and it will be up on the websites soon.
 
Thanks,
 Ruben
