### ISSUE TITLE
Issue with heatmap

### ISSUE THREAD

**Issue by shakesber89** [giotto-suite/Giotto#747]
Hi Guys I am using Single cell pipeline to plot some data. I am using osm fish pipelein. Its working good. I am creating a Heatmap shown below. 

![image](https://github.com/drieslab/Giotto/assets/20415983/02500d45-0875-431e-9d9b-5babff44e972)

Now I want to order the Feat in the Y axis in an ascending or descensing order. Can you pls help. 

I ma using plotMetaDataHeatmap .

The pData Look like
![image](https://github.com/drieslab/Giotto/assets/20415983/d9f828d6-9c11-469a-8150-e469bd61898a)

The fdata looks like

![image](https://github.com/drieslab/Giotto/assets/20415983/b4541dae-6b3b-4e22-a7f0-1026556b8278)

Thanks
Jesu

**Comment by RubD** [comment]
Hi @shakesber89 You can use the parameter `custom_feat_order` and provide the order of the features (e.g. genes) as a vector.

**Comment by shakesber89** [comment]
Thanks. It worked.
