### ISSUE TITLE
Error in generating visium object in Giotto in R studio : Object 'visium_png' not found

### ISSUE THREAD

**Issue by hndyilm** [giotto-suite/Giotto#807]
Hello everyone,

While generating visium object in Giotto in R studio, I get an error:

instrs = createGiottoInstructions( python_path = 'C:/Users/AppData/Local/r-miniconda/envs/giotto_env/python.exe',
                                   save_plot = TRUE,
                                   show_plot = FALSE)

data_path = 'C:/Users/Desktop/outs/'

visium_SARC = createGiottoVisiumObject(visium_dir = data_path, expr_data = 'raw',
                                       h5_tissue_positions_path = 'C:/Users/Desktop/outs/spatial/tissue_positions.csv',
                                       h5_image_png_path = 'C:/Users/Desktop/outs/spatial/',
                                       png_name = 'tissue_hires_image.png',
                                       do_manual_adj = FALSE,
                                       gene_column_index = 2, instructions = instrs)

ERROR: Error in createGiottoVisiumObject(visium_dir = data_path, expr_data = "raw", : 
  Object 'visium_png' not found

Any help would be appreciated. Thanks.

**Comment by RubD** [comment]
Can you share which version of Giotto you're using? I'd suggest to use the latest version and carefully read the help page for the `createGiottoVisiumObject`. You can start from a Visium directory or a .h5 file, but your parameters seem to suggest a combination of both.

We realize that this is a bit confusing and we will likely separate the .h5 and directory workflows in the future.

**Comment by hndyilm** [comment]
I am using the last version of Giotto (3.3.0). Thanks.
