### ISSUE TITLE
H&E-stain does not align with capturing area 

### ISSUE THREAD

**Issue by RolantusdataExp** [giotto-suite/Giotto#808]
Hi Giotto devs, 
Thanks for a great tool! I am currently struggling with an issue when running spatPlot2D, code: 
spatPlot2D(gobject = visium_liver, cell_color = 'in_tissue', point_size = 2,
           cell_color_code = c('0' = 'lightgrey', '1' = 'blue'),
           show_image = T, image_name = 'image')

When getting the output image, it seems like the H&E staining and the capturing area does not align. As you can see here: 
<img width="1309" alt="Skærmbillede 2023-11-24 kl  10 44 27" src="https://github.com/drieslab/Giotto/assets/75480608/19e4aa0e-74c3-455a-9180-d2f807254122">

It is quite clear to me that it seems like a scaling issue. Do you know how to fix it? 

Best regards, 
Peter

**Comment by RolantusdataExp** [comment]
Figured it out - closing issue

**Comment by sunjiahe-hub** [comment]
> Figured it out - closing issue

I have the sam question , how do it?

**Comment by sunjiahe-hub** [comment]
I have the same question , how do it?

**Comment by Jiahe-Sun** [comment]
I have the same question , how to do it?

**Comment by josschavezf** [comment]
@sunjiahe-hub this tutorial explains how to do it https://drieslab.github.io/Giotto_website/articles/image_alignment.html 

I hope it helps

**Comment by jiajic** [comment]
Just wanted to add on:
We recently swapped over image representation for Visium objects to `giottoLargeImages` which have not been fully detailed in the image alignment tutorial yet.

You can manipulate those images manually using
`GiottoClass::ext(gobject@largeImages[[image_name]]) <- GiottoClass::ext(xmin, xmax, ymin, ymax) `
