### ISSUE TITLE
CreateGiottoVisiumObject expr_data file

### ISSUE THREAD

**Issue by jnmark** [giotto-suite/Giotto#81]
Hello,

I have a question regarding the expr_data file - as I understand, when you enter 'filter' or 'raw' here, Giotto automatically looks for the _feature_bc_matrix folder that contains the barcodes, features, and matrix files. Is there a way to specify or read directly from the .h5 file instead? It seems we don't have the other files saved and do not have access to CellRanger tools. Thanks for the help!

**Comment by RubD** [comment]
Hi,

createGiottoVisiumObject expects you to give the path to the visium folder, which should have the following structure:

visium_folder:
    - filtered_feature_bc_matrix
    - raw_feature_bc_matrix
    - spatial

Depending on whether you want to start from the raw or already pre-filtered data you can then either select 'raw' or 'filter' for the **expr_data** parameter. 

Currently, we don't support reading directly from the .h5 file. I'll take a look and see how easy it would be to add this feature.

R

**Comment by RubD** [comment]
I've looked into it and I have updated the **createGiottoVisiumObject**. It can now also accept .h5 files directly. This should make it easier to create a Giotto object from Visium data. You'll need to reinstall Giotto (needs v1.0.3).

### input paths
```{r}
h5_file ='/your/path/Data/Visium_data/Breast_cancer_A/V1_Breast_Cancer_Block_A_Section_1_filtered_feature_bc_matrix.h5'
loc_file ='/your/path/Data/Visium_data/Breast_cancer_A/spatial/tissue_positions_list.csv'
png_file ='/your/path/Data/Visium_data/Breast_cancer_A/spatial/tissue_lowres_image.png'
```

### command
```{r}
giotto_visium = createGiottoVisiumObject(h5_visium_path = h5_file, 
 h5_tissue_positions_path = loc_file, 
 h5_image_png_path = png_file)
```
Please let me know if it works or if you encounter any problems. Thanks

**Comment by RubD** [comment]
I made a typo yesterday, which led to an error, but that's fixed now.

**Comment by jnmark** [comment]
Hello,

Thank you so much for fixing this and I apologize for not getting back to this sooner to test it. I tried re-installing Giotto v1.0.3 using remotes::install_github("RubD/Giotto@v1.0.3") but I get a download error: 

Downloading GitHub repo RubD/Giotto@v1.0.3
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/RubD/Giotto/tarball/v1.0.3'

Is there another way?

**Comment by RubD** [comment]
Sorry, that was my fault. The current master version already had this feature, so you can just follow the normal installation instructions. I forgot to actually 'release' v1.0.3. I did that now, so also your previous command should work, but v1.0.3 is the same as the current version.

**Comment by jnmark** [comment]
Thank you so much! The createGiottoVisiumObject wasn't able to read the h5 file earlier despite re-installing, so I figured I needed to explicitly install v1.0.3. However, it's all fixed now, thanks so much for the prompt help always. Looking forward to test all the new functionalities that have been added since I last ran the spatial vignette.
