### ISSUE TITLE
Interactive Selection in Giotto

### ISSUE THREAD

**Issue by hndyilm** [giotto-suite/Giotto#810]
Hello everyone,

I am doing interactive selection in Giotto with R studio. 

my_polygon_coordinates <- plotInteractivePolygons(my_spatPlot)
                                     

my_giotto_polygons <- createGiottoPolygonsFromDfr(my_polygon_coordinates, name = 'selections')

visium_data <- addGiottoPolygons(gobject = visium_data,
                                  gpolygons = list(my_giotto_polygons))

visium_data <- addPolygonCells(visium_data,
                                polygon_name = 'selections') # NOT WORKS

# I am getting such an error in this step: These column names were already used: in_tissue array_row array_col nr_feats
 perc_feats total_expr leiden_clus
 and will be overwritten

visium_data <- addPolygonCells(visium_data,
                                polygon_name = 'selections',
                                na.label = 'No Polygon')

getCellsFromPolygon(visium_data,
                    polygon_name = 'selections',
                    polygons = 'polygon 1')

getCellsFromPolygon(visium_data,
                    polygon_name = 'selections')

I DID NOT  GET ANY CELL IDs AND "POLYGON 1". ALL CELL IDs ARE "NO POLYGON"

Any help would be appreciated.

**Comment by josschavezf** [comment]
@hndyilm could you please share with me the table 'my_polygon_coordinates' and your Giotto object? You can upload them here or send them to my email joselynchavezf@gmail.com

**Comment by hndyilm** [comment]
@josschavezf I have sent them to your email. Thank you.
