### ISSUE TITLE
could not find function "." 

### ISSUE THREAD

**Issue by xiangmingcai** [giotto-suite/Giotto#812]
Hi, 
I try to use exportGiottoViewer and had this error:

```
> exportGiottoViewer(gobject = visium_kidney,
+                    output_directory = viewer_folder,
+                    # factor_annotations = c('in_tissue',
+                    #                        'leiden_clus'),
+                    # numeric_annotations = c('nr_feats'),
+                    # dim_reductions = c('tsne', 'umap'),
+                    # dim_reduction_names = c('tsne', 'umap'),
+                    # expression_values = 'scaled',
+                    # expression_rounding = 2,
+                    overwrite_dir = T)

 output directory already exists, files will be overwritten 

 write cell and gene IDs 
write physical centroid locations
Error in h(simpleError(msg, call)) : 
  在为'['函数选择方法时评估'j'参数出了错: could not find function "." 

```

I checked the code and it seems like this row in this function exportGiottoViewer  is wrong:

`spatial_location = spatial_location[, .(sdimx, sdimy)]`

Am I right?

Thanks!

**Comment by josschavezf** [comment]
Hi @xiangmingcai unfortunately the Giotto viewer is not supported anymore, but we are currently working on the integration of visualization tools through SpatialData, napary, and vitessceR. Keep an eye on our coming updates. When we have those integrations ready, we will add a tutorial to our website http://giottosuite.com/
