### ISSUE TITLE
New tutorials issue

### ISSUE THREAD

**Issue by rbutleriii** [giotto-suite/Giotto#838]
**Describe the Error**
In the tutorials the `2. Start Giotto` script will not work, because R will prompt to ask for upgrades, resulting in the `library(Giotto)` and `library(GiottoData)` commands being lost if they weren't already installed.  
...

**Error Message**

blah blah `Error function checkGiottoEnvironment not found`

**To Reproduce**

Run in a version of R with no Giotto installed

**Expected behavior**

Modifying the code with `upgrade="never"` or `upgrade=F` should do the trick
```r
# Ensure Giotto Suite is installed
if(!"Giotto" %in% installed.packages()) {
  devtools::install_github("drieslab/Giotto@suite", upgrade=F)
}
library(Giotto)

# Ensure Giotto Data is installed
if(!"GiottoData" %in% installed.packages()) {
  devtools::install_github("drieslab/GiottoData", upgrade=F)
}
library(GiottoData)

# Ensure the Python environment for Giotto has been installed
genv_exists = checkGiottoEnvironment()
if(!genv_exists){
  # The following command need only be run once to install the Giotto environment
  installGiottoEnvironment()
}
```

**System Information**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Version [e.g. 4.0.1]
    - R == 4.2.2
    - Giotto == 4.0.0
    - Python ==3.10.2

**Comment by RubD** [comment]
Thanks @rbutleriii for the feedback. We're working on a new website and we will make sure to fix this problem.

**Comment by josschavezf** [comment]
Hi @rbutleriii to follow up with this issue, are you still having this problem with the most recent version of Giotto 4.0.2? I'm trying to replicate the installation error but everything seems to work now. Please, let me know if this was solved.

**Comment by rbutleriii** [comment]
Looks good with the new tutorials, thanks!
