### ISSUE TITLE
silhouetteRankTest - no such file or directory "km_centroid.txt"

### ISSUE THREAD

**Issue by jenniferfranks** [giotto-suite/Giotto#84]
In trying to run the Visium brain tutorial, I run into an issue in Part 10. The function silhouetteRankTest errors out with the message below. In looking through the folders, I cannot locate the txt file, so it seems there is an issue in creating it. 

sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `cd '/Giotto/silhouetteRank_output//result_5000_0.95_0.100' && Rscript do_kmeans.R gene.freq.good.txt 1 1 1000 km_centroid.txt km_label.txt'
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  FileNotFoundError: [Errno 2] No such file or directory: "/Giotto/silhouetteRank_output//result_5000_0.95_0.100/km_centroid.txt"

**Comment by RubD** [comment]
This function is still in beta. We'll look into the issue, maybe @bernard2012 knows what happened here? In the meantime you could also try out [silhouetteRank](https://rubd.github.io/Giotto_site/reference/silhouetteRank.html), which is base on the same principle. Thanks for letting us know.

**Comment by bernard2012** [comment]
Hi Jennifer, 
It seems that the path is misspecified, because it is strange to begin a path with "/Giotto/silhouetteRank_output//result_5000_0.95_0.100". Usually it should be something like /home/<username>/Downloads/Giotto...
The silhouetteRankTest requires GNU parallel to be installed separately to work.
I also need to see the full command to better diagnose the problem.

**Comment by jenniferfranks** [comment]
Thanks, I think I figured out the issue. There was a set of parentheses earlier in my filepath and changing that seems to fix the issue. The same issue pops up in doHMRF. Still not entirely sure why the issue happens, because other files are created (such as genes.txt in doHMRF), but hopefully that helps.

**Comment by bernard2012** [comment]
Oh great.

**Comment by wxcjl0919** [comment]
> Thanks, I think I figured out the issue. There was a set of parentheses earlier in my filepath and changing that seems to fix the issue. The same issue pops up in doHMRF. Still not entirely sure why the issue happens, because other files are created (such as genes.txt in doHMRF), but hopefully that helps.

Hi Jennifer,

I've got the same problem, could you tell me how to fix that?

Best,
Xin
