### ISSUE TITLE
Unable to Download Giotto Suite from Github

### ISSUE THREAD

**Issue by u-gom-a** [giotto-suite/Giotto#844]
Recently, I am unable to download the Giotto package for installation. In the past I have been able to use the following command while following the CosMx vignette without issue:

`devtools::install_github("drieslab/Giotto@suite")`

As of last week this command fails to successfully install the package. I have attempted different iterations. This includes "Giotto@suite_modular" and "Giotto@HEAD" but these both result in the same error. 

The only repository I am able to download is `devtools::install_github("drieslab/Giotto@master")` , however this loads version. 1.1.2 I'm not very savvy with R, but any assistance with this would be GREATLY appreciated.

...

**Error Message**

<details>

```r
# Downloading GitHub repo drieslab/Giotto@suite
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/drieslab/Giotto/tarball/suite' failed
```
</details>

**To Reproduce**

Steps to reproduce the behavior, i.e.:
1. Following tutorial file '"Nanostring CosMx Subcellular Lung Cancer"'
2. Run function(s): 
'if(!"Giotto" %in% installed.packages()) {
  devtools::install_github("drieslab/Giotto@suite")
}'
3. See error 

**Expected behavior**
Giotto Suite should be installed 

Please replace the following according to your machine:
 - OS: Windows
  - Version [e.g. 4.0.1]
    - R
    - Giotto
    - Python

**Comment by jiajic** [comment]
Hi @u-gom-a 

We have also been noticing this issue, but we are not sure what is causing it. So far it seems that who it affects is random, despite similar settings and systems.
<hr>

Two possible fixes we have found are:
1. increase the timeout
```
options(timeout=1000)
devtools::install_github("drieslab/Giotto")
```
2. use *pak* to install
```
install.packages("pak")
pak::pkg_install("drieslab/Giotto")
```

Best,
George

**Comment by u-gom-a** [comment]
Thanks George,

Increasing the timeout worked for me.

Best,

ugoma
________________________________
