### ISSUE TITLE
Spots does not align across tissue 

### ISSUE THREAD

**Issue by RolantusdataExp** [giotto-suite/Giotto#854]
Dear Giotto, 
Thanks for a great tool! 
I just did my first analysis using Giotto, and just got pointed out that the spots in SpatPlot/SpatPlot2D look rather small, and does not cover the whole tissue. As you can see here: 
![Giotto_tissue_visium_spatplot2d](https://github.com/drieslab/Giotto/assets/75480608/523fcb5d-165e-4d6a-8f38-0afcb9a4aa97)
I would expect it to look more like this where the points covers the whole tissue: 
<img width="459" alt="Skærmbillede 2024-01-04 kl  09 25 31" src="https://github.com/drieslab/Giotto/assets/75480608/c35336a6-a80e-42b2-8f00-b101e386ff8d">

So my question is: How do I obtain an image_output where I get the "correct" size dots that repressents tissue location? 

Regards, 
Peter

**Comment by Zockimonster** [comment]
I have the same issue:
![image](https://github.com/drieslab/Giotto/assets/133122445/0a724126-b739-4b1d-a122-6b92d5283b44)
But if I load the image with Seurat, the alignment is correct...

**Comment by josschavezf** [comment]
Hi, @RolantusdataExp you can increase the point size using the argument point_size = 5 or any value that works better for you. 

e.g:

spatPlot2D(gobject = visium_brain,  point_size = 5)
