### ISSUE TITLE
How to add cell-type annotation in tutorial of mouse Visium kidney??

### ISSUE THREAD

**Issue by ti-spat** [giotto-suite/Giotto#88]
Hi,

Thank you for your developing Giotto and kind tutorials.
I'm currently demonstrating tutorials and have a question.

The mouse Visium kidney tutorial part 7 suggested that we can add cell type annotation based on the procedure of mouse Visium brain dataset.
However, I still didn't understand what kind of codes I should prepare for running "PAGE" and "RANK" methods.

https://rubd.github.io/Giotto_site/articles/mouse_visium_kidney_200916.html

In this case, do I have to add external data on my own??

It would be very grateful for your answer.

Sincerely yours,

**Comment by RubD** [comment]
Hi ti-spat,
Thanks for trying out our demonstration tutorials and your feedback. There are currently a number of different ways you can perform cell type enrichment within Giotto:

1. based on single-cell RNA-seq normalized count matrix and an accompanying vector of cell cluster annotations for that dataset:
You could then use makeSignMatrixRank to create a rank matrix and use this as input for runRankEnrich

2. based on lists of cell type specific marker genes:
You could then provide these lists of cell type specific marker genes to makeSignMatrixPage to create a matrix that can be used as input for runPAGEEnrich

3. Similar as to point 2 you can also run a simple runHyperGeometricEnrich test

4. Finally, you can perform deconvolution using single-cell RNA-seq data with the function runDWLSDeconv function.  This is still in the beta-phase, but we're seeing pretty good results.

5. Alternatively, you can also use some of the other methods that have been recently published to perform deconvolution and then transfer the results to Giotto. This probably requires a little bit more work, but I'm happy to assist.


I'll try to create a HOWTO for these different options in the near future. It's on my to-do list and will be available here: https://rubd.github.io/Giotto_site/articles/tut7_giotto_enrichment.html 


Best

**Comment by ti-spat** [comment]
Hi Ruben,
Thanks for quick, kind and detail instructions!
I'd like to try these methods using suggested functions in order.

I also look forward updates!

Best
