### ISSUE TITLE
Maybe need to update code for checking data class?

### ISSUE THREAD

**Issue by WT215** [giotto-suite/Giotto#89]
Hi,

Thank you for your nice package!

I got the following error:
```
Warning message:
In if (class(inputmatrix) %in% c("data.frame", "matrix"))
```
In current version R 4.0.3, instead of `matrix`, the class of matrix is
```
> class(Dat_cast1$Data)
[1] "matrix" "array" 
```
Hence the relevant code need to be udpated.

**Comment by RubD** [comment]
Hi Wenhao,

Thanks for the feedback. I've quickly fixed the issue. 

`inherits(inputmatrix, what = c('data.frame', 'matrix'))`

In the future we'll use safer approaches to check an object class!

Ruben
