### ISSUE TITLE
 Error: 'miniconda_path' is not an exported object from 'namespace:reticulate' 

### ISSUE THREAD

**Issue by yanwengong** [giotto-suite/Giotto#91]
Hi. 

I created a Conda env called giotto where I install all the required python package through conda install (note I have anaconda3 instead of miniconda ). 

python_path <- "/Users/your_username/anaconda3/envs/giotto/bin/python"
instrs = createGiottoInstructions(show_plot = TRUE,
                                  save_plot = TRUE,
                                  save_dir = results_folder,
                                  python_path = python_path)

I got the error of "Error: 'miniconda_path' is not an exported object from 'namespace:reticulate'"

Then, I tried to use the following code to install the python packages automatically:
python_path = NULL 
if(is.null(python_path)) {
  installGiottoEnvironment(force_miniconda = TRUE)
}

Got the same error " Error: 'miniconda_path' is not an exported object from 'namespace:reticulate' "

Do you know what's happening?

**Comment by RubD** [comment]
Hi,

Can you try to install the Giotto environment like `installGiottoEnvironment(force_miniconda = TRUE)` from a fresh R session? So without loading any other library (besided Giotto) or running a prior analysis. This should normally work.

If that works I can further try to figure out why you can not provide your own python path. That should normally work. Which reticulate version are you using?

**Comment by yanwengong** [comment]
Hi. I tried installGiottoEnvironment(force_miniconda = TRUE) from a fresh R session, but still get " Error: 'miniconda_path' is not an exported object from 'namespace:reticulate'" 

 packageVersion("reticulate")
[1] ‘1.13’

**Comment by RubD** [comment]
Ok, thanks for the feedback. I think it's related to the version of reticulate you're using. If you upgrade to the newest version it should work. I think anything > 1.15 should actually work. If this solves the issue, then I'll also update this in Giotto.

**Comment by yanwengong** [comment]
Hi. I updated reticulate to ‘1.18’ and it worked. Thanks for the suggestion!
