### ISSUE TITLE
error in spatialDWLS

### ISSUE THREAD

**Issue by patrickjdanaher** [giotto-suite/Giotto#92]
Hi GC,

I'm getting an error when I run spatialDWLS. My call is 

```sdw = runDWLSDeconv(gobject = gobj,  
                    expression_values = c("normalized"),
                    logbase = 2,
                    cluster_column = "cluster",
                    sign_matrix = SpatialDecon::safeTME[usegenes, ],
                    n_cell = 100,
                    cutoff = 2,
                    name = NULL,
                    return_gobject = TRUE)
```

And the error is:
```
Error in rowMeans(2^expr_values - 1, dims = 1) : 
  'x' must be an array of at least two dimensions
```

Do you have any advice on resolving this? I can email the giotto object I'm using if it helps debug.

Thanks,
Patrick

**Comment by gcyuan** [comment]
Hi Patrick

Thanks for letting me know. We are aware of this problem. Rui is looking into this. We will give you an update as soon as we can.

Best
GC

**Comment by rdong08** [comment]
Hi Patrick,

Thanks a lot for your interested in our spatialDWLS. I am working on this problem. Would you please share your Gobject and signature matrix to rdong1989@gmail.com if possible?
Thanks.

Best,
Rui

**Comment by patrickjdanaher** [comment]
I think I've figured it out: I've been using the "suite" branch of giotto. When I switched to the master branch, runDWLSDeconv() ran just fine. 

Thanks @rdong08  for your help.

**Comment by ndelrossi7** [comment]
Hey @patrickjdanaher! @rdong08 fixed this error yesterday - the updates have also been pushed to the suite branch so you should be able to use them there as well.
