### ISSUE TITLE
Giotto installation Error: object 'get_dimReduction' is not exported 

### ISSUE THREAD

**Issue by jiangzh-coder** [giotto-suite/Giotto#941]
Hi

i used newest installation steps from "https://drieslab.github.io/Giotto_website/articles/ecosystem.html",
then i tried to install "SgsAnnDataV2" from "https://github.com/bio-xtt/SgsAnnDataV2".

# Necessary for installation from R
if(!"pak" %in% installed.packages()) {
  install.packages("pak")
}
pak::pkg_install("drieslab/Giotto")
pak::pkg_install('drieslab/GiottoClass')
pak::pkg_install('drieslab/GiottoUtils')
pak::pkg_install('drieslab/GiottoVisuals')
pak::pkg_install('drieslab/GiottoData')
# Ensure Giotto Suite is installed
if(!"Giotto" %in% installed.packages()) {
  pak::pkg_install("drieslab/Giotto")
}
library(Giotto)
# Ensure Giotto Data is installed
if(!"GiottoData" %in% installed.packages()) {
  pak::pkg_install("drieslab/GiottoData")
}
library(GiottoData)
# Ensure the Python environment for Giotto has been installed
genv_exists = checkGiottoEnvironment()
if(!genv_exists){
  # The following command need only be run once to install the Giotto environment
  installGiottoEnvironment()
}
library(Giotto)

devtools::install_github("bio-xtt/SgsAnnDataV2")
############However, i met following errors:
Error: object 'get_dimReduction' is not exported by 'namespace:Giotto'
Execution halted
ERROR: lazy loading failed for package 'SgsAnndata2023'
* removing 'C:/Users/zhou_/AppData/Local/R/win-library/4.3/SgsAnndata2023'
Warning message:
In i.p(...) :
  安装程序包‘C:/Users/zhou_/AppData/Local/Temp/RtmpsTV6mt/file2184d4d4900/SgsAnndata2023_0.2.0.tar.gz’时退出狀態的值不是0

########the 2nd error is: when i tried to load "
Failed with error:  ‘lazy-load database 'C:/Users/zhou_/AppData/Local/R/win-library/4.3/Giotto/R/Giotto.rdb' is corrupt’

Thank you and Best wishes
Jiang

**Comment by josschavezf** [comment]
Hi @jiangzh-coder we have made several recent updates to the package, are you still facing this issue?

**Comment by jiajic** [comment]
`get_dimReduction()` is a deprecated function that has since been made internal. The new exported function that replaces it is `getDimReduction()`. From the discussion on [SgsAnnDataV2](https://github.com/bio-xtt/SgsAnnDataV2/issues/1),  it looks like this should be resolved with their newest version.
