### ISSUE TITLE
Error in  DWLS deconvolution result with Pie plots

### ISSUE THREAD

**Issue by Umaarasu** [giotto-suite/Giotto#947]
Hi,

I have not been able to run this below command. Is there a way to solve this?

spatDeconvPlot(visium,   show_image = T,    radius = 250,   save_param = list(save_name = "spat_DWLS_pie_plot"))

Error in gimage@mg_object[[1]] : 
  object of type 'externalptr' is not subsettable

Thanks!

**Comment by RubD** [comment]
If you set `show_image = F` it will probably work. It looks like a problem with the image attached to this giotto object. Is this from a saved giotto object and do you use the functions `saveGiotto` and `loadGiotto`?

**Comment by Umaarasu** [comment]
@RubD No, this not a saved Giotto object. Thanks, changing to 'F' works.
