### ISSUE TITLE
error in installing Giotto

### ISSUE THREAD

**Issue by LinZhang1004** [giotto-suite/Giotto#958]
Hi I'm installing Giotto on our server, which is running in Ubuntu 20.04.5 LTS. We installed R version 4.2.2.

During the middle of the installation, I saw an error which says:

Error in loadNamespace(j <- imp[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
   namespace ‘Matrix’ 1.5-4.1 is already loaded, but >= 1.6.2 is required
Calls: <Anonymous> ... namespaceImportMethods -> <Anonymous> -> loadNamespace
Execution halted

At the end, it shows:

ERROR: dependencies ‘GiottoClass’, ‘GiottoVisuals’ are not available for package ‘Giotto’
  removing ‘/usr/local/lib/R/site-library/Giotto’
Warning messages:
1: In i.p(...) :
  installation of package ‘/tmp/RtmpUE9Hw7/fileb06a20b75d23/GiottoClass_0.3.0.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/tmp/RtmpUE9Hw7/fileb06a77aea28/GiottoVisuals_0.2.0.tar.gz’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/tmp/RtmpUE9Hw7/fileb06a216d6835/Giotto_4.0.6.tar.gz’ had non-zero exit status

Do you know which particular packages should be updated or installed in order to fix these error? Thanks a lot!

**Comment by josschavezf** [comment]
Hi @LinZhang1004, there is a most recent version of Matrix (1.7-0), I suggest updating this package using install.packages("Matrix")

**Comment by LinZhang1004** [comment]
Thank you! It works now, and I've installed Giotto.
