### ISSUE TITLE
createGiottoCosMxObject: Error in cat

### ISSUE THREAD

**Issue by GBeattie** [giotto-suite/Giotto#960]
**Describe the Error**

Hi,

I'm following the a "nostring CosMx Subcellular Lung Cancer" vignette and am getting an error when using createGiottoCosMxObject

**Error Message**

```
> fov_join <- createGiottoCosMxObject(cosmx_dir = data_path,
+                                     data_to_use = 'subcellular', # only subcellular
+                                     FOVs = c(2,3,4),
+                                     instructions = instrs)
A structured CosMx directory will be used
Checking directory contents...
   > CellLabels folder found
   > CompartmentLabels folder found
   > CellComposite folder found
   > CellOverlay folder found
   > transcript locations file found
   > fov positions file found
   > expression matrix file found
   > metadata file found
Directory check done
Loading subcellular information...
Loading FOV offsets...
Loading transcript level info...
|--------------------------------------------------|
|==================================================|
Subcellular load done
Splitting detections by feature vs neg probe
  > Features: 25875734
  > NegProbes: 182648
Loading image information...
Image load done
[ FOV 002 ]
Assigning FOV feature detections...
Building subcellular giotto object...
polygonlist is a list with names
[ cell ] Process polygon info...
Error in cat(..., sep = sep) : 
  argument 1 (type 'list') cannot be handled by 'cat'
```

**System Information**

Please replace the following according to your machine:
 - OS: MacOS 14.5
 - Version
    - R: 4.4.0
    - Giotto: 4.0.6
    - Python: Instructions above generate this output: EnvironmentLocationNotFound: Not a conda environment: /Users/gordonbeattie/Library/r-miniconda-arm64/envs/giotto_env/bin/pythonw, although this might not be the issue.

**Comment by josschavezf** [comment]
Hi @GBeattie I fixed this particular issue in the development branch. You can install it using remotes::install_github("dries lab/Giotto@suite_dev") We will update the main branch soon.

**Comment by GBeattie** [comment]
Thanks, that helped, just needed dev branch of GiottoClass as well, so for anyone with same issue this worked for me:

```
remotes::install_github("drieslab/GiottoClass@dev")
remotes::install_github("drieslab/Giotto@suite_dev")
```
