### ISSUE TITLE
get10Xmatrix: Unable to read Visium matrix if total unique spatial barcodes <4992

### ISSUE THREAD

**Issue by MarkZaidi** [giotto-suite/Giotto#97]
Greetings,

I've used the get10Xmatrix to import previous Visium datasets. One of our 4 samples processed in batch with identical parameters throws an error when attempting to generate the sparse matrix at the end of get10Xmatrix.

From my understanding, it seems like the error pertains to the matrix.mtx file. Each row is a "read", and each column is a different value corresponding to the read. gene_id_num is a numerical identifier of the gene name gene_id. cell_id is the specific spot that the read came from, and there should be 4992 unique entries of cell_id. If 2 rows contain the same transcript from the same spot, umi is incremented from 1 by 1. The problem here is that there are no transcripts that originate from one specific spot (cell). This causes the number of unique entries of cell_id to be equal to 4991 instead of 4992.

Using docker image: [docker-giotto-1.0.2.7z](http://spatialgiotto.rc.fas.harvard.edu/docker-giotto-1.0.2.7z) 

Raw feature matrix which throws the error:
[raw_feature_bc_matrix.zip](https://github.com/RubD/Giotto/files/6474817/raw_feature_bc_matrix.zip)

If there is an updated version where this issue is resolved, could you point me to where I can find the docker image? Furthermore, do I need to do a separate install as outlined in (http://spatialgiotto.rc.fas.harvard.edu/giotto.install.docker.html), or is there a way to update existing images?

**Comment by RubD** [comment]
Hi,

I tried reading your raw feature matrix with the latest Giotto version (cless or master branch) and it worked. I'll try to see if we can create a new or update the existing docker image, but if you could install Giotto directly from github in R or Rstdudio then you could already move forward.

Let me know if there are any further issues.

Best,
Ruben

**Comment by MarkZaidi** [comment]
Thanks, I followed the instructions in http://spatialgiotto.rc.fas.harvard.edu/giotto.install.native.html to update to the latest version, and the issue is resolved.
