### ISSUE TITLE
seuratToGiottoV5

### ISSUE THREAD

**Issue by worthing1016** [giotto-suite/Giotto#975]
**Describe the Error**
When I am using the seuratToGiottoV5() function, I encountered the following error. I am using Seurat version 5.1.0, and I would like to know how to resolve this issue

**Error Message**

Error in seuratToGiottoV5(sobject, spatial_assay = "Spatial", dim_reduction = c("pca", "umap"), subcellular_assay = "Vizgen", sp_network = NULL, nn_network = NULL, verbose = TRUE): 
  there is no function "seuratToGiottoV5"

    - R 4.4.1
    - Giotto
    
**Additional context**
![微信截图_20240704142633](https://github.com/drieslab/Giotto/assets/174586203/dfbcc6af-40f5-410c-9dc3-4e1a1ee6b108)

**Comment by iqraAmin** [comment]
Hi @worthing1016,

Could you please provide me with your session info? Also, if possible, could you provide a subset of your data so I can reproduce the error?

Thanks!

**Comment by worthing1016** [comment]
> Hi @worthing1016,
> 
> Could you please provide me with your session info? Also, if possible, could you provide a subset of your data so I can reproduce the error?
> 
> Thanks!

/
/

**Comment by worthing1016** [comment]
> Hi @worthing1016,
> 
> Could you please provide me with your session info? Also, if possible, could you provide a subset of your data so I can reproduce the error?
> 
> Thanks!

Thank you very much for your reply. I have already resolved the issue. It was caused by my Giotto version being too low
